### ISSUE TITLE
CKAN support for Heroku + OpenShift

### ISSUE THREAD

**Issue by rufuspollock** [ckan/ckan#1075]
See http://trac.ckan.org/ticket/2810 plus existing branch
## Why?
- Make it much easier for folks to deploy and try out CKAN
## What
- Configure for Heroku including procfile etc
- (?) Run the data store in main DB
- [optional] Support DB only search (no solr)
## Who

I'd be willing to make this happen :-)

**Comment by rimolive** [comment]
I know this issue has been opened since 2013 but anyone made any progress? As for the new OpenShift, having a Docker image is 80% of the job done but I tested the Docker Image by following https://github.com/ckan/ckan/blob/4a3b375/doc/maintaining/installing/install-using-docker.rst and it returned HTTP 500.
