### ISSUE TITLE
Select boxes with autocomplete are clearing their placeholders

### ISSUE THREAD

**Issue by vitorbaptista** [ckan/ckan#1278]
For example, go to the ```Add Resource``` page. The placeholder ```eg. CSV, XML or JSON``` disappears whenever we activate ```select2``` in https://github.com/okfn/ckan/blob/master/ckan/public/base/javascript/modules/autocomplete.js#L76.

The problem seems to be when we upgraded ```select2``` in 7e7b24ba9cfcd9c9916703d3bbc2d0c1657e3efc.

At first I thought it was because we use the ```placeholder``` attribute in the element, and not ```data-placeholder```, but it doesn't seem to be the case.

@domoritz Do you have any idea of how to fix it?

**Comment by rossjones** [comment]
Does https://github.com/ckan/ckan/commit/f285d7fded749494f53c94a4589afbeda1e40c09 close this?

Either way ..

This issue is being closed as it is more than 18 months old.  If you are still experiencing this problem and wish to help investigate further, or submit a PR, please feel free to re-open it.
