### ISSUE TITLE
CSV previewer should have configurable separators

### ISSUE THREAD

**Issue by strainu** [ckan/ckan#1296]
See http://date.gov.ro/dataset/siruta/resource/a0a67c05-6714-486f-93ab-c9bad0f4561a

The data item is a csv file using ';' as separator, but CKAN is not able to show the file correctly

**Comment by mattfullerton** [comment]
Is the file-loading mechanism actually using Recline's CSV backend or rather the Dataproxy backend? Perhaps if messytables was upgraded in the Dataproxy instance (https://github.com/okfn/dataproxy/tree/master/dataproxy/vendor), this problem would go away? @domoritz @rgrp - jog any memories?

**Comment by domoritz** [comment]
Sorry, it's been a while. I don't really remember any of the specifics and don't think I can help much.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by the42** [comment]
Sorry guys, but for all these countries which use the comma ',' as a separator to delineate numeric prefix from postfix, the Windows operating system defines the semicolon ';' as the list separator and Excel picks up this separator ';' to separate columns when saving as CSV. This is the case for German speaking countries in Europe. As such having this feature as an option would be huge win to have proper preview. Or even better to re-use some intelligent logic taken from CSVLint to make an educated guess that the CSV separator character in a given CSV file is.

**Comment by mattfullerton** [comment]
I live and work in Germany and support users in Germany so can only echo the pain here. That said I think the position is clear but hasn't enough teeth: this method of getting CSV files into a form for the data preview is no longer supported. In order to figure this out though you first have to look at the code:

https://github.com/ckan/ckan/blob/master/ckanext/reclineview/theme/public/vendor/recline/recline.js#L9 (onwards)

And then go to the repository: https://github.com/okfn/dataproxy ...

The recommended way to get CSV previews _is to let CKAN push your data into the datastore_.

A closer look shows that another OKF project, messytables, is used to parse the CSV data. The latest version of messytables is used when deploying (git submodule). Hence I suspect that if someone "redeployed" the dataproxy we would handle semicolons as separators just fine, because messytables is _exactly what is used to deal with this_ when importing to datastore (which handles semicolons well).

If someone at OKF gives me a 5 minute primer on what Google Apps Engine is and the necessary rights to run a test replacement dataproxy and then switch to it, I happily volunteer to solve this problem. @danfowler @rgrp  It saves me time explaining this at regular interval in the long run :wink: 

The overall problem is that we are using a CKAN-independent thing to do this: recline, so we can't easily build in the use of CKAN's resourceproxy which would make things much much simpler. But with some effort it would be possible.

Alternatively, CKAN team please turn off previews for CSV files without datastore, as it is just confusing users so so much and leaving a really bad impression.

**Comment by skasberger** [comment]
+1 on @the42 and @mattfullerton !

**Comment by marcomb** [comment]
Hallo, do you have any update on this issue? I am still interested to have this functionality and to support of the preview of different type of CSV (Comma, Semicolon, Tab).

**Comment by mattfullerton** [comment]
@marcomb Is setting up datastore and datapusher an issue for you?
