### ISSUE TITLE
Can't find drafts

### ISSUE THREAD

**Issue by mwainwright** [ckan/ckan#1545]
Draft datasets are hard to find - they are only on the creator's dashboard (under 'My datasets'), where they may be buried in other datasets.

Improvements:

* A filter on the dashboard which allows you to view draft datasets only
* Ability for sysadmins to include draft datasets in search results

**Comment by rossjones** [comment]
This issue is being closed as it is more than 12 months old.  If you are 
still experiencing this problem and wish to help investigate further, 
please feel free to re-open it.

**Comment by ThrawnCA** [comment]
This was never actually implemented, and it would be a useful feature to have.

On our current CKAN system, one of our org admins wants to delete an obsolete organisation - but he can't, because it has draft datasets. And they're not easily visible to him; if he were more technically skilled, he could assemble a `package_search` API call that would retrieve them, but there's no web UI for it.

**Comment by ThrawnCA** [comment]
This just came up again, and even when I tried using the package_search API with `include_drafts=True&include_deleted=True&include_private=True`, the datasets didn't show up. I had to go directly to the database to find them.
