### ISSUE TITLE
Ubuntu 14.04 LTS support

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#1651]
We should aim to support Ubuntu 14.04, probably by next release.

I'd expect the main issues would be on installation instructions and libraries / requirements compatibility.

Things to check:
http://packages.ubuntu.com/trusty

* [x] Postgres 9.3 - SQL commands (eg datastore)
* [x] Solr 3.6 - Solr 4 has been widely used across CKAN instances, so I wouldn't expect problems here
* [x] Libraries versions (see eg #1635)
* ...

**Comment by badbruce07** [comment]
I have some issues in setting up on ubuntu 14.04 LTS regarding jetty server and schema.xml. How can I resolve this issue?

**Comment by florianm** [comment]
What issues are you running into exactly? I posted a more detailed walk through on [open-data](https://github.com/opendata/CKAN-Multisite/issues/10), hope that helps.

**Comment by frogsapo** [comment]
I'm newbie to CKAN and I'm trying to install it from sources on Ubuntu 14.04 LTS.
I followed the current version of the [CKAN install guide](http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html) and hit the solr-jetty snag mentioned by @rparrapy and @badbruce07 as well as some [other folks](http://stackoverflow.com/questions/30355839/ckan-local-installation-500-error-on-solr-jsp-support-not-configured) which brought me to this discussion.

As I understand it (and my understanding is very limited) this solr-jetty bug probably has to do with an ill packaged old version (6 apparently) of jetty on Ubuntu 14.04 but alas the tomcat-coyote.jar workaround mentioned by @Hoedic, that did the trick for @pwhipp, didn't work for me. And as newbie, the "install solr manually" path (documented by @florianm ) looks quite steep to me. 

Hence, if want to install from sources while remaining in CKAN's mainstream, what would you guys - as CKAN advanced users and experts - recommend :
1. have my sysadmin install an Ubuntu 12 vm and start from there ?
2. try the "solr manual install" ?
3. go for installing jetty version 8 ? 
4. another path I missed while googling ?
Thanks.

**Comment by amercader** [comment]
Just today I've installed Solr on Ubuntu 14.04 without any problem (`sudo apt-get install solr-jetty` + edit the `/etc/default/jetty` file), so I wonder if there is something weird with old versions.

Here's my server version:

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.3 LTS
Release:        14.04
Codename:       trusty

```

And the `solr-jetty` package details:

```
dpkg -s solr-jetty
Package: solr-jetty
Status: install ok installed
Priority: optional
Section: java
Installed-Size: 70
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: all
Source: lucene-solr
Version: 3.6.2+dfsg-2
Depends: jetty (>= 6.1.22), libjetty-extra-java (>= 6.1.22), solr-common (= 3.6.2+dfsg-2), default-jdk | java5-sdk
Conflicts: solr-tomcat, solr-tomcat6
Description: Enterprise search server based on Lucene3 - Jetty integration
 Solr is an open source enterprise search server based on the Lucene
 Java search library, with XML/HTTP and JSON APIs, hit highlighting,
 faceted search, caching, replication, and a web administration
 interface. It runs in a Java servlet container such as Tomcat.
 .
 This package provides the Jetty integration files for Solr.
Original-Maintainer: Debian Java Maintainers <pkg-java-maintainers@lists.alioth.debian.org>
Homepage: http://lucene.apache.org

```

Having said that, I've never had any problems with `solr-tomcat` so worth checking it if you can't get Jetty to work.

**Comment by amercader** [comment]
TODO on the Ubuntu 14.04 support front:

- [ ] Build deb packages for Ubuntu 14.04
- [ ] Run tests on Ubuntu 14.04
- [ ] Review install instructions to make sure they work on 12.04 and 14.04

**Comment by frogsapo** [comment]
Dear Adrià Mercader,

Thanks a lot for your concern and quick response.

I put my glasses on and checked both the outputs of the commands
'lsb_release -a' and 'dpkg -s solr-jetty' as gotten on my server.
And I got _exactly_ the same responses (which surprised me since
I thought there was much more system diversity to allow for such
similarity).

Maybe I got lost in trying too many kludges on this bug. I shall
start again from a clean slate and ask my sysadmin for a re-install
of my Ubuntu 14.04 VM. From there I'll try with just the instructions
of your email...

My lab (I work in french academia) needs CKAN so bad for one
of its projects (a partnership with the folks handling the CKAN
powered http://data.grandlyon.com/acceder-aux-donnees/ )
that I need to get this working.

Thanks again for your help,
Yours,
Eric Boix
https://liris.cnrs.fr/membres?idn=eboix

**Comment by brylie** [comment]
Is there any plan to provide a containerized installation option (e.g. Docker)?

**Comment by florianm** [comment]
Hi all, fwiw we are moving from a source install towards using datacats, which combines ckan with docker and containerises the yucky bits like solr nicely. Full setup docs for my datacats/aws recipe are at govhack2015.readthedocs.org - feedback welcome!

**Comment by florianm** [comment]
@frogsapo @brylie here's the link: http://govhack2015.readthedocs.org/en/latest/ this could fix your problems. let us know how you go, your feedback is highly appreciated!

**Comment by frogsapo** [comment]
This is just to post some positive feedback on installing ckan-2.4.1 on Ubuntu 14.04.3 LTS as experienced by a CKAN newbie. As advised above in this discussion I eventually went for the solr-tomcat installation (instead of Jetty) and everything went smoothly.

My first CKAN server is alive and that's cool !

The following are just some remarks/comments concerning the [CKAN docs](http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html) that might be of some help to other beginners:
 * The list of packages is `sudo apt-get install python-dev postgresql libpq-dev python-pip python-virtualenv git-core solr-tomcat` i.e. you can omit openjdk-6-jdk (actually solr-tomcat pulls the version 7 of the openjdk)
 * On step 5 (Setup Solar) restarting solr is done with `sudo service tomcat6 restart`. The default port of solr configuration is now 8080 instead of 8983. Testing solr is thus done with e.g. `lynx http://localhost:8080/solr`. You will need to configure CKAN's development.ini accordingly.
 * Invert the realization of step 7 and 8, that is go first for step 8 (Link to who.ini) and only then step 7 (Set up the Datastore). Otherwise when testing CKAN at the end of step 7 (with e.g. `lynx http://127.0.0.1:5000/`) you will get error messages that are not due to your Datastore configuration (but to the missing link of step 8).
 * [Testing CKAN](http://docs.ckan.org/en/latest/contributing/test.html) will require you to edit test-core.ini to change some fields (`ckan.site_url, solr_url, sqlalchemy.url, ckan.datastore.write_url, ckan.datastore.read_url`) in accordance to what you've configured in `/etc/ckan/default/development.ini`. BTW the test-core.ini file is located in `$HOME/ckan/lib/default/src/ckan/`. When running the tests I ended up with roughly 9 E (errors), 26 F (failures) and 13 S (might stand for Skipped?). I don't know how to interpret such results but the server seems responsive...
 * I'm now looking for a service init script for ckan (to place in /etc/init.d/). For the time being I understood that launching ckan is done manually with `cd /usr/lib/ckan/default/src/ckan ; paster serve /etc/ckan/default/development.ini`.

**Comment by frogsapo** [comment]
@florianm this is just some quick (and probably disappointing for you) feeback on http://govhack2015.readthedocs.org/en/latest/ . 

The first line of the [details section](http://govhack2015.readthedocs.org/en/latest/#details) mentions that the installation is documented in "Alternatives" but on my web browser this looks like a dangling web link (in Red).

Since you were mentioning Datacats I used the eponymous [sidebar link](http://govhack2015.readthedocs.org/en/latest/2_Datacats/) and I quickly got the intuition that this was not targeting newbies. It seemed to me that Datacats was adding a layer on top of CKAN (that itself uses solr that in turn runs on top of jetty or tomcat) which could obfuscate things even more in case of trouble (nothing is certain but death and taxes..and nebiew configuration troubles). Since my objective (for the time being) was to gain some early understanding of CKAN (features and internals) I wen back to CKAN direct install (see above comment). Sorry for dropping that ball and thanks for helping.

**Comment by joetsoi** [comment]
(note to self) really minor doc change needed

http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html#setup-solr

change line 15 and line 18 to line 16 and line 19

**Comment by mattfullerton** [comment]
@frogsapo - if you are looking to deploy CKAN permanently from source, you should check out http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html

**Comment by mattfullerton** [comment]
@frogsapo - if you are looking to deploy CKAN permanently from source, you should check out http://docs.ckan.org/en/latest/maintaining/installing/deployment.html

**Comment by patrickval** [comment]
Hello guys,

I am deploying CKAN 2.4 on Ubuntu 14.04, with jety 6 and SOLR 4.7.2, apache2 server and Postgres 9.3 in another machine.

After climbing the services have following error:

Debug false:

Server Error
An internal server error occurred 


Debug true:

WebError Traceback:
⇝ SearchError: SOLR returned an error running query: {'sort': 'score desc, metadata_modified desc', 'fq': [u'owner_org:"73bffc86-3b1f-46c3-85d2-0fa0084ac53e" +site_id:"default" +state:active'], 'facet.mincount': 1, 'rows': 0, 'facet': u'false', 'facet.limit': '50', 'wt': 'json', 'q': '*:*', 'fl': 'id validated_data_dict'} Error: 'Not Found' 


LOG:

Error - <class 'ckan.lib.search.common.SearchError'>: SOLR returned an error running query: {'sort': 'score desc, metadata_modified desc', 'fq': [u'owner_org:"73bffc86-3b1f-46c3-85d2-0fa0084ac53e" capacity:"publi$
URL: http://150.162.6.39:5000/
File '/usr/local/lib/python2.7/dist-packages/weberror/errormiddleware.py', line 162 in __call__
  app_iter = self.application(environ, sr_checker)
File '/usr/local/lib/python2.7/dist-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/local/lib/python2.7/dist-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/local/lib/python2.7/dist-packages/fanstatic/publisher.py', line 234 in __call__
  return request.get_response(self.app)
File '/usr/local/lib/python2.7/dist-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/local/lib/python2.7/dist-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/usr/local/lib/python2.7/dist-packages/webob/dec.py', line 147 in __call__
  resp = self.call_func(req, *args, **self.kwargs)
File '/usr/local/lib/python2.7/dist-packages/webob/dec.py', line 208 in call_func
  return self.func(req, *args, **kwargs)
File '/usr/local/lib/python2.7/dist-packages/fanstatic/injector.py', line 54 in __call__
  response = request.get_response(self.app)
File '/usr/local/lib/python2.7/dist-packages/webob/request.py', line 1053 in get_response
  application, catch_exc_info=False)
File '/usr/local/lib/python2.7/dist-packages/webob/request.py', line 1022 in call_application
  app_iter = application(self.environ, start_response)
File '/usr/lib/ckan/default/src/ckan/ckan/config/middleware.py', line 389 in inner
  result = application(environ, start_response)
File '/usr/local/lib/python2.7/dist-packages/beaker/middleware.py', line 73 in __call__
  return self.app(environ, start_response)
File '/usr/local/lib/python2.7/dist-packages/beaker/middleware.py', line 155 in __call__
  return self.wrap_app(environ, session_start_response)
File '/usr/local/lib/python2.7/dist-packages/routes/middleware.py', line 131 in __call__
  response = self.app(environ, start_response)
File '/usr/local/lib/python2.7/dist-packages/pylons/wsgiapp.py', line 125 in __call__
  response = self.dispatch(controller, environ, start_response)
File '/usr/local/lib/python2.7/dist-packages/pylons/wsgiapp.py', line 324 in dispatch
  return controller(environ, start_response)
File '/usr/lib/ckan/default/src/ckan/ckan/lib/base.py', line 338 in __call__
  res = WSGIController.__call__(self, environ, start_response)
File '/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py', line 221 in __call__
  response = self._dispatch_call()
File '/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py', line 172 in _dispatch_call
  response = self._inspect_call(func)
File '/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py', line 107 in _inspect_call
  result = self._perform_call(func, args)
File '/usr/local/lib/python2.7/dist-packages/pylons/controllers/core.py', line 60 in _perform_call
  return func(**args)
File '/usr/lib/ckan/default/src/ckan/ckan/controllers/home.py', line 182 in index
  return base.render('home/index.html', cache_force=True)
File '/usr/lib/ckan/default/src/ckan/ckan/lib/base.py', line 217 in render
  loader_class=loader_class)
File '/usr/local/lib/python2.7/dist-packages/pylons/templating.py', line 249 in cached_template
  return render_func()
File '/usr/lib/ckan/default/src/ckan/ckan/lib/base.py', line 155 in render_template
  return render_jinja2(template_name, globs)
File '/usr/lib/ckan/default/src/ckan/ckan/lib/base.py', line 104 in render_jinja2
  return template.render(**extra_vars)
File '/usr/local/lib/python2.7/dist-packages/jinja2/environment.py', line 894 in render
  return self.environment.handle_exception(exc_info, True)
File '/usr/lib/ckan/default/src/ckan/ckan/templates/home/index.html', line 2 in top-level template code
  {% set homepage_style = ( g.homepage_style or '1' ) %}
File '/usr/lib/ckan/default/src/ckan/ckan/templates/page.html', line 1 in top-level template code
  {% extends "base.html" %}
File '/usr/lib/ckan/default/src/ckan/ckan/templates/base.html', line 103 in top-level template code
  {%- block page %}{% endblock -%}
File '/usr/lib/ckan/default/src/ckan/ckan/templates/page.html', line 19 in block "page"
  {%- block content %}
File '/usr/lib/ckan/default/src/ckan/ckan/templates/home/index.html', line 14 in block "content"
  {% block primary_content %}
File '/usr/lib/ckan/default/src/ckan/ckan/templates/home/index.html', line 15 in block "primary_content"
  {% snippet "home/layout{0}.html".format(homepage_style) %}
File '/usr/lib/ckan/default/src/ckan/ckan/lib/jinja_extensions.py', line 255 in _call
  return base.render_snippet(args[0], **kwargs)
File '/usr/lib/ckan/default/src/ckan/ckan/lib/base.py', line 79 in render_snippet
  renderer='snippet')
File '/usr/lib/ckan/default/src/ckan/ckan/lib/base.py', line 217 in render
  loader_class=loader_class)
File '/usr/local/lib/python2.7/dist-packages/pylons/templating.py', line 249 in cached_template
  return render_func()
File '/usr/lib/ckan/default/src/ckan/ckan/lib/base.py', line 155 in render_template
  return render_jinja2(template_name, globs)
File '/usr/lib/ckan/default/src/ckan/ckan/lib/base.py', line 104 in render_jinja2
  return template.render(**extra_vars)
File '/usr/local/lib/python2.7/dist-packages/jinja2/environment.py', line 894 in render
  return self.environment.handle_exception(exc_info, True)
File '/usr/lib/ckan/default/src/ckan/ckan/templates/home/layout1.html', line 31 in top-level template code
  {% block featured_organization %}
File '/usr/lib/ckan/default/src/ckan/ckan/templates/home/layout1.html', line 32 in block "featured_organization"
  {% snippet 'home/snippets/featured_organization.html' %}
File '/usr/lib/ckan/default/src/ckan/ckan/lib/jinja_extensions.py', line 255 in _call
  return base.render_snippet(args[0], **kwargs)
File '/usr/lib/ckan/default/src/ckan/ckan/lib/base.py', line 79 in render_snippet
  renderer='snippet')
File '/usr/lib/ckan/default/src/ckan/ckan/lib/base.py', line 217 in render
  loader_class=loader_class)
File '/usr/local/lib/python2.7/dist-packages/pylons/templating.py', line 249 in cached_template
  return render_func()
File '/usr/lib/ckan/default/src/ckan/ckan/lib/base.py', line 155 in render_template
  return render_jinja2(template_name, globs)
File '/usr/lib/ckan/default/src/ckan/ckan/lib/base.py', line 104 in render_jinja2
  return template.render(**extra_vars)
File '/usr/local/lib/python2.7/dist-packages/jinja2/environment.py', line 894 in render
  return self.environment.handle_exception(exc_info, True)
File '/usr/lib/ckan/default/src/ckan/ckan/templates/home/snippets/featured_organization.html', line 1 in top-level template code
  {% set organizations = h.get_featured_organizations() %}
File '/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py', line 1905 in get_featured_organizations
  items=config_orgs)
File '/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py', line 1936 in featured_group_org
  extras = logic.get_action(list_action)({}, {})
File '/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py', line 429 in wrapped
  result = _action(context, data_dict, **kw)
File '/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py', line 508 in organization_list
  return _group_or_org_list(context, data_dict, is_org=True)
File '/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py', line 423 in _group_or_org_list
  group_list.append(logic.get_action(action)(context, data_dict))
File '/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py', line 429 in wrapped
  result = _action(context, data_dict, **kw)
File '/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py', line 1232 in organization_show
  return _group_or_org_show(context, data_dict, is_org=True)
File '/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py', line 1171 in _group_or_org_show
  packages_field=packages_field)
File '/usr/lib/ckan/default/src/ckan/ckan/lib/dictization/model_dictize.py', line 423 in group_dictize
  group, just_the_count=True)
File '/usr/lib/ckan/default/src/ckan/ckan/lib/dictization/model_dictize.py', line 414 in get_packages_for_this_group
  q)
File '/usr/lib/ckan/default/src/ckan/ckan/logic/__init__.py', line 429 in wrapped
  result = _action(context, data_dict, **kw)
File '/usr/lib/ckan/default/src/ckan/ckan/logic/action/get.py', line 1771 in package_search
  query.run(data_dict)
File '/usr/lib/ckan/default/src/ckan/ckan/lib/search/query.py', line 364 in run
  (query, e.reason))
SearchError: SOLR returned an error running query: {'sort': 'score desc, metadata_modified desc', 'fq': [u'owner_org:"73bffc86-3b1f-46c3-85d2-0fa0084ac53e" capacity:"public" +state:active +site_id:"default"'], 'f$

Anyone know how to solve?
Thank you.

**Comment by florianm** [comment]
Hi @patrickval, 
* tongue-in-cheek suggestion: use http://www.datacats.com - docker instead of source install
* my personal opinion: use datacats
* have you copied the ckan schema into the solr core? Your solr at least runs and works.
* fwiw, I've [written up](https://github.com/opendata/CKAN-Multisite/issues/10#issuecomment-70068327) my source install adventure incl. testing solr and making sure JTS is installed correctly.
* If you want to go with datacats, I'm currently writing up my datacats install from barebone AWS EC2 VM to full stack [here](http://govhack2015.readthedocs.org/en/latest/).

Lastly, before you try datacats, give them a week or two to fix datacats/datacats#334
HTH!

**Comment by mattfullerton** [comment]
Could you consider integrating a Python 2.7.9+ interpreter into the python environment/package? This seems to be possible:
https://renoirboulanger.com/blog/2015/04/upgrade-python-2-7-9-ubuntu-14-04-lts-making-deb-package/

My reason: https://github.com/ckan/datapusher/issues/83

That said, there would be an easier fix for that issue by supplying a different config.

**Comment by amercader** [comment]
@mattfullerton See my thoughts on this here: https://github.com/ckan/datapusher/issues/83#issuecomment-151121100

**Comment by amercader** [comment]
Fixed with #2726. Please test the new docs and packages and create new issues if there are still problems.

**Comment by dportnoy** [comment]
These instructions for install of Solr worked for me: https://www.digitalocean.com/community/tutorials/how-to-install-solr-5-2-1-on-ubuntu-14-04
(uses jetty)

**Comment by mrobbin** [comment]
Hi all, i try to install CKAN on ubuntu 14.04 but still error when install solr-jetty always JSP support not configured.

**Comment by Conzar** [comment]
@mrobbin You can try using Puppet to install ckan as the puppet module supports Ubuntu 14.04 and handles installing solr.
https://forge.puppetlabs.com/landcareresearch/ckan

**Comment by mrobbin** [comment]
@Conzar ok i want to try, thank you for your solution.

**Comment by lperepol** [comment]
This issue is marked as closed. There are still issues with installing solr.
Solr install is not working as documented in : 
http://docs.ckan.org/en/latest/maintaining/installing/install-from-package.html

**Comment by mstantoncook** [comment]
I agree with @lperepol. I think it's best to have an 14.04 alternative route/option in the docs that involves compiling jetty (3.6.2) from source. I'm happy to test/write the docs.
