### ISSUE TITLE
A simple CkanCommand that loads the app config shouldn't connect to the database/solr

### ISSUE THREAD

**Issue by nickstenning** [ckan/ckan#1785]
While refactoring part of the datastore (the `set-permissions` command) I discovered that a command as simple as:

```python
from ckan.lib import cli

class MyCommand(cli.CkanCommand):
    summary = "Do a thing"
    
    def command(self):
        self._load_config()
        print "Hi"
```

will attempt to connect to a) the database(s) and b) Solr. This makes writing and debugging simple commands much more tedious, as one has to ensure that databases and Solr cores are configured properly, even if the command in question makes no use of them.

I had a quick dig -- not enough to identify the cause of the problem definitively -- and it looks like `ckan.config.load_environment`, particular the plugin loader, might be responsible.

**Comment by rossjones** [comment]
Being able to avoid the solr schema check, and only have connection-oriented things do so on first use is probably sendible for paster commands though because we want the server to crash immediately if it can't find them at server-run time.

Unfortunately this issue is old and un-addressed, and so, inline with current ticket-gardening, I am going to close it unless someone feels they have the time to submit a PR.
