### ISSUE TITLE
Documentation fails to guide me through installation of the datastore

### ISSUE THREAD

**Issue by bartaelterman** [ckan/ckan#1889]
I'm installing CKAN from a .deb package on Ubuntu as documented [here](http://docs.ckan.org/en/latest/maintaining/installing/install-from-package.html).

Following all the steps as documented, I get an error when I set the permissions. When I run `sudo ckan datastore set-permissions`, I get the message: 

    Perform commands to set up the datastore.
    Make sure that the datastore URLs are set properly before you run
    these commands.

    Usage::

        paster datastore set-permissions SQL_SUPER_USER

    Where:
        SQL_SUPER_USER is the name of a postgres user with sufficient
                       permissions to create new tables, users, and grant
                       and revoke new permissions.  Typically, this would
                       be the "postgres" user.

Both datastore urls (write and read) are uncommented in my ckan configuration file (note that the documentation points me to the configuration file `/etc/ckan/default/production.ini `, but I have the impression that the datastore is looking at a different configuration file in which case this should be updated in the documentation)

For the record:

- I'm using postgres 1.9.14. (EDIT: that's 9.1.14)
- I also tried using the paster command as shown in the message that I get. However, I don't have paster, so I used the paster executable in `/usr/lib/ckan/default/bin/` but that one says `Command 'datastore' not known`.
- I opened a psql session and gave all the sql commands as documented in `set_permissions.sql` (replacing the variables by the proper database and user names) and was able to set all the permissions that way.

Otherwise, brilliant work. Love to hear from you soon.

**Comment by fiblan** [comment]
In 2.3 the correct command is :
```
. /usr/lib/ckan/default/bin/activate
paster --plugin=ckan datastore set-permissions -c /etc/ckan/default/production.ini
```
without "postgres"

**Comment by Aung-Myint-Thein** [comment]
Thanks... Now I am trying to duplicate the whole machine and trying to set up everything from scratch. I have 2 dump files. one for main_data (ckan_default) and ckan_datastore (datastore's DB).

However, when I run $ paster --plugin=ckan db load <dump_file> -c /etc/ckan/default/prod.ini, it will always load load the data into main_data (ckan_default).

I have set up the permission of Datastore User  too. What can I do and how can i specify the name of database so that I can load into both databases. Really appreciated.

**Comment by mrobbin** [comment]
i try and get result

297 WARNI [ckanext.datastore.plugin] Omitting permission checks because you are running paster commands.
/*
This script configures the permissions for the datastore.

It ensures that the datastore read-only user will only be able to select from
the datastore database but has no create/write/edit permission or any
permissions on other databases. You must execute this script as a database
superuser on the PostgreSQL server that hosts your datastore database.

For example, if PostgreSQL is running locally and the "postgres" user has the
appropriate permissions (as in the default Ubuntu PostgreSQL install), you can
run:

    paster datastore set-permissions | sudo -u postgres psql

Or, if your PostgreSQL server is remote, you can pipe the permissions script
over SSH:

    paster datastore set-permissions | ssh dbserver sudo -u postgres psql

*/

-- Most of the following commands apply to an explicit database or to the whole
-- 'public' schema, and could be executed anywhere. But ALTER DEFAULT
-- PERMISSIONS applies to the current database, and so we must be connected to
-- the datastore DB:
\connect datastore_default

-- revoke permissions for the read-only user
REVOKE CREATE ON SCHEMA public FROM PUBLIC;
REVOKE USAGE ON SCHEMA public FROM PUBLIC;

GRANT CREATE ON SCHEMA public TO "ckan_default";
GRANT USAGE ON SCHEMA public TO "ckan_default";

GRANT CREATE ON SCHEMA public TO "ckan_default";
GRANT USAGE ON SCHEMA public TO "ckan_default";

-- take connect permissions from main db
REVOKE CONNECT ON DATABASE "ckan_default" FROM "datastore_default";

-- grant select permissions for read-only user
GRANT CONNECT ON DATABASE "datastore_default" TO "datastore_default";
GRANT USAGE ON SCHEMA public TO "datastore_default";

-- grant access to current tables and views to read-only user
GRANT SELECT ON ALL TABLES IN SCHEMA public TO "datastore_default";

-- grant access to new tables and views by default
ALTER DEFAULT PRIVILEGES FOR USER "ckan_default" IN SCHEMA public
   GRANT SELECT ON TABLES TO "datastore_default";

it's success or fail ?

**Comment by FacundoAcevedo** [comment]
I have some troubles doin this ( using centos). Using ckan user when i run
`paster --plugin=ckan datastore set-permissions postgres -c /etc/ckan/default/development.ini`
It asks me for password, but ckan user hasn't.
So get into virtualenv as root and ran it, and works :D

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
