### ISSUE TITLE
datastore_search_sql with authorization should show private datasets.

### ISSUE THREAD

**Issue by cphsolutionslab** [ckan/ckan#1954]
After discussions on the CKAN mailing list it seems as if there's a common understanding that datastore_search_sql should be able to work with private datasets if correct authorization header is sent along.
Today it's not able to so.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it

**Comment by torfsen** [comment]
On CKAN 2.6.2, I get internal server errors when calling the [`datastore_info`](http://docs.ckan.org/en/latest/maintaining/datastore.html#ckanext.datastore.logic.action.datastore_info) API function on a private dataset. When I [reported](https://lists.okfn.org/pipermail/ckan-dev/2017-June/011010.html) that on the `ckan-dev` mailing list, @mattfullerton [told me](https://lists.okfn.org/pipermail/ckan-dev/2017-June/011011.html) about this issue.

So this issue obviously also affects `datastore_info` (and not just `datastore_search_sql` as noted here and in the docs). Other DataStore API functions might also be affected, but I didn't investigate further.

Irregardless of whether the original issue of accessing private datasets via the DataPusher API by authenticating using an API-key is resolved: even if there is a permission problem then that should trigger the correct error messages instead of an internal server error.
