### ISSUE TITLE
Datastore breaks if there's a row with a single whitespace on a numeric field

### ISSUE THREAD

**Issue by vitorbaptista** [ckan/ckan#1963]
Say that I submit a CSV file with contents:

| value |
| ------- |
| 52     |
| 41     |
| 32     |
| _...thousands of rows..._      |
| 99     |
| _(empty)_ |
| _(whitespace)_ |
| 102   |

The Datapusher will split this file in smaller chunks and submit to the Datastore. Now imagine that the first chunk have just nicely formatted numbers. Seeing this, the Datastore will create a table with a numeric column `value`. All fine. But then, in the next chunks, a row with just a single whitespace `"  "` appears. We'll try to insert that into the Datastore, and it'll fail.

There's no easy way for the user to know what is going on. The error message sent to the user is very cryptic. Even I spent almost one hour trying to figure out what was happening (and could only discover by looking into the machine's logs).

The problem here is that the user data is messy, and we could argue that we shouldn't try to clean it up (because we don't know what he wants to do). But I guess just stripping all strings that come our way isn't going to hurt.

A long time ago there was a similar discussion on OpenSpending. I vagely remember that we decided to strip strings there as well, but I'm not sure. Do you remember it, @tryggvib?

**Comment by Aaron-M** [comment]
Another case where the datapusher fails in a CSV such as below.  The file in question actually has 33581 records, but only some were imported.  The problem seems to be with the 'Animal code' column - the DataPusher interpreted A8301 as a Date/time, rather than a string, and thus created 2 problems - misrepresented the data it did import, and failed to import all the data (probably when it encounterd data that did not conform to the assumed field format). I got around it by putting the "A8301" inside quotes, but that is not ideal.  

Example csv:
TrackID,Study Site,Animal code,NZDT_datetime,Latitude,Longitude,HDOP,Season
1,NC,A8301,21/09/2009 00:56:36,-42.14529,173.51146,1.8,spring
2,NC,A8301,21/09/2009 02:57:35,-42.14553,173.51102,9.1,spring
3,NC,A8301,21/09/2009 04:57:23,-42.14539,173.51086,2.1,spring
4,NC,A8301,21/09/2009 07:56:34,-42.14533,173.51110,1.5,spring

**Comment by amercader** [comment]
We have improved the information on messages on #2145 for 2.3. On next releases we can try and improve the actual handling of wrong data. Bumping the milestone for now.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
