### ISSUE TITLE
Unicode characters in URL box becomes dashes

### ISSUE THREAD

**Issue by mishari** [ckan/ckan#2156]
Hi,

Creating a new dataset, when I enter a URL in a non-latin language the characters just turn into '-' with no warning as to what's going on. Since unicode URL are well supported and especially since CKAN will be used in countries where english literacy is very low, I would like CKAN to support unicode strings in the URL. If that's not possible in this version then in the very least an informative message explaining why the dashes appear would be useful.

**Comment by davidread** [comment]
We chatted about this at the tech meeting and there was concern that this could be a big change, since the ckan code is riddled with handling the name as byte string, rather than unicode as this change would require. We'll need to establish a lot of demand from non-latin languages and find someone to volunteer the necessary work in ckan core.

**Comment by davidread** [comment]
This issue was closed due to inactivity. Feel free to reopen if you have more feedback or are interested it working on it
