### ISSUE TITLE
Organization with the same name as different organizations id links to wrong organization.

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#2183]
If I create organization through the API, give it custom ID, change the name to something else and then create a new organization through the web interface with the same name as the first organizations custom ID, The new organization is linked to the old organization like an alias.

For example:

http://demo.ckan.org/organization/testiorg2

created from the API with id testiorg which can be seen in http://demo.ckan.org/api/3/action/organization_show?id=testiorg

Then created organization with name testiorg http://demo.ckan.org/organization/testiorg but it links to the same organization.

**Comment by rossjones** [comment]
So to clarify, and to ensure I've got this right.

* You call organization_create and pass ID of 123, and a name of 'a'
* You call organization_update and change name from 'a' to 'b'.
* You call organization_create without an ID but with a name of 123.

You end up with one org where 
```
id = 123
name = b
```

and another where
```
id = some-guid
name = 123
```

Suspect we should stop the providing of an id field to organization_create unless there's a really good reason for doing this.  In most cases, we use the name property for accessing organizations (except for a few internal places where we use ids because they don't change - in theory).

**Comment by Zharktas** [comment]
And in this example you can't access the organization with id some-guid, all the web interfaces return organization with id 123.

**Comment by rossjones** [comment]
It's because of https://github.com/ckan/ckan/blob/master/ckan/model/group.py#L141 which looks it up by ID first, and then by name if not found, but that's not the actual issue in this case, it's just a by-product of having an ID that is mirrored in a name.

**Comment by wardi** [comment]
Let's make it a validation error (and a DB constraint) that orgs and groups can't have an id or name that matches any existing id or name. Let's also do the same for datasets.

**Comment by wildcatzita** [comment]
@amercader , is this issue actual?

**Comment by amercader** [comment]
@wildcatzita Yes

**Comment by wildcatzita** [comment]
@amercader , ok. I'll fix it.

**Comment by wildcatzita** [comment]
Made [PR](https://github.com/ckan/ckan/pull/3468) for groups.
@wardi , about DB constraint - I use this code, but it's not work for me

```
def upgrade(migrate_engine):
    # ignore reflection warnings
    with warnings.catch_warnings():
        warnings.simplefilter("ignore", category=sa_exc.SAWarning)
        metadata = MetaData()
        metadata.bind = migrate_engine
        group_table = Table('group', metadata, autoload=True)
        unique_id_name_constraint = UniqueConstraint(
            'id', 'name', table=group_table)
        unique_id_name_constraint.create()
```

**Comment by gleb-rudenko** [comment]
@amercader, any progress with this one?

**Comment by wildcatzita** [comment]
@gleb-rudenko , I still working on it

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
