### ISSUE TITLE
IMigrate

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#2201]
From ideas: https://github.com/ckan/ideas-and-roadmap/issues/114
## User story

As a sysadmin
I want a consistent interface to running migrations for extensions
So that I don't have to manually run sql scripts or hunt through the code for clues.
## Feature

A new plugin for extensions to implement so that when a user runs `db upgrade PLUGIN` the migrations for the newly updated plugin get run.  This could also be used for initial DB setup rather than the current approaches of:
- A paster command, named init, db-init, setup, create etc.
- Checking if the tables exist on every launch of CKAN and creating if not.
## Plan

Create interface IMigrate. When a plugin uses it and is enabled (using ckan.plugins):
- when you run ckan it prints warnings if the extension's model is out of date
- run `paster db upgrade` creates/migrates the extensions' tables as well as core

**Comment by davidread** [comment]
So I've done the basics of this, but not the IMigrate interface yet. I'm parking it for now, as don't have the need for it at the moment. So if anyone else wants to pick it up, please do.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
