### ISSUE TITLE
Problems with requests and https

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#2249]
Because people use self-signed certs, all of the 'requests' calls to ckan tend to fail with SSL certificate validation errors.

We can turn these off by using verify=False in each use of 'requests' but this then means it wouldn't be verifying non self-signed certificates.

Some options:
* See if our version of requests supports REQUESTS_CA_BUNDLE for specifying trusted CAs and document it
* Provide a config option to trust (and set verify=False) specific HTTPs server (using site_url?).

**Comment by amercader** [comment]
> *  See if our version of requests supports REQUESTS_CA_BUNDLE for specifying trusted CAs and document it

We use requests 2.3, it looks like [it does support it](https://github.com/kennethreitz/requests/blob/v2.3.0/requests/sessions.py#L435). Not exactly sure where we would document this. Perhaps along the other SSL related tips, which we still haven't included in the main docs #1773 

>    Provide a config option to trust (and set verify=False) specific HTTPs server (using site_url?).

Having done this myself in other projects I would vote against it because of extra complexity in requests and general ugliness.

**Comment by rossjones** [comment]
I think you're right, REQUESTS_CA_BUNDLE seems like the best approach.
