### ISSUE TITLE
Redirecting after login to the wrong path -> 404 error

### ISSUE THREAD

**Issue by ainslied** [ckan/ckan#2260]
Hello.
My base url for ckan is : http://www.domain.com/ckan/

When an anonymous user goes to a ressource which requires login, he is redirected to the login page :
"http://www.domain.com/ckan/user/login?came_from=http://www.domain.com/ckan/dataset"
But after login, ckan redirects him to "http://www.domain.com/ckan//www.domain.com/ckan/dataset" => 404 error.

Regards,
AD

**Comment by ainslied** [comment]
I tested with http://www.domain.com/ckan/user/login?came_from=/dataset and it works, but this link is not generated automatically..

**Comment by george-sattler** [comment]
Just gave this one a quick test - got the same error when adding a path to virtualhost file i.e.
```WSGIScriptAlias /ckan /etc/ckan/default/apache.wsgi```
I can take a look at this one.

**Comment by george-sattler** [comment]
@amercader double checked my environment - along with the WSGIScriptAlias as per above, I was testing with:
```ckan.site_url = http://localhost/ckan```
... and was able to reproduce the error with Apache

**Comment by amercader** [comment]
thanks @george-sattler I'll have a look

**Comment by amercader** [comment]
Confirmed as well.

@george-sattler, FYI you can test running CKAN on a non-root location using the development server as well (paster), so you don't have to deal with Apache.

On your ini file add this section:

```
[composite:nonroot]
use = egg:Paste#urlmap
/ckan = main
```

And then run paster with:

```
paster serve --reload -n nonroot development.ini
```

CKAN should now be served at http://127.0.0.1:5001/ckan

**Comment by amercader** [comment]
OK, I've pinned this issue to the wonderful [`_add_i18n_to_url`](https://github.com/ckan/ckan/blob/3d9b303206aedb1a6dca770c21f7051dc8db3856/ckan/lib/helpers.py#L198) function.

This patch seems to fix the issue but I confess that I haven't fully understood what's going on:

```diff
diff --git a/ckan/lib/helpers.py b/ckan/lib/helpers.py
index f7123b8..474f22f 100644
--- a/ckan/lib/helpers.py
+++ b/ckan/lib/helpers.py
@@ -250,7 +250,7 @@ def _add_i18n_to_url(url_to_amend, **kw):
             url = '%s/%s%s' % (root, locale, url)
 
     # stop the root being added twice in redirects
-    if no_root:
+    if no_root and not url_to_amend[:4].lower() == 'http':
         url = url_to_amend[len(root):]
         if not default_locale:
             url = '/%s%s' % (locale, url)

```

@george-sattler do you mind having a go and try to see what's going on?

**Comment by george-sattler** [comment]
@amercader sure, I give it a whirl.

**Comment by george-sattler** [comment]
@amercader  I've got something that I think might be a lead although i also confess that I don't fully understand it...
[logged_in](https://github.com/ckan/ckan/blob/master/ckan/controllers/user.py#L369) in the user controller grabs the ```came_from``` param which is a full url e.g. ```http://localhost:5000/ckan/dataset/test-dataset```. It then calls redirect_to() with this full url. My theory is that it's getting mangled (possibly by  _add_i18n_to_url). 
Would I be correct in saying that redirect_to should be used only when you intend to supply things like the controller and action etc... rather than a full url?
If that's the case then would it be easier if the user controller's [logged_in](https://github.com/ckan/ckan/blob/master/ckan/controllers/user.py#L369) method redirected directly to the full url instead of processing that url first?

**Comment by amercader** [comment]
@george-sattler sorry for the late reply, I think you might be right. It definitely makes sense not to pass a full url through `url_for` and co. The only thing I need to double check is if this is required for changing locales, I think there is a redirect involved there.

Also, I'd probably refactor `h.redirect_to` to just redirect straight away full urls rather than have a special case in the controller method.

**Comment by ainslied** [comment]
Thank you, amercader, it works well this way !
_add_i18n_to_url looks confusing to me.

**Comment by MrkGrgsn** [comment]
This may be fixed by #2998

**Comment by krishnaraghavendra** [comment]
I am still having the issue. Is it resolved

**Comment by amercader** [comment]
I lost track of whether this was fixed or if a backport was needed, so I removed the Backport peding label.
If someone is still having this issue in an old version **and** knows of an existing commit that could help I'm happy to reopen it again and mark it for backporting.
