### ISSUE TITLE
Resource view tabs don't render nicely on two lines

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#2264]
@mintcanary what do you think? can we have two (n) rows of tabs?

![wc2acmn](https://cloud.githubusercontent.com/assets/200230/6045101/60f0dbba-ac8f-11e4-805e-7525a68a4fff.png)

**Comment by mintcanary** [comment]
I was thinking something like this http://www.bootply.com/l2ChB4vYmC

**Comment by amercader** [comment]
@mintcanary that sounds great. Will it get automatically focused (and will the tab be visible) if you load a tab which is "hidden"?
Basically if you link to an specific tab, what happens if this is one of the ones not visible by default?
For instance, imagine that there are 10 more tabs before "Cases in Liberia":

http://master.ckan.org/dataset/number-of-ebola-cases-and-deaths-in-affected-countries/resource/79e0e29a-661b-4856-b194-adbb925f8e1c?view_id=5cd1fc51-7ebe-4757-9f9d-b8e8d89aef91

**Comment by mintcanary** [comment]
Good question. My answer would be that it should behave as you describe, but I don't know how/if that can be achieved, personally. Presumably the same issue was present with the old layout. Was it addressed at that time?

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
