### ISSUE TITLE
package_search docs - advanced use

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#2292]
A new page in the docs with lots of helpful examples of package_search

e.g. datasets using a particular vocab

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
