### ISSUE TITLE
Invalidate session after a logout

### ISSUE THREAD

**Issue by metaodi** [ckan/ckan#2294]
Unfortunately the ckan-dev was not able to help me yet, so I'll just raise this issue here.

We have currently a security issue on one of our CKAN instances. I'm
not really the expert, but as far as I understood CKAN uses the
auth_tkt plugin from repoze.who to authenticate a user and create its session.
The auth_tk cookie therefore contains all the session data which is
then used to authenticate a user.

Now if a user logs out this cookie is deleted and the next time he
logs in a new session cookie is created. If now an attacker can copy
the content of the `auth_tk` cookie, then he could still use the session
to access the site. So afaik this means the session is never really
invalidated on the server side. By looking at the code I don't really
understand how it works. There must be some kind of session
information on the server side, right? Shouldn't it be possible to
delete that once a user logs out, so that actually the session is not
valid anymore? Or how does that work?

PS: We're talking here about CKAN 2.2. The auth_tk stuff is here:
https://github.com/ckan/ckan/blob/c260d58387167c660c4981b0305d514693064e20/ckan/lib/auth_tkt.py
and what appears to be the session handling is here:
https://github.com/ckan/ckan/blob/40a4befc7cb68ad621558e6bb2c70621afffc0cd/ckan/lib/base.py#L292

**Comment by brew** [comment]
Hi - I was replying on ckan-dev as you posted here :). See https://lists.okfn.org/pipermail/ckan-dev/2015-February/008684.html

**Comment by metaodi** [comment]
@brew Thanks you so much! Is it possible to invalidate the session on the server side? If so, how?

**Comment by brew** [comment]
I don't think it's possible as it is. I would think adding logic to the `CkanAuthTktCookiePlugin` that stored a unique value from the cookie with a `valid` status in the database would be possible. It would probably need an expiry that tallies with that used for the cookie, so that a scheduled job can remove old sessions.

**Comment by rossjones** [comment]
How about adding something like 

```python
from pylons import session
session.invalidate()
```

somewhere near 

https://github.com/ckan/ckan/blob/775c417700380294b912911800ff8afb16f722bb/ckan/controllers/user.py#L388

**Comment by brew** [comment]
@rossjones I don't think that applies to the repoze.who cookie based auth, but only to the beaker session. However, I think it could be possible to use the beaker session as the identity store, instead of pure cookie-based, using something like https://github.com/kaukas/repoze.who-use_beaker.

I believe many of the security concerns are addressed by making use of the recently exposed settings in the latest version of ckan, due for release soon (2.3):

* Secure flag - this forces the cookie to only be transmitted over https,
and mitigates the man-in-the-middle attack (as demonstrated by firesheep).
If set, an attacker would need physical access to your machine to clone
your auth cookie.
* HttpOnly flag - helps to prevent XSS attacks by preventing DOM access to
cookies
* timeout - if set, this decreases the window of opportunity for an attack
to occur - note this is separate from the expires value on the auth_tkt
cookie itself.

http://docs.ckan.org/en/latest/maintaining/configuration.html#repoze-who-settings 

I do acknowledge this doesn't provide the ability to invalidate sessions server-side, though, and would be interested in seeing a beaker session authenticator plugin that provides that facility.

**Comment by tino097** [comment]
As this looks like a issue targeting really old release, i will close it. 
Please reopen if occurs in newer versions
