### ISSUE TITLE
Handling of views for pre existing data

### ISSUE THREAD

**Issue by Aaron-M** [ckan/ckan#2298]
Pre existing data from previous versions testing is still on the beta site, and when I look at an 'old' record the interface to the data is slightly different compared to when I look at a record I just uplodaded.

In the 'old' dataset (e.g. http://beta.ckan.org/dataset/afghanistan-election-districts/resource/50f6abfc-1ff3-4885-8d8b-ec452605f159), I see a tab for 'Grid View', and beside that a tab for 'Data Explorer'.  The 'Grid view' shows the grid of data as expected.  The 'Data Explorer' then displays Grid | Graph | Map buttons.

In a 'new' dataset (e.g. http://beta.ckan.org/dataset/afghan-spatial/resource/956d6a64-4533-4c74-a50c-e3192aae9986) the separate 'Grid View' tab is not there, just the 'Data Explorer' tab with the 3 buttons.

Is this the expected behaviour?  It's slightly confusing for users to see differing interfaces depending on what version was installed when the data was deposited?  It doesn't appear to offer any additional functionality to have this distinction.

Is there a way to ‘update’ existing datasets during the upgrade process to v2.3. such that this redundant ‘Grid View’ tab is avoided?  

Another thing I noticed is that for an existing dataset (e.g. http://beta.ckan.org/dataset/annual-production-figures-1980-2012/resource/e529b86b-5899-4b5b-9cb9-1cea802b9558) sometimes the ‘Data Explorer’ tab is not displayed (only Grid View) – so you cannot attempt to graph the data, or to place it on a map.  However if I take a copy of that spreadsheet, and reupload a new record, then I get the ‘Data Explorer’ view, with Grid | Graph | Map buttons.
![ckan views1](https://cloud.githubusercontent.com/assets/4842751/6237500/57eea7d0-b758-11e4-9cce-78184c719c41.jpg)
![ckan views2](https://cloud.githubusercontent.com/assets/4842751/6237501/5ac6f746-b758-11e4-868e-fbf2fec40724.jpg)

**Comment by amercader** [comment]
Hi @Aaron-M
Apologies for the confusion, I should have flagged that the resources visualization has changed on 2.3 and point to the relevant docs (I'll email the list with more info):

http://docs.ckan.org/en/latest/maintaining/data-viewer.html

The way resource visualizations (we generally refer to them as "resource views") work, there can be more than one view for each resource, and dataset editors can create them manually on the "Manage" section. Of course creating the views manually is not very convenient, so site admins can define which views they want to [appear by default](http://docs.ckan.org/en/latest/maintaining/data-viewer.html#defining-views-to-appear-by-default) when uploading or linking to a file.

The current default is creating a "Data Explorer" view on CSV and Excel files, that's why you get it on new datasets on beta.ckan.org. In the past this was set to create a "Grid View" by default, that's why some old datasets only have this one available. If they have both it was probably me or some other devs creating them manually to test things.

I have now reset all views on beta.ckan.org and set them to the default ones to avoid more confusion. You can still create new views of different types on resources you have permissions on.

Does that make sense?

**Comment by Aaron-M** [comment]
Thanks for the explanation.

CSV, TSV, XLS, PDF, XML, JSON, and TXT files now seem to work as expected.  

PNG and JPG images also worked.

However HTML, and XSLX do not.

Looking at the XLSX resource, the data has been pushed to the DataStore (as per http://docs.ckan.org/en/latest/maintaining/configuration.html#datapusher-settings) but the associated preview is not being automatically activated.

HTML does not work whether it is the upload of an HTML file, or a link to an external webpage.

For clarification, to automate the preview for text files with different extensions (e.g. .R, .nex, .py) we (continue to) edit the config setting http://docs.ckan.org/en/latest/maintaining/configuration.html#ckan-preview-text-formats - correct?  (But we now also have the flexibility of manually choosing a text preview if the extension/format is not automatically recognised.)
Thanks
Aaron

**Comment by amercader** [comment]
> Looking at the XLSX resource, the data has been pushed to the DataStore (as per http://docs.ckan.org/en/latest/maintaining/configuration.html#datapusher-settings) but the associated preview is not being automatically activated.

This might be an actual bug, if DataPusher supports xlsx then we should probably create the view for it. I'll have a look.

> HTML does not work whether it is the upload of an HTML file, or a link to an external webpage.

The webpage view is not activated on beta.ckan.org, but you can do so on yours adding the `webpage_view` plugin (if you trust the sources)

> For clarification, to automate the preview for text files with different extensions (e.g. .R, .nex, .py) we (continue to) edit the config setting http://docs.ckan.org/en/latest/maintaining/configuration.html#ckan-preview-text-formats - correct? (But we now also have the flexibility of manually choosing a text preview if the extension/format is not automatically recognised.)

Yes, these configuration settings still work as before.

**Comment by amercader** [comment]
Added a patch for the xlsx issue #2303, closing this for now

@Aaron-M let me know if you have any more questions
