### ISSUE TITLE
Not getting offered all view choices to set

### ISSUE THREAD

**Issue by Aaron-M** [ckan/ckan#2308]
Uploaded a resource (text file) which has a non-recognised extension (ttt).  I went in and clicked manage, attempted to set a view manually for it.  However, the choice of views was restricted to:
![views1](https://cloud.githubusercontent.com/assets/4842751/6277674/864e385e-b8f5-11e4-879c-255b506663dd.png)

I uploaded an xlsx file, and similarly went to assign a view (once https://github.com/ckan/ckan/pull/2303 is applied the view should automatically generate on upload). I get all the choices of view:
![views2](https://cloud.githubusercontent.com/assets/4842751/6277736/38e551c8-b8f6-11e4-9bd8-cd64478f4c86.png)

BUT, I then noticed in another xlsx file (which I happen to have uploaded during beta 2.1 under a separate user login) which had not loaded to the Datastore but had the format field specified as xlsx, that the view choices I get offered are only image and website.
![views3](https://cloud.githubusercontent.com/assets/4842751/6277837/fc77bc98-b8f6-11e4-9b19-a2aafb99289c.png)
In contrast a CSV file (also not uploaded to DataStore), includes the 'Data Explorer' as a view option.  I'm picking #2303 will probably fix this for xlsx files, however I wonder if it will be an issue for people not using the Datastore, or if the file had a different extension (e.g. xlsm (a macro enabled xlsx file))?

For the CSV file (or a TSV), arguably a valid choice of view would also be as a text file, but that view is not able to be applied.  For structured data in a text file it would possibly be unusual to want a text view vs a Data Explorer/Grid, but it would technically work, and maybe a 'raw' text view might be useful for quickly scrolling through a lot of records vs the grid, or for a quick copy and paste...? Not sure if has value or not?

**Comment by amercader** [comment]
> Uploaded a resource (text file) which has a non-recognised extension (ttt).

You will need to add any non-standard text formats to the [ckan.preview.text_formats](http://docs.ckan.org/en/latest/maintaining/configuration.html#ckan-preview-text-formats) config option, otherwise CKAN won't know that that's a valid text file eg:

```
ckan.preview.text_formats = text plain text/plain ttt
```
The XLSX issues you mention should be fixed by #2303, which is now merged and deployed to beta.ckan.org. Don't focus to much on old resources as these were created using old logic and they might be unreliable 

> For the CSV file (or a TSV), arguably a valid choice of view would also be as a text file, but that view is not able to be applied

You can still enable text views for CSV if you add them to the `ckan.preview.text_formats` option, but I'd say that in 99% of cases it makes much more sense to browse them as a table.

Closing for now, feel free to reopen if necessary.
