### ISSUE TITLE
Common ini code to fetch additional configuration

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#2323]
I'd like to move some of the code in [_load_schema_module_path](https://github.com/open-data/ckanext-scheming/blob/master/ckanext/scheming/plugins.py#L300-L324) into core ckan so it can be shared across extensions (as a helper possibly). This is a function that resolves configuration files relative to python module names so that an ini can have settings like:

```
licenses_group_url = ckanext.mysitetheme:licenses/licenses.json
```

It first tries to resolve the part of the "url" in front of the colon as a python module path, and if that succeeds it prepends the location of that module to the rest of the path. If it fails then it fetches the file as a normal url with urllib2.

This style follows a similar convention used in our setup.py files for defining plugins. This helper makes it easier to share configurations across computers with virtualenvs installed in different locations.

**Comment by rossjones** [comment]
Is this something you're still interested in doing, I realise it's a bit of an old ticket.  

There are a few things that it would be useful to be able to include from extensions, and I wonder if it might be something that could be done as part of something like https://github.com/ckan/ideas-and-roadmap/issues/113 ?

If you think this isn't really an issue any more, lemme know and I'll close it.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
