### ISSUE TITLE
Error on redirection after creating custom group

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckan#2344]
CKAN 2.3

Error: `GenerationException: url_for can only return a string, got unicode instead: category_read?id=nowa-grupa2`

Because in `controllers/group` (llok for `# !!`):
```python
def _save_new(self, context, group_type=None):
        try:
            data_dict = clean_dict(dict_fns.unflatten(
                tuplize_dict(parse_params(request.params))))
            data_dict['type'] = group_type or 'group'
            context['message'] = data_dict.get('log_message', '')
            data_dict['users'] = [{'name': c.user, 'capacity': 'admin'}]

            # !! data_dict['type'] is in string
            group = self._action('group_create')(context, data_dict) 
            # !! group['type'] is in unicode

            # Redirect to the appropriate _read route for the type of group
            # !! redirect_to doesn't like unicode
            h.redirect_to(group['type'] + '_read', id=group['name'])
```

**Comment by KrzysztofMadejski** [comment]
I have problem when displaying custom group as well beacuse of strict-check in read:
```python
    def read(self, id, limit=20):
        group_type = self._get_group_type(id.split('@')[0])
        if group_type != self.group_type: # does this check is really needed here?
            abort(404, _('Incorrect group type'))
```

Does one has to apart from implementing IGroupForm also override GroupController and mappings to put to that Controller. Shouldn't default GroupController handle all group types?

How do you support custom groups?

**Comment by davidread** [comment]
The GenerationException is probably due to the name of the route not being registered properly in https://github.com/ckan/ckan/blob/master/ckan/lib/plugins.py#L161 . url_for (called by redirect_to) will first try the parameter (u"category_read") as a route name, and I it should be ok casting that unicode to a str string. But since "category_read" has not been registered it assumes that param is actually a URL, and it doesn't like it as unicode.

So check you have enabled your plugin in your ckan.plugins, and also that your plugin is implements IGroupForm and has a group_types method like this:
```
     def group_types(self):
         return ('category',)
```

**Comment by davidread** [comment]
The second issue, with the `group_type != self.group_type` does seem to be a problem with CKAN. 

There seems to be a contradiction - when you have an IGroupForm it registers the routes for it, connecting it up with either the default GroupController or a custom one:
https://github.com/ckan/ckan/blob/master/ckan/lib/plugins.py#L157-L165
yet that default GroupController has the check `group_type != self.group_type` meaning it will 404 if the group_type is not 'group' - so how can it work for any new group_type?

So I think it is necessary for plugins.py to also tell GroupController what group_types it is also used for, so that the check can include those as well.
