### ISSUE TITLE
dashboard_activity_list_html() doesn't pass the user id to activity_list_to_html()

### ISSUE THREAD

**Issue by clementmouchet** [ckan/ckan#2346]
The load more functionality in the dashboard doesn't work, because the `id` that is used to query more data is not passed to the template.

I've fixed it by passing the context user id:

``` diff
diff --git a/ckan/logic/action/get.py b/ckan/logic/action/get.py
index ad59266..2519744 100644
--- a/ckan/logic/action/get.py
+++ b/ckan/logic/action/get.py

@@ -3216,8 +3221,6 @@ def dashboard_activity_list_html(context, data_dict):
     The activity stream is rendered as a snippet of HTML meant to be included
     in an HTML page, i.e. it doesn't have any HTML header or footer.

-    :param id: the id or name of the user
-    :type id: string
     :param offset: where to start getting activity items from
         (optional, default: 0)
     :type offset: int
@@ -3233,6 +3236,7 @@ def dashboard_activity_list_html(context, data_dict):
     model = context['model']
     offset = data_dict.get('offset', 0)
     extra_vars = {
+        'id': model.User.get(context['user']).id,
         'controller': 'user',
         'action': 'dashboard',
         'offset': offset,
```

Will submit a PR asap

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
