### ISSUE TITLE
tag_create doesn't accept vocabulary.name as stated in the doc

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckan#2362]
So I've changed `validators.vocabulary_id_exists` to accept id **or name**

Commit will follow.

Let me know if changing `vocabulary_id_exists` is not the proper way (maybe it is used somewhere as strictly enforcing id but I can't think of reason to do that.

**Comment by wardi** [comment]
@KrzysztofMadejski sounds good to me. It's inconsistent with many other parts of the code to not accept either the id or the name, when unique.

**Comment by kmbn** [comment]
Does this issue still need to be addressed? Since it's been open for over a year, I want to double-check before digging into it.

**Comment by KrzysztofMadejski** [comment]
I guess a PR should follow, but I'm quite involved now in other ckan parts, cannot promise to do it here. I think it may be less hussle if you cherrypick it or copy by hand instead of going through all PR process.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
