### ISSUE TITLE
Dataset modified timestamp gets updated even if nothing was changed in dataset

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#2373]
If user clicks update dataset without actually changing anything, it will update the modified timestamp. This itself is not a big problem, but since it will not update solr index, the timestamps won't match in package_show https://github.com/ckan/ckan/blob/master/ckan/logic/action/get.py#L948

This then triggers package_dictize which won't use custom schemas and before_view for datasets gets extras as key value pairs without the schema. 

For example multilingual gets different dataset_dict and makes ignoring specified attributes difficult.

**Comment by wardi** [comment]
@Zharktas great bug report. So the before_view usually gets the data after validation is applied but not when retrieving it from the db due to a solr date mismatch. That certainly sounds wrong.

In addition to fixing that bug, do you think that the modified timestamp should be updated in solr or not updated in the db when there is no change? I'd lean towards the latter.

**Comment by Zharktas** [comment]
@wardi I think it should not be updated in the db, since it is shown in user interfaces and if nothing in metadata is changed then the timestamp should not claim that it was modified.

**Comment by mostrovoi** [comment]
https://github.com/ckan/ckan/blob/master/ckan/logic/action/get.py#L1061

**Comment by Zharktas** [comment]
I can't reproduce this bug anymore in our environments running ckan 2.3.2, multilingual always get the right data_dict now, so i'm closing this one.

**Comment by Zharktas** [comment]
Reopening this since apparently the problem persists and it surfaced in another ckan project in our company. Relinking the line to something else than master so that it won't disappear due to another commits https://github.com/ckan/ckan/blob/34e1e3f05f52b9ec5b2c2ff79af9822e6d01dd0a/ckan/logic/action/get.py#L1061

**Comment by gleb-rudenko** [comment]
@wardi, is it need to be closed?

**Comment by wardi** [comment]
Likely still an issue. good for contribution

**Comment by gleb-rudenko** [comment]
will take a look at this one

**Comment by gleb-rudenko** [comment]
@wardi, @TkTech, guys the main culprit is the revision avoiding:
```python
    #avoid revisioning by updating directly
    model.Session.query(model.Package).filter_by(id=pkg.id).update(
        {"metadata_modified": datetime.datetime.utcnow()})
```
This part of code doesn't triggers any update event for updating solr index.
What we can actually do about this?
1. we could rewrite this part of code and it will do what we need (update solr index) but it will also start writing activity records for each dataset update even if nothing was changed.
2. try to check for data changes and if nothing was changed, do not update date_modified field at all.

how does that sound?

**Comment by gleb-rudenko** [comment]
@wardi, @TkTech, could you take a look at my PR please? resolving test issues now

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
