### ISSUE TITLE
Newsfeed don't expand - wrong link for ajax call

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckan#2386]
http://localhost:5000/pl/dashboard

`id` is not passed by `action.get.dashboard_activity_list_html` and wrong controller..

**Comment by joetsoi** [comment]
thanks for this, you're submitting a pull request for this (I hope? :p)

**Comment by KrzysztofMadejski** [comment]
I don't have a separate branch for this. You need to cherry-pick or even copy-paste (I've changed just two lines)

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
