### ISSUE TITLE
Perform_reset doesn't work

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckan#2395]
For users that have id != name.

Because of:
https://github.com/ckan/ckan/blob/master/ckan/lib/mailer.py#L139

``` python
def get_reset_link(user):
    return urljoin(g.site_url,
                   h.url_for(controller='user',
                           action='perform_reset',
                           id=user.id,
```

https://github.com/ckan/ckan/blob/master/ckan/controllers/user.py#L468

``` python
    def perform_reset(self, id):
        context = {'model': model, 'session': model.Session,
                   'user': id,
```

https://github.com/ckan/ckan/blob/master/ckan/logic/__init__.py#L285

``` python
                    context['auth_user_obj'] = \
                        model.User.by_name(context['user'])
```

To my best guessing context['user'] should always be a user name, not id.

**Comment by nateprewitt** [comment]
From what I can tell, perform_reset does in fact work, but only because there is some weird initialization of the "user" value in [controllers/user.py](https://github.com/ckan/ckan/blob/master/ckan/controllers/user.py#L40).

The id value for this specific context is set to the user.name value rather than user.id, when they are logged in. This is then passed to the logic/__init__.py check_access call. So we do actually get the desired result, but through some odd semantics. 

id is also used for both id and name in the user_show call you've modified, so perhaps changing the call in [logic/init.py](https://github.com/ckan/ckan/blob/master/ckan/logic/__init__.py#L285) to .get(context['user']) instead of .by_name() would be adherent to the existing pattern in /actions?

The only issue I can see with changing id to username is a username can be changed while an id should be static. An open reset link will be invalidated on name change, while the reset link with id would persist.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
