### ISSUE TITLE
url manipulation helpers remove the resource ID

### ISSUE THREAD

**Issue by njall** [ckan/ckan#2430]
Whenever I use the helpers h.add_url_param or h.remove_url_param on a page where the id of a resource is embedded in the URL, it seems to remove the id.

So for example, if I was on /dataset/new_resource/resource_id_here
and did 

{{ h.add_url_param(new_params={'key_name': 'variable_name'}) }}

I get this error:

There is a broken url being created {'action': u'new_resource', 'controller': u'package'}

Because it is not preserving the id 'resource_id_here'.

Is this a bug?

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
