### ISSUE TITLE
Organization template read_base is missing parameter "offset"

### ISSUE THREAD

**Issue by florianm** [ckan/ckan#2466]
Ubuntnu 14.04, source install, just merged my branch (up to date with master as of April 20, 2015) with latest master as of now (commit 97ab43f46e38fd9af0e437c9b051e38962a79b81).

Organisation detail pages raise a 500 error with 
```
[Tue Jun 16 11:39:13.957831 2015] [:error] [pid 25059] [remote 10.6.20.100:31236] File '/mnt/ckan/default/lib/python2.7/site-packages/ckan-2.4a-py2.7.egg/ckan/templates/organization/read_base.html', line 18 in blo
ck "content_primary_nav"
[Tue Jun 16 11:39:13.957835 2015] [:error] [pid 25059] [remote 10.6.20.100:31236]   {{ h.build_nav_icon('organization_activity', _('Activity Stream'), id=c.group_dict.name) }}
[Tue Jun 16 11:39:13.957837 2015] [:error] [pid 25059] [remote 10.6.20.100:31236] File '/mnt/ckan/default/lib/python2.7/site-packages/ckan-2.4a-py2.7.egg/ckan/lib/helpers.py', line 524 in build_nav_icon
[Tue Jun 16 11:39:13.957840 2015] [:error] [pid 25059] [remote 10.6.20.100:31236]   return _make_menu_item(menu_item, title, **kw)
[Tue Jun 16 11:39:13.957843 2015] [:error] [pid 25059] [remote 10.6.20.100:31236] File '/mnt/ckan/default/lib/python2.7/site-packages/ckan-2.4a-py2.7.egg/ckan/lib/helpers.py', line 587 in _make_menu_item
[Tue Jun 16 11:39:13.957846 2015] [:error] [pid 25059] [remote 10.6.20.100:31236]   % (menu_item, need))
[Tue Jun 16 11:39:13.957849 2015] [:error] [pid 25059] [remote 10.6.20.100:31236] Exception: menu item `organization_activity` need parameter `offset`

```

Adding a parameter "offset=0" to the template [organisation/read_base](https://github.com/ckan/ckan/blob/master/ckan/templates/organization/read_base.html#L18) and an obvious `python setup.py install`fixes this problem.

A [summary of my commits on my branch](https://github.com/ckan/ckan/compare/master...florianm:master) only shows one "offset" - the one I've patched in on my side.

Not seeing an existing bug report or mailing list discussion about this problem indicates that the problem lies on my end.

Unless anyone could help me shed light on this, I'll have a look at the blame views of each file involved in the error stack trace to look for new commits which could have introduced this problem at least on my end. 

Any pointers would be appreciated!

**Comment by hkotkanen** [comment]
I've run into the same problem and in my case it's caused by enabling the [ckanext-hierarchy](https://github.com/datagovuk/ckanext-hierarchy/) plugin, but I'm not yet sure if the cause is that particular plugin or some issue with how IGroupForm plugins are registered (maybe with an unfortunate name clash or something?). I'm thinking it could be [this line (lib/plugins#L190)](https://github.com/ckan/ckan/blob/master/ckan/lib/plugins.py#L190) that causes the "organization_activity" to need the offset-parameter, by registering a plugin with a group_type of "organization".

The only other mention of this problem that I've seen is this relatively fresh issue in the hierarchy plugin repo: [#9](https://github.com/datagovuk/ckanext-hierarchy/issues/9).

@florianm Do you have any plugins activated or does this problem occur for you on a vanilla instance?

Also, I hope no one takes offence to pinging the participants of the other, identical issue: @davidread @datracka

**Comment by florianm** [comment]
@hkotkanen actually hierarchy and a few [others](http://govhack2015.readthedocs.org/en/latest/3_CKAN/#supported-extensions) are installed on my end!

**Comment by datracka** [comment]
The same for me, installed ckanext-hierarchy in a vanilla instance and I ran in this issue.

**Comment by florianm** [comment]
Plus, both ckanext-hierarchy and ckanext-scheming instantiate the iGroupForm, so with hierarchy enabled, custom org/group templates from scheming can't be enabled. See open-data/ckanext-scheming#91

I've hacked around this conflict by 
* [providing](https://github.com/datawagovau/ckanext-datawagovautheme/blob/master/ckanext/datawagovautheme/templates/organization/read_base.html#L18) the `offset=0` parameter in my catch-all/theming extension, 
* enabling hierarchy, and 
* not using custom org schemas, but using the three extra org fields.

**Comment by brew** [comment]
I think this issue with the offset was fixed by https://github.com/ckan/ckan/pull/2640. I ran into it when working on organization support for ckanext-scheming: https://github.com/open-data/ckanext-scheming/pull/84

**Comment by florianm** [comment]
Thanks @brew, that resolved this issue methinks!
