### ISSUE TITLE
Datastore / Recline view: No view created for datastore resource 

### ISSUE THREAD

**Issue by mvi-eea-sk** [ckan/ckan#2473]
If `/api/action/datastore_create` is called for already created resource, the recline view is not generated automatically.

There are two bugs, that i discovered:
- recline view bug

here: https://github.com/ckan/ckan/blob/ckan-2.3/ckanext/reclineview/plugin.py#L90
and probably here too: https://github.com/ckan/ckan/blob/ckan-2.3/ckanext/reclineview/plugin.py#L62
the datastore_active parameter always returns None for some reason even if i call `/api/action/resource_update` on already created datastore resource.
So it depends on the second parameter 'url' to be set to '_datastore_only_resource' to generate the view.
- datastore bug

if calling `/api/action/datastore_create` with resource parameter, thanks to this: https://github.com/ckan/ckan/blob/ckan-2.3/ckanext/datastore/logic/action.py#L93 the url is set to '_datastore_only_resource' and view for this resource is generated
But when it's called with resource_id parameter (resource already exist, we only change it to datastore resource) the url parameter isn't changed to this string and no view is generated by recline plugin

I am sure this problem was not present 2.2.2 ckan, only in 2.3 it appeared.

**Comment by mattfullerton** [comment]
Can't we find a way of not being dependent on this cryptic url=_datastore_only_resource? There is the field datastore_active that ought to be enough, as @mvi-eea-sk says. Hence, I think the real bug here is the second issue, that datastore_active is not getting set.

@mvi-eea-sk: Can you try adding this inside the try block (at line 140) after the table creation step:
data_dict['resource'].set('datastore_active', True)

and see if that fixes the problem? If so I can make a pull request. Maybe someone with inside developer info knows why the problem might have appeared from 2.2 to 2.3 and/or why the condition with the URL text is in there. Perhaps I'm missing something.

**Comment by mvi-eea-sk** [comment]
@mattfullerton 
datastore_active parameter isn't persisted so setting it is pointless
and in the case of providing resource_id instead of resource, this will cause internal error

datastore_active parameter is set here https://github.com/ckan/ckan/blob/ckan-2.3/ckanext/datastore/plugin.py#L278-L287
thanks to implementing IResourceController interface in the before_show method, this parameter is set only before returning result of action resource_show
