### ISSUE TITLE
Licences should have version numbers and direct URLs

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#2478]
Our default licenses are 'underspecified' e.g. "Creative Commons Attribution" should have a version number because there are small differences between the versions and we don't want to create doubt.

In addition, the URL attached should be to CC itself, rather than http://www.opendefinition.org/licenses/cc-by which again misses the version number and is not as widely used as the official URI: https://creativecommons.org/licenses/by/4.0/

There has been some criticism of CKAN for this. In a review of metadata on catalogs worldwide, Open North said:

> A significant problem is the quality of licensing metadata. In 8 out of 24 catalogs, the licenses of over 10% of datasets are either not specified or underspecified. The choice of catalog software affects the quality of licensing metadata. CKAN offers several “generic” licenses, which are not licenses at all, such as “Other (Attribution)” or “License not specified.” It also offers Creative Commons licenses without specifying version numbers, which are necessary to identify the licenses; we supplemented the licenses with version numbers where possible. Catalogs should avoid using the default CKAN licenses as almost all are underspecified.
> 
> https://docs.google.com/document/d/1OMgK4e0KXkuQwJRS0viEsAqlGFoETDJffG9WQ_ONqdw/edit?pli=1#

**Comment by davidread** [comment]
This relates to issue raised here: https://github.com/ckan/ideas-and-roadmap/issues/153

**Comment by davidread** [comment]
To make this clear, I'm proposing hiding the default licences that are underspecified and adding better new ones. Those that use a custom list anyway won't be affected.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
