### ISSUE TITLE
Displaying 'Download' or 'Go to Resource'

### ISSUE THREAD

**Issue by mattfullerton** [ckan/ckan#2480]
Looking around on master.ckan.org and at the code, there are a few weird things going on here:
- If people are still using resource previews (and not the new views), the resource listing does not pick this up and shows 'Go to Resource' which is against the intended logic (https://github.com/ckan/ckan/blob/master/ckan/templates/package/snippets/resource_item.html#L43). This is probably not so tragic as I assume resource views will be jetisoned at some point. For example, the resource http://master.ckan.org/dataset/world-countries/resource/b95ab900-a7c1-4d86-9846-221f8d911a67 shows with go to resource in the list view even though there is a preview when clicking on it. But its the old ckanext-spatial resource preview, so I assume that's why has_views is failing?
- Once looking at a resource [preview], the check for views (to decide whether to show download or go to resource) seems to be failing, I presume on the ... part:
  https://github.com/ckan/ckan/blob/master/ckan/templates/package/resource_read.html#L40
  Is the can_be_previewed attribute perhaps not getting set correctly? For example, the resource http://master.ckan.org/dataset/world-countries/resource/fbafc4a6-03eb-46dc-8e63-eba42165b136 shows with download in the list view and go to resource when actually viewing the resource.

Personally, I could live without all these checks and be happy with 'Get Resource' for all cases

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
