### ISSUE TITLE
Arabic translation format string issue

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#2493]
There is a problem with the arabic translation:

```
(ckan)vagrant@precise64:/vagrant/src/ckan$ tx pull -f -r ckan.2-3 -l ar
(ckan)vagrant@precise64:/vagrant/src/ckan$ paster check-po-files ckan/i18n/*/LC_MESSAGES/ckan.po
Checking file ckan/i18n/ar/LC_MESSAGES/ckan.po
    Format specifiers don't match:
    Please <a href="{link}">update your profile</a> and add your email address and your full name. {site} uses your email address if you need to reset your password. ->   <"{a href="{link>    <a/>         . {site}
```

In Transifex I can toggle the "RTL" (right-to-left) button and it goes right/wrong, but I'm not sure if it is correct or wrong. I don't support you could take a look @amercader ?

**Comment by davidread** [comment]
Adria says we can fix this by changing the way we specify the params in the string.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
