### ISSUE TITLE
Allow homepage layout options to be defined from theme

### ISSUE THREAD

**Issue by smth** [ckan/ckan#2540]
A CKAN theme may not support all or any of the three layouts as they are described in `/ckan-admin/config`. It would be nice to have an easy way to define these, or hide this option, when creating a theme.

**Comment by amercader** [comment]
@mintcanary You are right. I'm afraid there isn't an easy way right now to register layouts to a particular theme. In fact, the choosing of layouts does not mix very well with the assumed approach for building custom themes by overriding templates and CSS. Do you have something in mind to accomplish what you propose?

In any case, we can hide the field from the `/ckan-admin/config` form overriding it from the extension and removing it.

**Comment by mintcanary** [comment]
Nothing in mind, technically. I'm imagining a theme config file, i.e a config which is associated with the theme, rather than the site. That said, on this issue, I think just removing the field is probably good enough.

**Comment by florianm** [comment]
If all elements of the home page (introduction, stats, featured, featured organisation / group) could have an ID, a custom theme can define visibility via CSS, and the placement options could be solved by adding a few more permutations in the admin GUI.

I've struggled to replace the grey area behind featured organisation and group as I couldn't figure out its xpath.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
