### ISSUE TITLE
Widget.recordCount.js doesn't handle singularity. Wrong label "records"

### ISSUE THREAD

**Issue by benjaminlaot** [ckan/ckan#2551]
It doesn't handle the result's singularity.

Ex : 1200 records  -> OK
        1records -> KO

![capture](https://cloud.githubusercontent.com/assets/9968236/8822869/bcc6023c-3068-11e5-9a06-475d5525f845.PNG)

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
