### ISSUE TITLE
datastore_search should use a 'read-only' postgres user

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#2564]
Currently the datastore's search uses the 'write_url' postgres user, rather than the 'read_url' so that its search can include private datasets. However that gives it more power than is needed - it is the only one to use a write user of all the actions available withing the appropriate authentication. It seems safer to use:
- for searching public datasets use the 'read-only' user
- for searching private datasets use a new postgres user that can only read, but can access private datasets too

**Comment by davidread** [comment]
So we don't need a third user once #2562 is done

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
