### ISSUE TITLE
DataStore should not deliberately maintain uppercase of field names

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#2577]
Originally submitted by @timwis on ckan/datapusher#78

It's the DataStore the one that takes care of creating/updating fields, so moving here
## 

I've noticed that if you upload a dataset with uppercase field names (which is almost always the case when pulling data from Esri/Arc databases), they get added to the postgres database with uppercase names. By default, postgres converts all field names to lowercase unless you explicitly double quote the field names. If you _do_ double quote them, then you _always_ need to use double quotes to interact with them.

As a result, you cannot query or use the DataStore API as the documentation suggests:

`?sql=SELECT * from "2c0d8231-e6b8-4598-8089-d1bcaf1bdaa6" WHERE ZIP_CODE = '19146'` ([example](https://www.opendataphilly.org/api/action/datastore_search_sql?sql=SELECT%20*%20from%20%222c0d8231-e6b8-4598-8089-d1bcaf1bdaa6%22%20WHERE%20ZIP_CODE%20=%20%2719146%27))
will fail with the error `column "zip_code" does not exist` (note the error includes a lowercase field name - postgres converts field names to lowercase unless they're double quoted)

You must wrap the field name in double quotes to query it, ie.
`?sql=SELECT * from "2c0d8231-e6b8-4598-8089-d1bcaf1bdaa6" WHERE "ZIP_CODE" = '19146'` ([example](https://www.opendataphilly.org/api/action/datastore_search_sql?sql=SELECT%20*%20from%20%222c0d8231-e6b8-4598-8089-d1bcaf1bdaa6%22%20WHERE%20%22ZIP_CODE%22%20=%20%2719146%27))

My hypothesis is that somewhere in the DataPusher extension, field names are being wrapped in double quotes, and my proposal is that they not be wrapped in double quotes. If there's some other reason they need to be (ie. to support special characters) then the field names should be converted to lowercase first to provide the expected functionality. Thoughts?

**Comment by amercader** [comment]
@timwis I can see your point about the double quotes, but that's the way Postgres works, in the Postgres client you'll also have to wrap a query like `WHERE "ZIP_CODE" = '12324'`. 
Another question is enforcing lower case on all keys for data sent to the DataStore to avoid this. The change in itself can seem pretty straight-forward but you also need to take into account stuff like spaces in field names, etc.

Also we are in a sense changing the original data, I'd expect someone wondering at some point why the field names are not capitalized like in the original CSV, Excel, ESRI GDB (eg [here](https://www.opendataphilly.org/dataset/parking-meters-kiosk-inventory/resource/33e8a289-c31a-4ce3-9ac1-4bd3319fe150)).

My main worry however is breaking existing applications that rely on queries containing quoted fields. Not sure how we could get around this.

**Comment by amercader** [comment]
Worth checking https://github.com/CartoDB/CartoDB-SQL-API/issues/196

**Comment by timwis** [comment]
@amercader thanks for the reply, and great points. Regarding the dataset you linked, here's how Socrata handles it: The [dataset](https://data.phila.gov/Transportation/Parking-Meter-Inventory/84k6-nu6e) lets you name the fields as you wish, spaces, capitals, etc. and when you download it it maintains that format. The [API](http://dev.socrata.com/foundry/#/data.phila.gov/84k6-nu6e), however, automatically converts field names to lowercase and replaces non-alphanumeric characters with underscores in order to make the API more usable as an API. Technically this is done when you upload the dataset and you can override it / change the "api key" of each field.

Does the "download" function pull from the DataStore? If so, I can see why you'd be concerned about maintaining the field names. Otherwise, I'd point out that Postgres converts field names to lowercase by default, unless you *explicitly* double quote them (so it almost seems like they made the choice for you :P).

I guess the ideal answer here would be a way to make case-insensitive queries in Postgres, but I'm not familiar enough with Postgres to say whether that's remotely possible or not.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
