### ISSUE TITLE
Empty date fields  in datapackage cause error when pushed via dpm

### ISSUE THREAD

**Issue by wingmanzz** [ckan/ckan#2588]
using this spec for the date
..
 {
            "type": "date", 
            "name": "start_actual_isodate"
          }, 
..
if i use this data

project_id, start_date,status
"1111",,"closed"

dpm ERR! CKANJS API Error. HTTP code 500. Message: "\n    <html>\n    <head>\n    <title>Server Error</title>\n    \n    </head>\n    <body>\n    <h1>Server Error</h1>\n    An internal server error occurred\n    \n    </body>\n    </html>"
CKANJS API Error. HTTP code 500. Message: "\n    <html>\n    <head>\n    <title>Server Error</title>\n    \n    </head>\n    <body>\n    <h1>Server Error</h1>\n    An internal server error occurred\n    \n    </body>\n    </html>"

when pushing via dpm

server logs say

Error - <class 'ckanext.datastore.db.InvalidDataError'>: The data was invalid (for example: a numeric value is out of range or was inserted into a text field).

If I replace the blank field data field, with a real date it works fine. 

project_id, start_date,status
"1111",2009-01-01,"closed"

Am I just missing a config option? Is there a nullable option to be set somewhere for date fields?

**Comment by wingmanzz** [comment]
one more update:

looking at the postgres logs, ckan tries to insert an empty string, instead of a null and returrns the following error

EDT ERROR:  invalid input syntax for type date: "" at character 355

**Comment by raymedia** [comment]
Hi guys,
Any updates or workaround for this issue? I'm having similar issue with my resources. Thanks in advance.

Cheers,
Ray

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
