### ISSUE TITLE
recline_graph_view not the same as Graph pane of recline_view as stated in documentation; non-numeric columns not available for axes.

### ISSUE THREAD

**Issue by ecraigo** [ckan/ckan#2591]
Hi there,

I'm using a CKAN 2.3 package install on a Ubuntu 12.04 server and am trying to create views to hopefully be embedded in iframes in a CMS. I wish to create a bar graph in which the group axis is a list of building names and the series axis is numeric. I can do this in the "graph" pane of the regular Data Explorer (recline_view), but when I try to set axes in "recline_graph_view", because I want to not have to make end-users generate their own graphs, non-numeric columns are not available to me.

It doesn't make a whole lot of sense to me to have bar graphs without the possibility of a non-numeric group axis, because that seems to me to be the point of bar graphs.

I did not see this in the changelogs between 2.3 and later versions, so I assume that it's still relevant. I apologize if I am in error. Thanks!

**Comment by mattfullerton** [comment]
This is set here: https://github.com/ckan/ckan/blob/master/ckanext/reclineview/plugin.py#L129

And the problem is its fixed for all kinds of charts, where most of them only make sense for numeric/interval data. But personally I would be OK with having it relaxed, I don't think the computer will explode if you throw text data at a line graph for example, and we could trust users to know what makes sense and what not, especially given that it's usually admins/curators who are setting up these views (as opposed to data explorer where anyone can play with it).

What do others think? (It's not my decision to make!)

**Comment by themgt** [comment]
We are having this problem as well - we can generate the sort of graph we're looking for in the graph portion of the recline_view plugin, but this view seemingly then can't be saved? And then with the recline_graph plugin, the view can be saved but we can't customize the graph with more than a single series?

Very confusing/unintuitive and problematic from an end-user standpoint.

**Comment by mattfullerton** [comment]
Yup. I don't know if it's worth pointing out that the two types of view (data explorer and graph) are technically separate, but they are based on the same stuff in the background. But from a user perspective that's irrelevant. It doesn't help much, but I have it relaxed on our CKAN:

![ckangraph](https://cloud.githubusercontent.com/assets/4084428/10992798/e46aec58-8469-11e5-8f5c-2e0bae39897d.png)

As you can see it might even make sense to draw a line between categories. Unfortunately though I have to preview twice before the parameters are accepted, so I don't want to submit a PR just yet, and there's been no response to my question above about whether the developers agree.

I also started (and didn't finish, sorry :disappointed:) a 'create from data explorer' function, because indeed the two views are very similar.

If you just want to plot nice line graphs, you could try out this extension: https://github.com/ckan/ckanext-basiccharts - it is a bit more powerful.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
