### ISSUE TITLE
Upgrade to Bootstrap 3

### ISSUE THREAD

**Issue by LaurentGoderre** [ckan/ckan#2602]
I have quite a bit of experience with Bootstrap and found out that ckan is using version 2.3 which is quite old. Would you guys be open if I opened a PR for this change? I would also like to make refactor the templating engine to make it a bit more consistent and easier to override.

I also am a web accessibility expert and would like to implement to some accessibility and HTML5 improvements.

Let me know what you guys think.

**Comment by djfurman** [comment]
:+1:

If there is interest here, please reach out to me, I'd be happy to collaborate on the effort

**Comment by LaurentGoderre** [comment]
:+1:

**Comment by amercader** [comment]
There is definitely interest! This has been proposed in the past (#1271, #1849, #1993) but never got round being done.

The main issue is apart from being a big job that needs to be carried all the way through, is having some sort of compatibility with existing extensions implementing a theme based on Bootstrap 2. I'm not super familiar with how the frontend stuff is structured but I know that the current assets are aggregated under the [`base`](https://github.com/ckan/ckan/tree/master/ckan/public/base) folder so perhaps we can implement a kind of basic "theme" support that allows us to keep old assets for compatibility.

@mintcanary would love your views on this.

As for the templates, again there's a balance between improvement and breaking existing things but we can totally discuss it. I think @wardi had ideas on this, specially on the dataset / form ones.

Thanks both for your interest!

**Comment by LaurentGoderre** [comment]
I thought one of the first step if we do this is to look at how assets are being organized. I opened #2601 for this.

**Comment by LaurentGoderre** [comment]
Also, we are in the opposite boat right now, our layout is in Bootstrap 3 so we have to maintain overrides to make ckan support Bootstrap 3 and it's really not all that complicated. The grids shystem changed (for the best) but it should not be hard for these extension to upgrade to 3.

**Comment by mintcanary** [comment]
I would love to see an upgrade. I would love even more for an upgrade to v4 (which sounds like it is going to be another significant improvement), but that's only in Alpha at the moment.

Yes, there is a potential problem with existing themes, where core has used Bootstrap classes (which may be different in different versions). Themes may be targeting these same classes in their CSS and/or adding more of them to their templates. Ideally, CKAN shouldn't be using any Bootstrap classes (but it does).

Looking forward a bit, I would like to see Bootstrap (assuming CKAN continues to use it) removed from core and into an extension, leaving just simple, semantic markup in core. Then in future this type of change would be a matter of removing one extension and adding a new one.

**Comment by LaurentGoderre** [comment]
I like that idea but that means better HTML structure and lot more configurable Jinja templates, so major breaking changes no matter which way we go.

**Comment by wardi** [comment]
@mintcanary sounds like a great idea. Our core templates would be so much nicer if their classes were just about ckan and not $framework_du_jour

**Comment by LaurentGoderre** [comment]
With that being said, from what I read about Bootstrap 4, at least the layout portion of it, is practically identical from Bootstrap 3. The fancy content stuff may change but the layout ones shouldn't which is a pretty big win!

**Comment by florianm** [comment]
So would that mean a general review/clean-up of templating and maybe [requirements](http://rshiny.yes-we-ckan.org/ckan-pip-collisions/) of extensions?

**Comment by mintcanary** [comment]
I guess if you wanted a more quick and dirty solution, you could address differences in classes, without rewriting templates, by adopting the (BS2) ones CKAN is using as 'CKAN classes' then extend current BS (or whatever framework) into them. So you'd document somewhere that, for example, `.span6` is a standard CKAN class, then in the CKAN LESS you'd have something like `.span6 { &:extend(.make-sm-column(6));}` or whatever. I'd much rather go the semantic route, but this sort of feels like a step in the right direction. (admittedly it's Friday afternoon, and I haven't given this a great deal of thought)

**Comment by davidread** [comment]
Tech team says:

* Yes please!!
* Do the upgrade on a long-term branch though
* Ee can assess how much impact this has on other peoples' extensions and decide when to merge - maybe for next version or at most a year. It might need to be called ckan 3.0 because of the backward-incompatibleness.
* If necessary we can switch core to bootstrap 3 and put bootstrap 2 stuff into an extension to help the transition.

**Comment by amercader** [comment]
Also, look into how feasible it its to have the current (2.x) assets and templates available on an extension that overrides the ones on core so people can use it to transition.

@LaurentGoderre it would be super useful to have a general idea of what changes are needed to make this happen at the templates level. Is it just changing CSS classes or also changing markup and moving blocks around?

@mintcanary if we target this for CKAN 3.0 and hopefully provide some kind of upgrade path then we can be more ambitious and do things properly :)

**Comment by LaurentGoderre** [comment]
I'm sure there are ways to implement in in a manner that would not affect the templates that much but it would likely feel like patchwork and would be difficult to maintain. I would personally prefer to do this as a CKAN 3 and be more ambitious. We could do a more thorough clean up. I would like to look at the blocks and how to make them consistent across CKAN. We could also look into a more semantic HTML.

**Comment by davidread** [comment]
Clearly the more breaking changes go in, the more things to adapt in the scores of custom extensions around the world. Moving to BS3 makes a lot of sense because that's what front-end devs are most comfortable with now and compatibility with other front-end stuff like WET. However rejigging the blocks needs strong justification for changes. Even if it is called CKAN 3. We need to take the community with us or we lose it. I'm not saying don't do it, but we should agree the key changes are worth it, such as when @wardi refactored the dataset edit form blocks from about 12 templates to about 5.

**Comment by wardi** [comment]
@davidread that reminds me I should rip out the backwards-compat nastiness I introduced with those changes (and I think I only removed 2 or 3 templates, there's lots more to do there)

**Comment by LaurentGoderre** [comment]
I agree, however while implementing WET for ckan, I am running into a lot of inconsistencies and those are the ones I want to fix. It would also be nice if theming would not require so much overrides.

**Comment by davidread** [comment]
I feel your pain - it totally annoying to have to make compromises to
ensure maximum backwards-compatibility for the common good of the CKAN
community. It's similar to supporting old IE versions - what a pain. If you
can think of ways around this then we're all ears.

Maybe you can find sneaky ways to improve things whilst keeping backward
compatibility, like dividing existing stuff in blocks, or adding empty
blocks that you can use to insert things. Just make sure to put these
things into PR(s) separate from the BS3 branch, so they can go into master
as we go along.

**Comment by LaurentGoderre** [comment]
Sounds good! #2611 is a push in that direction (a very small one granted)

**Comment by i-tu** [comment]
Hi, I have done a conversion to Bootstrap 3 in a [specific instance of CKAN](http://liityntakatalogi.suomi.fi/) ([repo here](https://github.com/vrk-kpa/api-catalog)). There's a lot of issues I've worked through in order to make layouts work properly and responsively, though please note this is a solo effort over a short period of time so there are bound to be snags.

The theme overwrites a large amount of templates, often just in order to change a class. This is obviously not too great for maintainability. It would be in my projects best interest to make a Bootstrap 3 fork of CKAN, which would ultimately be merged into mainstream CKAN (v.3?)

Is there interest in creating a BS3 fork in order to pool efforts on this front?

**Comment by rossjones** [comment]
This was discussed on the dev call today, and I think the general consensus is that we would all be extremely happy to see a PR that moved CKAN over to Bootstrap 3.  

As CKAN 2.5 is imminent, it might be best to base this work on that, with an aim of getting the move in for a later release, although we will still need to quantify the impact on 3rd party extension themes. If this does end up being CKAN 3, then perhaps there is also some room for reworking the templates to make them easier to work with?

@i-tu @LaurentGoderre  Is this something you might both consider collaborating on?  It seems like a lot of work to have one person do alone.

**Comment by LaurentGoderre** [comment]
Absolutely. Our front-end is Bootstrap 3 so havingt CKan on Bootstrap would greatly simplify our codebase

**Comment by LaurentGoderre** [comment]
Here is a little status upadate on the work. Still lots to do!

![ckan_bs3](https://cloud.githubusercontent.com/assets/1090826/12304145/14a6436e-b9fc-11e5-9289-72fde36a38b8.PNG)

**Comment by rossjones** [comment]
Awesome.  Are you managing to get this done within the current controller/templates or does it have deeper changes?

**Comment by LaurentGoderre** [comment]
Well...I thought I would start fresh, without the limitation of existing code (this is static). I had to fix some of the HTML5 markup etc. Once that's done, I can assess how much of the controller/template has to change. I do think that some of it will need to change

**Comment by rossjones** [comment]
That's fair enough I suppose :) Thanks for the update - looks great.

**Comment by LaurentGoderre** [comment]
Here's another update: http://laurentgoderre.github.io/ckan-bootstrap-static/dataset.html

**Comment by davidread** [comment]
Looking good :+1:

**Comment by LaurentGoderre** [comment]
Thanks! Glad you like it!

**Comment by torfsen** [comment]
Awesome that you're working on this!

If you're going to change the template structure (i.e. the Jinja blocks) then please let's take that chance and make things a bit more organized. Currently it's quite exhausting to create a theme because a lot of things that look similar in the rendered output are done rather differently on the template level. The same goes for the texts. For example,  there are both `Last Updated` and `Last updated` (upper vs. lower case) as translatable strings, and in the German translation they ended up with different translations. So more consistency would be very nice to have.

**Comment by amercader** [comment]
Done in the PRs above
