### ISSUE TITLE
API Key for External data

### ISSUE THREAD

**Issue by codemonkeyneo** [ckan/ckan#2648]
Hopefully someone can point me in the right direction and help with my query.

I wish to add a few shared resources into a CKAN implementation. The only thing is that to use the resources you will still need to register for an API Key. Is it possible that CKAN can pass on the api key sent in either header/url onto the other resource ?

Hope that makes sense,

Cheers

Neil

**Comment by codemonkeyneo** [comment]
I have looked more into the CKAN structure and it looks like I have to either find an extension or write my own to do this, I will investigate further.

**Comment by mattfullerton** [comment]
There was a similar request on the global list:
https://groups.google.com/forum/#!msg/ckan-global-user-group/JnCT6Afg-24/w50N33b3DAAJ

I would be interested in helping to develop this, as I stated there I only got as far as adding a "web service" button on the add resource page until now.

**Comment by wardi** [comment]
This seems like a hard problem. is your plan to proxy the API through CKAN?

**Comment by mattfullerton** [comment]
If its an external resource, it will be going through the resource proxy anyway in order to be of any use for downloading/views etc. I see no reason why an extended resource proxy couldn't take along a few other fields (like header name, header value, or post type and post body value) and use them if they are set? But I haven't thought it fully through or tried to implement it :relaxed:

**Comment by wardi** [comment]
Sounds reasonable to me! All I can think of are potential problems with some trickier uses of HTTP (resuming downloads, chunked uploads, etc.) and potential for tying up resources if the client is slow. These shouldn't be major problems.
