### ISSUE TITLE
resource extras stripped by package controller

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#2649]
https://github.com/ckan/ckan/blob/5c6ab31/ckan/controllers/package.py#L620

The resource_edit method currently filters fields passed to the resource form for draft datasets, breaking custom schemas with resource extras defined.

**Comment by torfsen** [comment]
Just ran into this. In addition to the problem pointed out by @wardi, there's also the issue that the POST data returned by the form does not include the extras. Hence, when `resource_update` is called with the data, the extras are lost.

As a simple fix it would probably be enough to use `resource_path` instead of `resource_update` [when storing the POST data](https://github.com/ckan/ckan/blob/9de1f467d852d2fac75217cfd36b400d779e718e/ckan/controllers/package.py#L567). That doesn't fix the original problem mentioned by @wardi but it does fix mine (at least according to my quick experiments).

**Comment by torfsen** [comment]
PR #3288 contains the fix I suggested above (using `resource_patch` instead of `resource_update`).

**Comment by wardi** [comment]
fixed by #3480

**Comment by torfsen** [comment]
Reminder for myself: Need to check whether the fix in #3480 also solves the problem I described above regarding the form's POST data not containing the extras.
