### ISSUE TITLE
errors on resource form may require uploaded files to be re-uploaded

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#2650]
The package controller's resource_edit doesn't check if a files the user attempted to upload were successful when there are errors in the form, and just keeps the uploaded name which may be a broken link when the form is saved.

**Comment by wardi** [comment]
also affects resource_new

**Comment by Psykar** [comment]
Is a reasonable solution to this to clear the upload / url field if attempt failed (and was an upload attempt)?

**Comment by Psykar** [comment]
Longer term would either require ajax'ifying, or caching of uploads together with a timed cleanup (not so nice)

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
