### ISSUE TITLE
Resource ID changing when uploading new file

### ISSUE THREAD

**Issue by mattwagstaff** [ckan/ckan#2664]
Is there a quick way to access (and/or export as a list of) the permanent link for a data source landing page?

For example, I understand that almost all pages that exist can be accessed with the page title in the URL, however when clicking on a particular dataset within a full set, CKAN generates a UUID link which may change:

Such as:
https://publications.qld.gov.au/dataset/commercial-fishing-forms/resource/88d905b7-0144-4f57-8969-648490a8272c

Is it possible for a user to access the "title" named permanent link quickly?

**Comment by wardi** [comment]
Are you asking for a permanent link to a specific resource page that doesn't include the dataset name field (which might change?) The best way to do that would be to add a controller with an IRoutes plugin that serves or redirects from /resource/<resource-id> to the correct page.

I think we like having the dataset name in the URL because it provides some indication to which dataset that the resource belongs.

**Comment by mattwagstaff** [comment]
Not what I was going for, but that's good information also - I'll look into that plugin.

I'm aware you can actually access these landing pages without the UUID in the URL using the title of the dataset like you mentioned.

For instance, the same URL I posted above can be accessed with the following: 
https://publications.qld.gov.au/dataset/commercial-fishing-forms/resource/Register%20Temporary%20Transfer%20of%20Quota%20Application%3A%20Commercial%20Harvest%20Fisheries

I typed this manually into the address bar in order to access it. For some reason, when clicking on a file in a range of files CKAN always uses this UUID (which can change with new versions of CKAN, I'm assuming through re-indexing of some sort) to create the URL, what I would like to do is to be able to get a list of particular datasets uploaded in the above format - with their titles rather than the UUID.

Is there a quick way of doing this?

**Comment by davidread** [comment]
Sorry, I'm getting confused with the root of the problem. When you say there is a UUID which changes, exactly which part of the URL are you talking about?

e.g. this is the URL of a resource:

    https://publications.qld.gov.au/dataset/commercial-fishing-forms/resource/88d905b7-0144-4f57-8969-648490a8272c

Are you concerned that the ```88d905b7-0144-4f57-8969-648490a8272c```` part (resource id) changes or is it the ```commercial-fishing-forms``` part (dataset name)?

You said it changes with "new versions of CKAN" - which version of CKAN have you upgraded from and to?

And how does this dataset get changed in your system? Are you using the web form or is it harvested (which harvester?).

IF you are concerned about the resource id changing in the web form then we made a hack in our DGU schema to help resources IDs stay the same: https://github.com/datagovuk/ckanext-dgu/pull/126/files that we might consider for core.

**Comment by mattwagstaff** [comment]
Hi @davidread - based on feedback from staff using that particular resource set, the 'resource ID' changes. Per their explanation to me, this happened in their last CKAN update, I'm unaware of versions. I'm working in a regulated environment and don't have much access to the backend information.

What I'm looking for is an easy way for end users to access or build the 'dataset name' version of the URL without having access to a harvester (which is controlled by an external party). Currently, when clicking on the dataset, it takes them to a landing page with the 'resource ID' in the URL. They are trying to give clients permanent links to the dataset landing pages, therefore the 'dataset name' URL seems like the only way to do this.

It would seem in this instance, having the DGU schema in your core deployment would fix this particular issue. I'm assuming since this has been written though, that other datasets have been known to change UUID also - so, out of interest, what causes this in your experience?

**Comment by davidread** [comment]
You are talking about distributing links to the 'resource' (you call it 'dataset', but the normal thing is to link to the 'dataset' (described on your website as 'Publication Set'). So I understand now why the changing resource ID is a problem for your site and you must understand that it is not an issue for the average CKAN, used for actual datasets and their resources.

I would not trust the resource ID to stay the same, and I suspect that various harvesters and maybe the web form have this problem. It looks like the method your publisher has used is the web form, and uploaded the file to it, and that has caused the resource ID to change. I'll change your issue title to reflect this.

I expect that with the help of the change I sent and a couple of tests then a python developer could fix this. If you don't have the resource in-house then there are developers in Australia you can hire.

**Comment by mattwagstaff** [comment]
Thanks @davidread. This makes sense now. 
To answer my original question (I'm assuming I won't have access to developers in the foreseeable future) is there a way to extract the URL/s containing the 'dataset name' instead of the 'resource id'?

**Comment by florianm** [comment]
@mattwagstaff yes you ckan ;-)

Python:
```{Python}
import ckanapi
c = ckanapi.RemoteCKAN("http://your.ckan.org/", apikey="your-api-key")
res = c.action.resource_show(id="your_resource_id")
res_url = "{0}dataset/{1}/resource/{2}".format("http://your.ckan.org/", res["package_id"], res["id"])
```

R:
```{R}
library(devtools)
install_github("ropensci/ckanr")
library(ckanr)
res_url = ckanr::resource_show("your_resource_id", url="http://your.ckan.org/")$url
```

**Comment by Aaron-M** [comment]
Thanks for the R code @florianm.

I tried it and found I had to use:  
```
install.packages("devtools")
devtools::install_github("ropensci/ckanr")
```
to start.

Testing it on a resource within dataset http://datastore.landcareresearch.co.nz/dataset/multimodal-size-distributions-in-spatially-structured-populations, I get a res_url returned of  

"http://datastore.landcareresearch.co.nz/dataset/b3fa8b3a-e631-4d94-b737-eb0e1b34616b/resource/9a6926d9-6ebf-43bc-b568-be2d5ac14d49/download/velazquezetalprsbdata.csv"  

Which inserts UUIDs for the dataset and resource.  So won't give me the permanent URL to the resource?

The functionality @mattwagstaff is describing (permanent url location for a resource), is actually something that may become more and more in demand - especially as academic/research organisations (such as ours) increasingly use CKAN to store/publish data associated with research publications.  We assign DOIs (Digital Object Identifiers - permanent links to the 'object') to our datasets and include them in the publication (this is often required by journals).

So far the DOIs I have issued have all been at the dataset level, but it is very conceivable that we would want to issue a DOI at a resource instead/as well - so that we can cite a specific resource in the paper, and/or and an additional resource (with a separate DOI) when we load up another years worth of sampling for example, as a new resource within the dataset. (The DOI system has facility for related identifiers - is variant of, is part of... - so having a dataset comprising related reources each with a DOI is quite a likely scenario).

Thanks for your advice/work on this stuff!

**Comment by florianm** [comment]
@Aaron-M that sounds very interesting. I've got on my wishlist to customise ckanext-doi to provide DOI minting through ANDS (who are happy to collaborate) in addition to the existing DataCite minting.

A DOI for a resource URL, together with a permalink would be nice!
The permalink will/should break however when the resource is completely replaced, e.g. through scripted harvesting (if not done carefully). 
Also, e.g. for a CSV resource there are two versions:
* the attached file, which was initially uploaded into the datastore (a postgis table behind the scenes) by the datapusher, and 
* the contents of the datastore table, which can be altered through the datastore API, and overwritten with the original attached file by running the datapusher again.
Which (revision of which) version would need/receive/trigger minting of a DOI?

As for permanent resource URLs, something like 
http://datastore.landcareresearch.co.nz/dataset/b3fa8b3a-e631-4d94-b737-eb0e1b34616b/resource/9a6926d9-6ebf-43bc-b568-be2d5ac14d49 is as permanent as it gets AFAIK.
The filename (included in the /download bit) can change so I wouldn't include that.

For our internal reporting, which uses `ckanR` to pull figures (resources) from our CKAN into reports, I only use the resource ID with `resource_show` - that's good enough on my end.

Fun fact: just now a colleague asked for a permalink to CKAN resources as well.

**Comment by Aaron-M** [comment]
Thanks @florianm  - re DOIs I'll contact you via email, but just to note if anyone else is reading this and interested in DOIs and CKAN, get in touch as we are doing some work with the CKAN developers on DOI minting.

**Comment by mattwagstaff** [comment]
Thanks guys. This is excellent stuff. Let me get in touch with the managers of our CKAN instance and I'll see if we can get that Python script implemented, seems like the easiest fix. 

I'm actually a little surprised this hasn't been done already, but great that it's being worked on - the charms of open source :)
