### ISSUE TITLE
DataStore API throws 500 when creating an empty datastore and resource simultaneously

### ISSUE THREAD

**Issue by ajb** [ckan/ckan#2676]
Following these docs:

> To create an empty datastore resource and a CKAN resource at the same time, provide `resource` with a valid `package_id` and omit the `resource_id`.

![img](http://take.ms/ty4Ep)

**Comment by rossjones** [comment]
I'm sure someone will be able to check the logs, but can I check that you're sending the required auth header?

**Comment by ajb** [comment]
Yes, I am. Thanks for checking!

On Wed, Oct 7, 2015 at 3:11 AM, Ross Jones <notifications@github.com> wrote:

> I'm sure someone will be able to check the logs, but can I check that
> you're sending the required auth header?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ckan/ckan/issues/2676#issuecomment-146097872>.
>



-- 
Adam Becker
(951) 9-BECKER
@AdamJacobBecker

**Comment by klikstermkd** [comment]
@ajb @joetsoi I just tested this and it works now.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
