### ISSUE TITLE
International (unicode) alphabetical ordering

### ISSUE THREAD

**Issue by trickvi** [ckan/ckan#2683]
CKAN by default ignores international alphabets when ordering strings.

For example on: http://oppnadata.se/organization which is the Swedish portal the letters Ä and Å are ordered just as if they were A when in fact they should come last. Same can be said about Ö which is ordered with O.

This is about setting the locale and using the locale string comparison

    import locale
    # locale being set somehow, somewhere in CKAN
    # sort datasets
    dataset.sort(locale.strcoll)

Happy days.

**Comment by davidread** [comment]
It's either SOLR or Postgres sorting the organizations here.

**Comment by joetsoi** [comment]
http://oppnadata.se/api/action/organization_list

it's ordered in terms of the title (the url slug), we remove the unicode characters, so " Åklagarmyndigheten" becomes "aklagarmyndigheten".

I guess we should order things in terms of name instead of title if we want the correct ordering, @amercader i can take this off you.
