### ISSUE TITLE
datastore_search_sql crash when same column name in sql result

### ISSUE THREAD

**Issue by skrchnavy** [ckan/ckan#2686]
When running query on 2 joined tables that have same column, Internal Server Error occurs.

For testing this queries were used on demo.comsode.eu and join is on the same table. But it is reproducible also in case when 2 different tables are used and one or more columns have same name
- crash  
  `http://demo.ckan.org/api/3/action/datastore_search_sql?sql=SELECT * FROM "c18882df-61f1-418d-a6c7-f0a390916b08" a INNER JOIN "c18882df-61f1-418d-a6c7-f0a390916b08" b ON a."nid" = b."nid"`
- also crash  
  `http://demo.ckan.org/api/3/action/datastore_search_sql?sql=SELECT a.nid, a.created, b.nid, b.created FROM "c18882df-61f1-418d-a6c7-f0a390916b08" a INNER JOIN "c18882df-61f1-418d-a6c7-f0a390916b08" b ON a."nid" = b."nid"`
- result returned OK:  
  `http://demo.ckan.org/api/3/action/datastore_search_sql?sql=SELECT a.nid AS anid, a.created as acreated, b.nid AS bnid, b.created AS bcreated FROM "c18882df-61f1-418d-a6c7-f0a390916b08" a INNER JOIN "c18882df-61f1-418d-a6c7-f0a390916b08" b ON a."nid" = b."nid"`

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
