### ISSUE TITLE
default_group_schema not applied in DefaultGroupForm

### ISSUE THREAD

**Issue by joetsoi** [ckan/ckan#2690]
DefaultGroup.db_to_form_schema does not return a schema, I was expecting default_group_schema, this is surprising and most likely broken, or at least will suprise  anyone writing their own group/org schema in extensions. https://github.com/ckan/ckan/blob/master/ckan/lib/plugins.py#L439-L441

By default
http://master.ckan.org/api/action/organization_show?id=123-org&include_datasets=true

If you create a group plugin and return default db to form schema, the schema is https://github.com/ckan/ckan/blob/master/ckan/logic/schema.py#L294-L299 Which contains just ['id', 'title, 'name'].

**Comment by joetsoi** [comment]
ckan dev meeting agreed DefaultGroupForm should probably return the reduced schema

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
