### ISSUE TITLE
"pip install ckan" does not pull dependencies

### ISSUE THREAD

**Issue by dlax** [ckan/ckan#2702]
`pip install ckan` just install ckan, it does not pull any of the runtime dependencies. I guess this is because the `requirements.txt` is typically meant to be also pip-installed if one is working on a CKAN source, but this file is not available otherwise AFAICT. So it seems to me that ckan is just not pip-installable.

I tend to believe that runtime dependencies should be declared within `setup.py`.

Besides, why are dependencies listed in `requirements.txt` (or `requirements.in`) so tight?

**Comment by davidread** [comment]
> ckan is just not pip-installable.

Correct, not in the well-known way. However the ckan install instructions are clear, guiding people to pip install ckan using `-e` so that requirements.txt is right there in venv/src/ckan, and then you're told to do `pip install -r requirements.txt` so it does install fine.

> why are dependencies listed in requirements.txt (or requirements.in) so tight?

requirements.txt states exact versions of everything, so that there is little room for error for the average installer, which saves a lot of support requests. Pinning versions for dependencies is common and good practice.

> I tend to believe that runtime dependencies should be declared within setup.py.

The advantage of using requirements.txt instead of setup.py is because it allows developers to install different version to the default, due to their custom extension wanting it. They take a risk of compatibility, but that is their option, and quite common. However if the versions were pinned in ckan's setup.py then they would have to hack this file (because setuptools checks these are versions are installed when you run ckan), which requires a fork of ckan. But since the deps are specified in requirements.txt then there are no run-time checks and they can simply install different versions after doing the original `pip install -r requirements.txt`.
