### ISSUE TITLE
"uri" field of resource returned as "None"

### ISSUE THREAD

**Issue by letmaik** [ckan/ckan#2716]
CKAN's API returns `"uri":"None"` for resources instead of `"uri":null` as in the other fields. This upsets the ckanext-dcat extension (see https://github.com/ckan/ckanext-dcat/issues/46).

Demo: http://ckan-demo.melodiesproject.eu/api/3/action/package_show?id=test-datensatz-zum-testen-von-distributionen

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
