### ISSUE TITLE
data-viewer resize iframe not working in IE11.

### ISSUE THREAD

**Issue by euniceong** [ckan/ckan#2722]
the resize function for data-viewer does not work in IE11. the height is not recalibrated.

**Comment by amercader** [comment]
@euniceong Can you send a screen-shot of the issue?

This might be an issue with the Data viewer library itself ([Recline](https://github.com/okfn/recline)). Can you check if one of its demos has the same issue? http://okfnlabs.org/recline/demos/

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
