### ISSUE TITLE
Internal server error raised when inserting data in a wrong format

### ISSUE THREAD

**Issue by frbattid** [ckan/ckan#2728]
You can find a detailed version of this issue at http://stackoverflow.com/questions/33633869/not-able-to-upsert-records-in-demo-ckan-org-500-error

In a few words: if tried to insert an interger value into a column of type Json. Instead of raising an error like "wrong type for value XXX", a "500 internal server error" is raised, which does not help to fix the error in the request.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
