### ISSUE TITLE
json.dumps(validated_pkg_dict, cls=ckan.lib.navl.dictization_functions.MissingNullEncoder) gives TypeError: datetime.datetime(2015, 11, 1, 0, 0) is not JSON serializable

### ISSUE THREAD

**Issue by BartPraats** [ckan/ckan#2744]
When adding custom fields to a dataset of type isodate and format yyyy-mm-dd, I get an error (only in production)

https://github.com/ckan/ckan/blob/0f50cbf73ab626a7dd67ec16b2282be619d81b03/ckan/lib/search/index.py#L124-L125

This line gives the following error for types of datetime.datetime(yyyy, mm, dd, 0, 0)

    TypeError: datetime.datetime(2015, 11, 1, 0, 0) is not JSON serializable

This error only results in a 500 server error on my production site. It occurs on my development site but the result is still a successfully updated dataset.

**Comment by BartPraats** [comment]
I traced back the error to the following line of code:

https://github.com/ckan/ckan/blob/9635971e3b6a9fb813904cd9b7913d3d6d1796eb/ckan/lib/navl/dictization_functions.py#L204

It returns a datetime.datetime object which is not json serializable. Somehow ckan tries to serialize it depending on the ckan.cache_validated_datasets config param.

**Comment by BartPraats** [comment]
Btw I fixed the problem for now using my own date validator. But this should still not happen right? Or am I wrong here?
I also recently discovered that my production site is running on version 2.4.1 and my development site on 2.5.0a. Maybe this might have been the cause...

**Comment by wardi** [comment]
I've found that the isodate validator works for storage of dataset extras because there's some extra logic that handles dates in the db layer, but not for resource extras, because those are stored as a JSON blob. In scheming I've added an extra conversion step to dates and datetimes https://github.com/open-data/ckanext-scheming/blob/master/ckanext/scheming/converters.py#L26 to avoid this problem.

 ckan's isodate validator should probably be changed so that it can be used in resources without this extra step. If you have time, feel free to submit a pull request that makes this change.
