### ISSUE TITLE
"ckan_url" is returned by "package_show_rest", but not "package_show"

### ISSUE THREAD

**Issue by vitorbaptista** [ckan/ckan#2775]
For example, check that https://datahub.io/api/3/action/package_show_rest?id=qualisbrasil returns `"ckan_url": "https://datahub.io/dataset/qualisbrasil"`, but  https://datahub.io/api/3/action/package_show?name_or_id=qualisbrasil doesn't. Given that `ckan.model.Package.as_json()` also returns the `ckan_url`, I suppose returning `ckan_url` is the correct behaviour.

**Comment by amercader** [comment]
`package_show_rest` is long deprecated, as well as `ckan.model.Package.as_json()` (`model_dictize.py` is how JSON objects are created now).

It is not very difficult to construct the value for `ckan_url` from your script if you need it, but if you think it really should be part of the API response feel free to send a PR.

**Comment by wardi** [comment]
We could have a better name for this field. CKAN is important for us, but will end users have any idea what this means?

How about something along the lines of `catalog_url` or `metadata_url`?

**Comment by vitorbaptista** [comment]
@wardi agreed. Simply using `url` would be ideal, IMO, as it keeps the dataset result consistent with the resources. There's already a `url` attribute in the `Package` model though, that I don't know the use. It seems to always be an empty string.

If using `url` is too much work, I would prefer `catalog_url`. I'll start working on a PR using `catalog_url`. If we prefer another name, It would be easy to change it afterwards.

**Comment by vitorbaptista** [comment]
P.S.: If you're able to, please assign this issue to me :+1:

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
