### ISSUE TITLE
Tags' "name" attribute documentation (or code) is wrong

### ISSUE THREAD

**Issue by vitorbaptista** [ckan/ckan#2780]
Although docs says that the name has to be between 2 and 100 characters, and contain only alphanumeric characters, `-`, `_`, and `.`, the validator also accepts whitespace:

``` python
# https://github.com/ckan/ckan/blob/master/ckan/logic/validators.py#L447-L453
def tag_name_validator(value, context):

    tagname_match = re.compile('[\w \-.]*$', re.UNICODE)
    if not tagname_match.match(value):
        raise Invalid(_('Tag "%s" must be alphanumeric '
                        'characters or symbols: -_.') % (value))
    return value
```

At first I thought whitespace could be part of "alphanumeric", but that's not the case. Python's `\w` definition is to match alphanumeric, and it doesn't match whitespace.

I'm not sure if the issue is with the documentation or the actual code

**Comment by amercader** [comment]
See my comment in https://github.com/ckan/ckan/issues/2781#issuecomment-163648639
How are you creating these tags exactly?

**Comment by vitorbaptista** [comment]
I was using `package_create` passing a `tags` dict.

What is the correct fix for this? Is it the documentation that should be fixed, or the actual code?

**Comment by amercader** [comment]
The correct behaviour is for the frontend and the API to apply the same validation rules when creating tags. If we are allowing to use any character on the frontend I don't see why you should not be able to do the same via `package_create`.

I think the whole tags validation is being bypassed on the package controller using the `tag_string` field:

https://github.com/ckan/ckan/blob/master/ckan/controllers/package.py#L506:L509

I would just vote to remove the `tag_name_validator` and allow all values there. IIRC this was enforced historically because tags had dedicated pages and we needed them to be URL friendly but that is not the case any more (and we've been allowing all characters when creating them from the frontend for a while now)

**Comment by amercader** [comment]
I'll raise it on the dev meeting tomorrow

**Comment by vitorbaptista** [comment]
@amercader were you able to discuss this?

**Comment by hamhands** [comment]
Any updates?

**Comment by amercader** [comment]
@hamhands this was marked as "Good for Contribution", meaning that the tech team acknowledges the issue but is unlikely to have time to work on it, so if you can submit a patch that would be great.

The issue you have in https://github.com/ckan/ckanext-dcat/issues/64 is related to this one but not the same. There are essentially [two validators](https://github.com/ckan/ckan/blob/df4b05bf299e4565f8865dcbb095fe2418a4f8fd/ckan/logic/schema.py#L113:L114) at play here: `tag_name_validator`, which deals with the issue described by @vitorbaptista and `tag_length_validator` which is the one causing the errors you are getting.

I'm in favour of deleting both of them.

Context:

* CKAN used to have dedicated pages for tags, so the names needed to be URL friendly, this is not the case any more as we just redirect to the search page with the appropriate tag filter
* The package controller is bypassing the name validation entirely [here](https://github.com/ckan/ckan/blob/df4b05bf299e4565f8865dcbb095fe2418a4f8fd/ckan/controllers/package.py#L512:L514), so that causes different behaviour on the frontend an API.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
