### ISSUE TITLE
Migrations are not available to extensions

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#2784]
It would be good to be able to have migrations run from extensions, so that they don't have to:

a. Have a separate paster command to create the database tables they need
b. Have workarounds when the db schema changes
c. Try and autoload tables at startup time.

Integrating with `db upgrade` appears to be the favoured approach.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
