### ISSUE TITLE
Fix relationships between package and organisation.

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#2789]
Currently there package model has a field owner_org, which is the ID of the organisation it belongs to.  It also has an entry in the member table which specifies which group (or rather organisation) the package belongs to.

It would probably be better if the member entries with `capacity='organization'` were removed, and no longer used, in preference for owner_org having a FK constraint on the group table instead.  The FK constraint would have to allow nulls so that datasets didn't have to be in an organisation if it wasn't required.

**Comment by EnricoMantoria** [comment]
So, a nullable FK? Is there a better way?

**Comment by rossjones** [comment]
I think this is the lowest impact change, and a move towards the ideas in https://github.com/ckan/ideas-and-roadmap/issues/165 which I think should be the end-goal.  

I had a brief look at doing this, and the problem came with the tests as they often use '' to remove a dataset from a group - and we don't want to be setting owner_org to ''. I tried setting this to null in validation/conversion but it didn't remove the dataset from the organisation, so probably more investigation required as to why.  

This is up-for-grabs if you wanted to have a try at implementing it, it should be reasonably self-contained.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
