### ISSUE TITLE
IPackageController has no before_create

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#2792]
Although IPackageController has an after_create method, IResourceController has an after_create _and_ a before_create.

Perhaps before_create would be useful for IPackageController as well?

**Comment by gleb-rudenko** [comment]
@amercader, I can work on it.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
