### ISSUE TITLE
authz.auth_is_anon_user() doesn't work inside tests

### ISSUE THREAD

**Issue by vitorbaptista** [ckan/ckan#2799]
A user is considered anonymous if it's either falsy or an IP address (https://github.com/ckan/ckan/blob/master/ckan/authz.py#L426-L442). The problem is that `BaseController` sets `c.author` to be either the `c.user` or her IP address, and when there's no IP address (as when the requests comes from testing), it is set to the default `Unknown IP Address` string (https://github.com/ckan/ckan/blob/master/ckan/lib/base.py#L260-L263).

In that case, `authz.auth_is_anon_user()` will return false, as if the user isn't anonymous. This creates issues in (for example) `package_create` (https://github.com/ckan/ckan/blob/master/ckan/logic/auth/create.py#L7-L37).

**Comment by vitorbaptista** [comment]
The test to check if the user is an IP address is also quite fragile: it simply checks if there's a `.` (dot) in the username.

**Comment by wardi** [comment]
even better would be to never store an IP address in this author field.

**Comment by vitorbaptista** [comment]
@wardi Definitely. While that doesn't happen, I've submitted a PR to fix this and also add tests to this method (https://github.com/ckan/ckan/pull/2801)

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
