### ISSUE TITLE
Opening a deleted dataset or organization logs you out

### ISSUE THREAD

**Issue by bzar** [ckan/ckan#2805]
Steps to reproduce:

1. Create a dataset as user A
1. Remove the dataset
1. Log out
1. Log in as user B (regular user)
1. Open the removed dataset via address bar
1. You are now logged out at the login screen

Redirecting to login screen is OK since the user does not have sufficient privileges to view the removed dataset, but logging them out is, in my opinion, unnecessary.

**Comment by rossjones** [comment]
I think that unauthenticated, or users without permission to edit, should get a 404 if they visit a package where state='deleted'.  The question is really, should we, instead of doing this check in package_show instead do it as part of check_access so that it applies to everything that has state=deleted?

**Comment by rossjones** [comment]
Confirmed on master. User is logged out :( 
Will investigate a PR to return 404 instead.
