### ISSUE TITLE
String is too long for tsvector (DataStore)

### ISSUE THREAD

**Issue by drnextgis** [ckan/ckan#2837]
Trying to add resource to DataStore but get an error:

```
sqlalchemy.exc.OperationalError: (OperationalError) string is too long for tsvector (3981192 bytes, max 1048575 bytes)
 'CREATE  INDEX "e8546e524414cd2dda84335b59aebc2cb83cebf2" ON "8bcedaa0-3630-4259-b94c-8bec3b82206a" USING gist(to_tsvector(\'english\', "GEOM"))' {}
```

Is there way to exclude some fields from tsvector column for preventing such error?

**Comment by wardi** [comment]
it looks like the decision about which fields are indexed is based only on the column type. You might need to change this part of the datastore code: https://github.com/ckan/ckan/blob/master/ckanext/datastore/db.py#L482

making the full-text indexing configurable would be great. Maybe something as simple as a configuration option with blacklisted column names (like "GEOM" in your case)

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
