### ISSUE TITLE
Group auth for sub-types is insufficient

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#2852]
Currently, if you implement IGroupForm the default group auth functions are used, and so based on ckan.auth.user_create_groups you may or may not be able to have normal users create groups.   If you want different behaviour between different IGroupForm implementations, you're out of luck.

Would be useful to have either:
- A different set of config settings, named after the group 'type' that allowed changing auth per-group-type
- A way for IGroupForm to specify the names of the auth functions for a type.  So, my sub-type 'collections' could specify that collection_create should be called as opposed to group_create even though this would involve duplicating a lot of group_auth.

If you have a a single IGroupForm, you can just override the group_\* auth functions, but this doesn't help if you have more than one group type.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
