### ISSUE TITLE
FQ params are incorrectly wrapped in list when passed to Solr.

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#2853]
Just before 'fq' parameters are passed to Solr, they are wrapped in a list. This will break any usage of tagged fq parameters (such as {!tag name}name:something) as they don't like being sent as a single long string inside a list.

Solr is happy to either get a string for fq, with all parameters in, or a list where each item is a single fq term.  Currently fq in the code is treated as a string and dangerously splits on spaces (which will break with terms that contain a space).  We should change the fq parameter to be a list of filters to apply, but would need special considering for API calls to ensure it doesn't break anything.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
