### ISSUE TITLE
Admin urls load empty templates outside of controller

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#2871]
Since admin urls are mapped behind ckan-admin/someurl, templates are loaded through admin/trash because ckan (or pylons) tries to match folder structure to unmapped url.

For example: 
http://demo.ckan.org/admin/trash 
http://demo.ckan.org/admin/confirm_reset

These won't actually do anything but urls should match to controllers, will provide a PR when I have change to make it.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
