### ISSUE TITLE
Amazon CloudSearch Support

### ISSUE THREAD

**Issue by STOIE** [ckan/ckan#2877]
Hi all,

Just wondering:
* Is there any support for Amazon CloudSearch as a search backend?
* Could it happen without too much effort?

I want to build a fully containerized version of ckan running on Amazon Elastic container service, with elastic disk volume mounts (auto-handling of shared disk). Then use RDS Postgresql for the DB, Elastic load balancer and something for the search... which I am hoping could be a pluggable service like CloudSearch...

Thoughts?

Aaron.

**Comment by rossjones** [comment]
As CloudSearch is powered by Solr, as long as you can give it the CKAN schema.xml then I can't see why it wouldn't work.  There's no specific support in CKAN for CloudSearch though.

Hope this helps.  And sounds like the type of thing which'd make an awesome blogpost ;)

**Comment by STOIE** [comment]
Hey Ross,

I think the issue is that CloudSearch although backed by apache solr, it actually only responds to calls over it's own API, which I assume is a fairly simple change from the standard solr calls, but I have no idea where I would need to start looking to make ckan compatible.

I agree that if CloudSearch did allow use of the standard solr connections, it would be a walk in the park making this work... but, it doesn't look like it's going to be that simple.

Aaron.

**Comment by rossjones** [comment]
Judging by http://docs.aws.amazon.com/cloudsearch/latest/developerguide/search-api.html it doesn't seem a million miles away, but is probably different enough that it would likely involve changes to the code at https://github.com/ckan/ckan/tree/master/ckan/lib/search (for anyone that is considering it).

**Comment by duttonw** [comment]
This would be very nice to be able to make a true HA ckan without needing zookeeper and a cluster of solr index's.

The solr search layer does not have an interface like the IUploader has, if this was ever to occur, it would need to have an Interface created to seperate searching and index updating from the ckan core to allow a drop in plugin to add this functionality. A little like the s3 plugin for where files are stored (instead of on disk etc)
