### ISSUE TITLE
Grid view converts CSV column header 'title' to the site title

### ISSUE THREAD

**Issue by MrkGrgsn** [ckan/ckan#2923]
For CSV resources with a column header of 'Title', the grid and data explorer previews displays the site title as the header of this column.  The expected behaviour is that it would simply display "Title". Observed in CKAN 2.3.1.

**Comment by MrkGrgsn** [comment]
Screenshot
![title error](https://cloud.githubusercontent.com/assets/3621881/13909505/d9526e08-ef68-11e5-8a2d-e72bcaf59df5.png)

**Comment by smotornyuk** [comment]
What is the purpose of [sanitizeFieldName](https://github.com/okfn/recline/blob/master/src/view.slickgrid.js#L163-L171) function? Because of it's name, i thought that it removes/encodes all special chars, but in instead of it, fieldName used as selector for dom element. Because of this we have that interesting behaviour using column names like 'title', 'div', '#some-id-that-can-appears-on-the-page'. Probably this function must be rewrited to something that really escapes/removes special chars?

**Comment by amercader** [comment]
@smotornyuk the original goal was to avoid injections as SlickGrid will evaluate the header contents:

https://github.com/okfn/recline/commit/0990dce8edf0afa7af7d5e352daf98b571ed3d48

My solution is obviously not optimal so if you can come up with a better one that would be great

**Comment by smotornyuk** [comment]
@amercader i created [pull request](https://github.com/okfn/recline/pull/498). I prefer this way because it encodes required entities and we haven't need to mess with regExps or any other kind of replacement directly)

**Comment by amercader** [comment]
Fix for this in #2961
