### ISSUE TITLE
Escape special characters in password while db loading

### ISSUE THREAD

**Issue by drnextgis** [ckan/ckan#2952]
CKAN doesn't escape special symbols within password.

Restore procedure:

```
paster db load -c /etc/ckan/default/production.ini my_database_dump.sql
```

in my case produces the following invalid command:

```
PGPASSWORD=Ab1239idap&u && psql -U ckan_default -h localhost -d ckan_default -f /mnt/portal/tmp/ckan.pg_dump
[1] 26628
-bash: u: command not found
```

**Comment by wardi** [comment]
I'd prefer to remove the "db load" command and instead just document how to dump and restore using the postgres tools directly.

**Comment by torfsen** [comment]
@wardi: According to [the documentation](http://docs.ckan.org/en/latest/maintaining/paster.html#dumping-and-loading-databases-to-from-a-file), `db load` also automatically performs DB migrations if the data comes from an older CKAN version. That is a really nice feature that you won't get by using the raw postgres tools.

**Comment by wardi** [comment]
This command prevents users from using a bunch of the useful options available in pg_dump/pg_restore and I don't think it's really much of a burden to run `paster db upgrade` after restoring the db.

If you really like `db load` and are willing to fix this issue I won't refuse the fix. I think it's really useful to know that you don't *need* ckan in order to perform a backup or restore, though.

**Comment by torfsen** [comment]
Ah, I wasn't aware of the `db upgrade` command (the [online documentation](http://docs.ckan.org/en/latest/maintaining/paster.html) doesn't mention it explicitly and I never checked `paster db --help` before). In that case you're probably right and `db load` can be removed. A section in the docs describing the full database dump/restore/upgrade cycle would be useful then.

**Comment by TkTech** [comment]
+1 for removing `db load` in favour of improved documentation.

**Comment by mattfullerton** [comment]
@torfsen, it is documented where it needs to be though, albeit slightly hidden: http://docs.ckan.org/en/latest/maintaining/upgrading/upgrade-source.html#upgrading-a-source-install

**Comment by torfsen** [comment]
@mattfullerton: Yeah, it's also described at [database migrations](http://docs.ckan.org/en/latest/contributing/database-migrations.html). However, the [command line interface page](http://docs.ckan.org/en/latest/maintaining/paster.html) always had an "exhaustive" look and feel to me. From there I learned that `db load` does the necessary migrations and that's all that I've ever needed :wink: 

Perhaps the paster reference could be auto-generated so that the reference and `paster --help` / `paster command --help` contain the same information.

**Comment by dancastellani** [comment]
Hi, I'm having the same password problem but with `paster pg dump`. 
Is that fixed already? 
If not, I fixed it on my CKAN and can submit a fix for the `paster pg dump`.

Please let me know. Thanks

**Comment by torfsen** [comment]
Can this be re-opened until the discussed documentation improvements have been implemented? This is still affecting users, see for example [this Stack Overflow question that was posted today](http://stackoverflow.com/questions/38242908/dump-the-ckan-database-and-load-it-in-another-ckan-instance/38248006#38248006).

**Comment by NicolaiMogensen** [comment]
The command `sudo -u postgres pg_dump --format=custom -d ckan_default > ckan.dump` is invalid syntax in Postgresql 9.5 omitting the `-d` works as intended
