### ISSUE TITLE
Is there a reason why created date cannot be set on a group?

### ISSUE THREAD

**Issue by martinburchell** [ckan/ckan#2980]
### CKAN Version if known (or site URL)
2.5.2

For our customer's site we are using a custom group plugin to model events (earthquakes, floods etc). We are importing historic datasets from another system and want to set the created date on the group to be the date of the event in the past. By default you can't do this because default_group_schema() has 'created' set to 'ignore'. We can override this in our plugin but I am interested to know why this restriction exists in the first place.

**Comment by TkTech** [comment]
I believe the reasoning was sane - `created` is filled in by SQLAlchemy when the model is created, it wasn't really intended to be a user value because your use case wasn't originally thought of.

As long as you can override it in the plugin, I don't see a problem with this - the way you're using groups is pretty niche.

**Comment by wardi** [comment]
I think we should be able to set the created dates from our default API. I commonly dump users, groups, datasets and organizations from one CKAN instance and load them in another using ckanapi dump/load. The dataset model has recently been changed to support this https://github.com/ckan/ckan/pull/2739

**Comment by wardi** [comment]
just discussed this at the dev meeting. General feeling is "yes, go ahead and override it in a plugin if you need to". If you'd like to change the default ckan schema submit a pull request and we'll talk about it there.
