### ISSUE TITLE
Coverage results are no longer pushed to coveralls

### ISSUE THREAD

**Issue by k-nut** [ckan/ckan#3032]
### Please describe the expected behaviour

When the circle ci build finishes it should push the changes to coveralls.io to report code coverage.
### Please describe the actual behaviour

Coveralls.io has not gotten any new results since April 26th. See [the overview page](https://coveralls.io/github/ckan/ckan)

According to @brew this is because Travis was replaced with circle ci and that is not pushing the results there.

**Comment by k-nut** [comment]
Actually circle.ci also supports displaying coverage results directly. [Documentation](https://circleci.com/docs/code-coverage/#see-coverage-in-circleci)

But it seem that does not provide a pretty status badge.

**Comment by brew** [comment]
CircleCI is now pushing coverage to Coveralls on my branch [1], but Coveralls is reporting a big drop in coverage [2] since the last report from Travis; from 87% to 54%. I'm wondering if it's something to do with CircleCI working with parallel builds? I've added the recommended env var to CircleCi `COVERALLS_PARALLEL=true`, which is meant to resolve this.

[1] https://github.com/ckan/ckan/compare/3032-coveralls-circleci
[2] https://coveralls.io/builds/6267422

**Comment by k-nut** [comment]
@brew what is the status of this? Should you try to push something to your branch again so that circle does another build and coveralls can pick up the results again?

**Comment by brew** [comment]
Coveralls picks up the results, but the coverage is low for some reason.

**Comment by k-nut** [comment]
Hm. It also reports coverage for the test files. We probably do not want that but it is interesting to see. Because it seems like the tests are not all executed? Maybe this is only a problem with measuring coverage on the tests though...

 [example for non executed test] (https://coveralls.io/builds/6324944/source?filename=ckan%2Ftests%2Flib%2Fnavl%2Ftest_validators.py)

 [example for executed test](https://coveralls.io/builds/6324944/source?filename=ckan%2Ftests%2Flegacy%2Ffunctional%2Fapi%2Fmodel%2Ftest_revisions.py)

As you said already the [documentation](https://coveralls.zendesk.com/hc/en-us/articles/203484329-Parallel-Build-Webhook) says that we should set the `COVREALLS_PARALLEL` flag but it also says that we should set the webhook to the `coveralls.yml` file. Is it possible that we are not doing that?

**Comment by brew** [comment]
I think the documentation is wrong there. They mean circle.yml.

**Comment by k-nut** [comment]
Agree. But I also do not see it in our circle.yml.

**Comment by brew** [comment]
On the branch I'm working for this: https://github.com/ckan/ckan/compare/3032-coveralls-circleci

**Comment by k-nut** [comment]
:facepalm: So it does seem like we are doing everything as we are supposed to. 😕

**Comment by k-nut** [comment]
I just disabled the parallel test execution on my fork of the repository in circle.ci and the coverage is back to 87%. So it seems to definitely be that. I'll send them an email and ask if they have any idea what might be going wrong. https://coveralls.io/builds/6341285

**Comment by sirex** [comment]
It looks, that coveralls is still broken.

**Comment by sirex** [comment]
By the way, looking at the [last build](https://circleci.com/gh/ckan/ckan/1978) I see that test coverage is not grate, only 66%.

**Comment by sirex** [comment]
I might be wrong, because it might be 66% only for one parallel test run.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
