### ISSUE TITLE
i18n configured locales read and cache before test helpers change_config() can operate

### ISSUE THREAD

**Issue by sklump** [ckan/ckan#3036]
### CKAN Version if known (or site URL)

master, release-v2.5-ndm
### Please describe the expected behaviour

When running nosetests from ckan/tests/lib/test_helpers.py:TestHelpersUrlFor, applying @helpers.change_config('ckan.locales_offered', ...) and @helpers.change_config('ckan.locale_order', ...) should temporarily affect the locales on offer.
### Please describe the actual behaviour

In ckan/lib/i18n.py, methods _get_locales() and _get_locales_from_config() read configuration values to cache all offered locales before the helpers.py change_config() decorator can inject its temporary values. Hence, all calls for available locales reflect the original configuration file, not its temporarily changed values, irrespective of any application of @helpers.change_config().
### What steps can be taken to reproduce the issue?

Set the original configuration file to have

```
ckan.locale_order=en fr
ckan.locales_offered=en fr

```

Open ckan/tests/lib/test_helpers.py. Apply decorator @helpers.change_config('ckan.locale_order', 'en fr de') and @helpers.change_config('ckan.locales_offered', 'en fr de') to a test method on a 'de' locale. Note that the generated_url never includes the 'de' locale because it is not on offer.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
