### ISSUE TITLE
Contribution request

### ISSUE THREAD

**Issue by IAIS4EP** [ckan/ckan#3052]
Dear CKAN team,

at our Accelerator EUROPEANPIONEERS, we have tested some Enablers, also CKAN.

One of our results is a functional smoketest and to-go Docker based demo with a usage example for this component.

Do you think this could be a useful contribution to the project, allowing new developers very easy visual access to Enabler features, with 1 minute setup?

Please have a look:

https://github.com/IAIS4EP/fiware/tree/master/ge/ge_ckan 

If you like it - can we make it to a pull request ?

kind regards
Peter

**Comment by rleir** [comment]
Is this your hub image?
 [docker](https://hub.docker.com/r/adeprato/watly-cep/), based on a apache-tomcat instance which contains the proton and watly-server applications.

Linked from the project
https://github.com/IAIS4EP/fiware/tree/master/ge/ge_ckan

**Comment by amercader** [comment]
@IAIS4EP thanks for reaching out, there is an ongoing PR that updates the existing CKAN Docker support: https://github.com/ckan/ckan/pull/3029. This has had quite a lot of review and discussion and it will get merged soon, so that would be our preferred Docker approach. What would be very useful is that you had a look at that PR and suggest any enhancements or tips that you might had found while working on your version.
Thanks!

**Comment by deinok** [comment]
@IAIS4EP as @amercader said, Docker images will be updated very very soon (only bugfixes), in next PR docker images will  add some features. If needed, you can use this images [https://hub.docker.com/u/deinok/](https://hub.docker.com/u/deinok/) they are not safe for production for now. Only for beta testing propouses
