### ISSUE TITLE
Can a Resource contain hierarchical data?

### ISSUE THREAD

**Issue by arramiah1** [ckan/ckan#3101]
version 2.6
I need help on a City Data Portal project for which we are trying to use CKAN. The question is technical.
Scenario: The Datastore API documentation mentions that it is a thin layer on top of the relational Postgres SQL db model. In other words, a Resource maps to a single table.
 In our City Data Portal project, a single Resource, such as Toilets or Footpath survey sheet, is laid out the following way:
 - A single Toilet complex is associated with a location - and therefore forms a Resource record.
 - This Toilet complex has a number of urinals, bathrooms and washbasins. The data collection process includes collecting specific data on these. In a relational db, these should be stored in a child table with a foreign key relationship to the parent. Alternatively, a single column in the parent table can store the "children" as a Json array.
 - Further, the children (such as urinals, bathrooms and washbasins) can have additional related tables, that store a different set of survey results related in a one-to-many fashion, that are collected at different points in an year. That is, we store historical data (or different "versions" of the data)
The questions for CKAN are: 
- If Resources map to tables, how would we store hierarchical data as discussed above (instead of a flat structure as is normal in a relational database table) using the Datastore API?
 - What approach do you recommend for storing different versions of the same set of data parameters?

**Comment by wardi** [comment]
You should be able to create JSON fields in the datastore (and if not it will be a pretty simple thing to fix).

You can create multiple tables (ckan resources) with the datastore and then use logical foreign keys to relate them and query with the datastore sql search. The datastore API doesn't currently let you set up enforced foreign keys, but as long as you add the right indexes your queries should perform the same.

Of course If there's feature missing that you would like to add to the datastore extension we're happy to help review the changes you need. I'd like to see most of postgres' functionality exposed through the datastore API, including foreign keys, check constraints etc. in the future. Many CKAN users have written extensions that access the datastore DB directly for adding the features they need, including triggers for live updates, improved full text search and postgis functionality, so that's another option.

The ckan-dev mailing list is a better venue for this sort of discussion, and you might get some pointers to existing code that's similar to what you need there.
