### ISSUE TITLE
package_show returns empty lists for relationships

### ISSUE THREAD

**Issue by martinburchell** [ckan/ckan#3114]
### CKAN Version if known (or site URL)

2.5.2
### Please describe the expected behaviour

I would expect either:
package_show to return populated lists for 'relationships_as_subject' and 'relationships_as_object'
or 
package_show not to include the relationships at all in the returned dictionary
or
package_update to ignore the empty lists when updating
### Please describe the actual behaviour

package_show returns empty lists for 'relationships_as_subject' and 'relationships_as_object', which means that if you call package_update on the returned dictionary, the relationships get deleted.
### What steps can be taken to reproduce the issue?

```
   def test_package_update_does_not_affect_relationships(self):
        parent = factories.Dataset(name='parent')
        child = factories.Dataset(name='child')

        helpers.call_action('package_relationship_create',
                            subject=child['id'],
                            type='child_of',
                            object=parent['id'])

        [rel] = helpers.call_action(
            'package_relationships_list',
            id=child['id'],
            rel='child_of')

        assert_equals(rel['subject'], child['name'])
        assert_equals(rel['type'], 'child_of')
        assert_equals(rel['object'], parent['name'])

        dataset = helpers.call_action('package_show',
                                      id=child['id'])

        # Should not have to do this
        # del dataset['relationships_as_subject']
        # del dataset['relationships_as_object']

        helpers.call_action('package_update',
                            **dataset)

        [rel] = helpers.call_action(
            'package_relationships_list',
            id=child['id'],
            rel='child_of')

        assert_equals(rel['subject'], child['name'])
        assert_equals(rel['type'], 'child_of')
        assert_equals(rel['object'], parent['name'])

```

**Comment by TkTech** [comment]
This was discussed during the meeting - instead of fixing this in `package_show`, we want to remove relationships from `package_show` and instead recommend using`api/action/package_relationships_list` when you want to get the relationships.

Caching the relationships can become complex, and they are used so rarely that the benefit to making the relationship query in every `package_show` isn't worth it.

You can extend `package_show` in your own extension to make the call to `package_relationships_list` if you need it to fit your use case.

**Comment by martinburchell** [comment]
Sounds good to me

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.

**Comment by Freakbrain** [comment]
That this bug is not fixed leads to other problems! 
This leads to that create_resources deletes relationships. 
If it is an bug, it should not be fixed by giving a workaround!
