### ISSUE TITLE
ImportError: No module named plugin when creating a new theme extension

### ISSUE THREAD

**Issue by nabiltntn** [ckan/ckan#3146]
### CKAN Version if known (or site URL)

2.5.2
### Please describe the expected behaviour

Starting CKAN with a new plugin based on my custom extension
### Please describe the actual behaviour

I can't start Ckan after creating a new exension to define my own theme.
I followed the 2.5.2 guide , but i am getting an error message :

ImportError: No module named plugin
### What steps can be taken to reproduce the issue?
- Create new extension with the command :

``` sh
paster --plugin=ckan create -t ckanext ckanext-example_theme
```
- Edit setyp.py to include extension class in entry points
- python setup.py develop
- Add the new plugin in the my development.ini file

**Comment by orolle** [comment]
I use CKAN Version 2.4.0-1 and I get the same error. How did you solved the issue?

**Comment by metaljovi** [comment]
I got same issue as well, any help guys?

**Comment by caninapriori** [comment]
Any one find a resolution?

**Comment by nabiltntn** [comment]
Sorry guys , i fixed it but i dont remember the solution right now

**Comment by caninapriori** [comment]
I changed the name of my extension; the namespaces with "example_" as a prefix seem to be already used.

**Comment by gustavomwk** [comment]
Hello everyone, does anyone has a fix for this?
I am having the exact same problem. The tutorial mentioned at http://docs.ckan.org/en/ckan-2.6.2/theming/templates.html and it fails

with the error ImportError: No module named plugin

**Comment by gustavomwk** [comment]
Hi nabiltntn, can you put a comment on what your tried to fix the problem?
I am having the same exact problem. Thanks in advance

**Comment by davidread** [comment]
The solution to this problem is here: http://stackoverflow.com/a/44068312/1512326

How should we fix the docs though? We use the same path "ckanext/example_theme" in both the tutorial and the files in the ckan repo, so that we can quote real file examples, using `literalinclude` e.g. in https://raw.githubusercontent.com/ckan/ckan/master/doc/theming/css.rst

So renaming one or the other seems not great. Maybe we should just put in a warning to use a different name when you try it yourself?

CC @ckan/core
