### ISSUE TITLE
CKAN wikidata entry

### ISSUE THREAD

**Issue by ghost** [ckan/ckan#3154]
Would you be so kind as to check if the [CKAN wikidata entry](https://www.wikidata.org/wiki/Q977484) contains accurate information ?

**Comment by jcc10** [comment]
Wrong CKAN.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
