### ISSUE TITLE
Make it easier to adapt test config to local environment

### ISSUE THREAD

**Issue by torfsen** [ckan/ckan#3159]
It is currently rather cumbersome to adapt the test config (`test.ini` and `test-core.ini`) to a local environment. For example, I'm running Solr at a different port, so I always have to modify `solr_url` to reflect that. However, since both `test.ini` and `test-core.ini` are tracked via Git I'm often forced to `git stash` my changes, cannot use `git commit -a`, etc.

I think it would be nice to have a separate configuration file for local settings that is included in the main configuration and not tracked by Git. For example, `test.ini` could say

```
[app:main]
# Default values for options which can be changed for local environment go here
use = config:test-local.ini
# Options which should not be changed for local environment go here
```

The repository could then include a template for `test-local.ini`:

```
# Example file for local test settings. Copy to `test-local.ini`

# Test Configuration settings for your particular system (e.g. database
# connection, Solr URL) should go into this file (`test-local.ini`). It
# is automatically included in `test.ini` and not tracked by Git.

[app:main]
# Add your settings here
```

I'm using that approach for [ckanext-extractor](https://github.com/stadt-karlsruhe/ckanext-extractor) and it's working fine.

**Comment by wardi** [comment]
You have a couple options:
* use the [environment variables](http://docs.ckan.org/en/latest/maintaining/configuration.html?highlight=ckan_solr_url#environment-variables) such as CKAN_SOLR_URL to override some core ini settings 
* include your settings in the other direction: make your own test.ini then include the core configuration from there, then use that ini file when running tests

The latter is a little more flexible because you can override settings just by adding them to your ini instead of removing them from the core test.ini

I feel your pain because I've [worked around](https://github.com/datacats/datacats/blob/b436b9cceee039e75af4ab71cf09ddb9614ff766/datacats/environment.py#L719-L720) this before for running core tests across ckan versions. Do you think it's worth adding a third way to configure the core tests?

**Comment by torfsen** [comment]
The problem with the environment variables is that they're not available for all options. Including my settings in the other direction works, but then I still have a new file in my repo that git would like to track and I have to remember to use my file instead of what the documentation says.

I don't think we should introduce a third way for test configuration, to me it's more about making the first way (i.e. the config file(s)) easier to use.

**Comment by Kyle-Falconer** [comment]
I'd like to second this, that it should be easier to add an arbitrary configuration setting.

Another example of why this would be helpful is I'm running into right now is with the [ckanext-cloudstorage](https://github.com/open-data/ckanext-cloudstorage) options. This plugin uses these settings:

* `ckanext.cloudstorage.driver`
* `ckanext.cloudstorage.container_name`
* `ckanext.cloudstorage.driver_options`

The `driver_options` setting in particular needs to not live in the .ini file because it can have password information attached to it, so the only way I see of doing this in a secure and automated way is to programmatically edit the .ini file before CKAN starts up.

**Comment by wardi** [comment]
@Kyle-Falconer are you talking about the same issue? This is about making it easier to run the core tests. What do you mean by adding an arbitrary setting?

It seems like you've been working on docker recently, so if you're talking about arbitrary settings as environment variables you can do that by with an IConfigurer plugin that sets the settings you need from any source you like.

**Comment by amercader** [comment]
This may be useful if you want to set up conf options via env vars: https://github.com/okfn/ckanext-envvars
(it does what @wardi suggests under the hood)

IIRC you can set any conf setting except for `ckan.plugins`

**Comment by Kyle-Falconer** [comment]
Thanks for the suggestions, I'll check it out.

@wardi, I thought my comment was related to the original post because it relates to dynamically modifying the values in the configuration file.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
