### ISSUE TITLE
 ckan.cache_validated_datasets not documented

### ISSUE THREAD

**Issue by rossjones** [ckan/ckan#3226]
### CKAN Version if known (or site URL)

2.5.2
### Please describe the expected behaviour

Clear instructions on how to turn off validated datasets so that I can more easily work on my show_package_schema without package_show using the dict in solr.
### Please describe the actual behaviour

 ckan.cache_validated_datasets is not documented as a config option, appears only in a changelog.
### What steps can be taken to reproduce the issue?

Pretend you've never seen this ticket and try and turn off the Solr cache.
### Possible resolution

Document using  `ckan.cache_validated_datasets = false` to explain how to turn off the Solr cache.

**Comment by amercader** [comment]
That's definitely something worth adding to the config options page. Want to submit a quick PR?

**Comment by rossjones** [comment]
I think turning it off *may* break the search page, so will need to investigate further before advertising the option.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
