### ISSUE TITLE
Error when inserting an empty string in a Json column of the datastore

### ISSUE THREAD

**Issue by frbattid** [ckan/ckan#3231]
### CKAN Version if known (or site URL)

2.3
### Please describe the expected behaviour

I expected the empty string was added as it is, or if not accepted as a valid Json, the a NULL value was inserted; or at least the returned error was related to a malformed Json (if that's the case); please see the actual behaviour.
### Please describe the actual behaviour

500 Internal Server Error <--- it seems like CKAN internally crashes...

Regarding the above error, it is curious the error is different is trying to insert an invalid Json string. In that case a 400 Bad Configuration error is returned (which is OK for me).
### What steps can be taken to reproduce the issue?

By creating a datastore having a single Json column and by upserting an empty string:

```
{"resource_id": "xxxxxx", "records": [{"column_name":""}], "method": "insert", "force": "true"}
```

**Comment by wardi** [comment]
@frbattid Yes, we should be returning a validation error instead of a server error when postgres refuses some of the data we've inserted. Are you interested in working on a fix?

**Comment by frbattid** [comment]
@wardi, I'm just an admin of CKAN, not enough knowledge to fix it :)

Additionally, I've seen the behaviour is the same when inserting `[]`, `{}` or `null` in a Json column. I guess the problem is at PostgreSQL, not at CKAN... Why PostgreSQL is not accepting those values? As far as I know, they are valid Json values.

**Comment by wardi** [comment]
Oh I'm sure it's a datastore problem. The extension probably isn't set up to pass along JSON properly.

This is something I was planning to fix regardless, it's probably pretty simple.

**Comment by frbattid** [comment]
Great, I'll stay tuned.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
