### ISSUE TITLE
Renaming a resource will result in re-upload to the DataStore

### ISSUE THREAD

**Issue by moqri** [ckan/ckan#3268]
It's not an ideal behavior especially for large resource files

**Comment by Moqri** [comment]
For testing: seems it only happens when you rename a completely uploaded resource

**Comment by amercader** [comment]
I guess you mean that the file is uploaded to the DataStore again. Yes, this is not optimal. We should restrict it to when the URL or the uploaded file changes, but IIRC it's difficult to tell exactly what changed at the point that the DataPusher is triggered.

**Comment by TkTech** [comment]
@amercader I guess we could hash it if it's a local upload. We'd still have to skim the entire file but it would be quicker than loading it into DataStore. We can use FileAPI in newer browsers to do it locally. For URLs we could do a `HEAD` request first and hash the value of Last-Modified/ETags/other-caching-values, maybe?

**Comment by wildcatzita** [comment]
@amercader , I'll take a look

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
