### ISSUE TITLE
make facets sortable by function parameter

### ISSUE THREAD

**Issue by hbunke** [ckan/ckan#3271]
Sorting of facet items is hardcoded (in `lib/helpers/get_facet_items_dict()`). However, there might be usecases where this is not the desired sorting and sorting key should be the item title only (in our case this would be a journal's volume or issue number).

Presumably it should be no problem to make the sorting key a parameter for `get_facet_items_dict()` (with the current behavior as default). 

Any thoughts? I'd try to submit a PR if no one objects.

**Comment by amercader** [comment]
Sounds good, as long as you can keep the default behaviour so extensions don't break. Feel free to submit a PR for this

**Comment by hbunke** [comment]
See #3298. For now it's a very conservative change that enables reverse sorting by name for int type values only. I'm not sure if sorting by name would make sense for other values.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
