### ISSUE TITLE
Headers in Data Explorer are displayed not correctly for tables with lots of columns

### ISSUE THREAD

**Issue by moqri** [ckan/ckan#3273]
http://54.242.243.238:8080/dataset/baker-county/resource/42ad0533-7afc-4153-bb54-840993804b17
![image](https://s18.postimg.org/8a59oxoll/Screen_Shot_2016_10_12_at_9_56_10_PM.png)

**Comment by Moqri** [comment]
Double lines header!

**Comment by amercader** [comment]
How many columns approximately? Is it a scrolling problem? Your site is not up so I can't check. Can you upload the file to demo.ckan.org?

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
