### ISSUE TITLE
user 'manage' dialog usability

### ISSUE THREAD

**Issue by rleir** [ckan/ckan#3281]
### CKAN Version if known (or site URL)

dev-v2.6 http://beta.ckan.org/user/edit/rleir#markdown
### Please describe the expected behaviour

A minor quibble. The help text should match the linking policy. Either we allow links (preferred), as shown in the help text, or we disallow them and take them out of the help text.
### Please describe the actual behaviour

Add a link as shown in the help text, and get an error 'The form contains invalid entries: About: Edit not allowed as it looks like spam. Please avoid links in your description.' 
### What steps can be taken to reproduce the issue?

Open your user 'manage' dialog. Click on 'Markdown formatting'. It suggests you can use the format 'http://auto.link.ed/' for a link. Edit such a link into your 'About' text, click 'Update Profile'. You get the error message.

**Comment by gleb-rudenko** [comment]
@amercader , I'll work on it.

**Comment by gleb-rudenko** [comment]
@amercader , ready for review.

**Comment by gleb-rudenko** [comment]
@amercader, any progress with this one?

**Comment by amercader** [comment]
@gleb-rudenko Is there a PR for this?

**Comment by gleb-rudenko** [comment]
@amercader, I guess https://github.com/ckan/ckan/compare/master...gleb-rudenko:user-manage-dialog-usability

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
