### ISSUE TITLE
SOLR - Jetty - Default Installation

### ISSUE THREAD

**Issue by deinok** [ckan/ckan#3303]
### CKAN Version if known (or site URL)
MASTER

### Please describe the expected behaviour
Solr is installed following the docs

### Please describe the actual behaviour
A 500 HTTP Code is raised when accessing http://localhost:8983/solr

### What steps can be taken to reproduce the issue? 
Ubuntu 14.04 x64
sudo apt-get update && sudo apt-get upgrade
Follow the Docs until checking if SOLR is working.

Can give a Virtual Machine Image if needed.

Accessing http://localhost:8983/ shows Jetty default page, but http://localhost:8983/solr shows the following error:
`Problem accessing /solr/index.jsp. Reason: JSP support not configured`

No log in /var/log/solr

### Other information:
[https://github.com/ckan/ckan/pull/2966](https://github.com/ckan/ckan/pull/2966)
[http://stackoverflow.com/questions/30355839/ckan-local-installation-500-error-on-solr-jsp-support-not-configured](http://stackoverflow.com/questions/30355839/ckan-local-installation-500-error-on-solr-jsp-support-not-configured)

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
