### ISSUE TITLE
ckan.site_url cause invalid redirections

### ISSUE THREAD

**Issue by deinok** [ckan/ckan#3345]
ckan.site_url Should not be a mandatory

This cause the HTTP POST forms to be redirected to this url.

To reproduce this, set a valid URL but not pointing to the CKAN Instance, navigation works well but the login and register forms are not redirected well

**Comment by wardi** [comment]
We've discussed this in past issues, the summary is that we use site_url and root_path exclusively because
1. background jobs can't generate full urls without the settings
2. configuring reverse proxies with the right environment variables is fragile
3. even with the right environment variables we can't express things like `root_path=/{LANG}/extra-prefix/`
