### ISSUE TITLE
Package group listing should take group type into consideration

### ISSUE THREAD

**Issue by mikkonieminen** [ckan/ckan#3357]
### CKAN Version if known (or site URL)
CKAN version 2.6.0

### Please describe the expected behaviour
Only groups with type 'group' should be listed when viewing package/group_list.html. An identical issue occurs with the group select input when viewing the same template

### Please describe the actual behaviour
All groups with the attribute is_organization == false are listed and the group's type-attribute is not taken into account. If e.g. a group with the type 'foo' exists, it will also be listed here. The group listing in route '/group' is working as expected. 

### What steps can be taken to reproduce the issue? 
Issue can not be reproduced without new functionality that creates additional group types than 'group' and 'organization'. We have a work in progress [extension](https://github.com/6aika/ckanext-collection) which provides this functionality.

A PR to fix the issue will follow.

**Comment by gleb-rudenko** [comment]
@wardi , can I work on it?

**Comment by amercader** [comment]
@gleb-rudenko yes, see this comment for the proposed approach https://github.com/ckan/ckan/pull/3358#issuecomment-265751895

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
