### ISSUE TITLE
Intermittent test failures in test_jobs

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#3365]
e.g. https://circleci.com/gh/ckan/ckan/2035

@torfsen just to keep this open as we closed #3359

**Comment by torfsen** [comment]
I've spent some time on isolating the problem, see http://stackoverflow.com/q/41279157/857390.

**Comment by torfsen** [comment]
Thanks for the suggestion, @TkTech! I've [re-posted my question to the SQLAlchemy mailing list](https://groups.google.com/forum/#!topic/sqlalchemy/_SN2BDipBw8).

**Comment by torfsen** [comment]
With [the help of StackOverflow](http://stackoverflow.com/a/41722129/857390) I think I've found the underlying problem. Here's how I understand what happens:

1. The main CKAN process initializes its SQLAlchemy engine and stores references to the engine and session in global variables (`ckan.model.meta.engine`, etc.)
2. When a worker is started, rq forks a new child process. That process inherits its parent's global state, including the session and the global variables referencing it.
3. The worker process now initializes its own engine and session, which is necessary because engines cannot be shared between processes.
4. The new worker session is then stored in the global variable that previously pointed to the worker's copy of the parent's session. This causes the refcount of that copy to drop to 0.
5. When the garbage collector in the child now happens to run it will finalize the worker's copy of the parent's session since it's not referenced anymore (within the worker process). This also closes the associated connections, which are shared with the parent. 
6. When the parent now tries to use these connections it finds them unexpectedly closed and raises an exception.

There are two possible solutions to this problem:

1. Keep references to the copy of the parent's session in the worker process so that it doesn't get garbage collected. This is nice because nothing changes for the parent but it's a bit hacky.
2. In the parent, close all connections and dispose the engine before forking and then re-initalize things afterwards. This ensures that no connections are shared with the child, since no connections exist during the fork. This is a cleaner way of doing things but more complicated, since starting a worker now affects the current session.

I'll have a look at how complicated these two approaches are to implement in CKAN (and whether they actually solve the issue :stuck_out_tongue_winking_eye:).

**Comment by wardi** [comment]
@torfsen great detective work! I agree approach #2 sounds like the cleaner option, but a working fix is better than a clean one. :-)

**Comment by wardi** [comment]
fixed by #3377
