### ISSUE TITLE
Content from data explorer table preview cells can not be copied to the clipboard

### ISSUE THREAD

**Issue by fanderegg** [ckan/ckan#3368]
### CKAN Version if known (or site URL)
CKAN 2.5.2, but should also happen in newer versions.

### Please describe the expected behaviour
When you highlight a cell in the preview and Ctrl+C, the content of the cell should be copied to the clipboard.

### Please describe the actual behaviour
The content is not copied to the clipboard. 

If someone has pointers how and where to fix this, we could probably make a pull request.

**Comment by amercader** [comment]
I guess this needs to be implemented at the Recline level, more specifically on SlickGrid which is the library that powers the grid. See https://github.com/okfn/recline/issues/318

Things might have improved in terms of browser support since that issue was created but the solutions suggested there seem a bit hacky to me.

I'm going to close this but feel free to reopen if you want to do any work on this front.
