### ISSUE TITLE
UnicodeDecodeError when creating an  extension

### ISSUE THREAD

**Issue by july7vivian** [ckan/ckan#3379]
### CKAN Version if known (or site URL)
2.5.2

### Please describe the expected behaviour

I wanted to create an extension by the tutorial.

### Please describe the actual behaviour
I executed following commands to create a extension:

`. /usr/lib/ckan/default/bin/activate`
`cd /usr/lib/ckan/default/src`
`paster --plugin=ckan create -t ckanext ckanext-example_theme`
but failed to decode

`UnicodeDecodeError: 'utf8' codec can't decode byte 0xb0 in position 45: invalid start byte in /home/ubuntu/ckan/._ckan.egg-info`
### What steps can be taken to reproduce the issue? 
I attemped to open `/home/ubuntu/ckan/._ckan.egg-info`, but failed.

**Comment by july7vivian** [comment]
@nickstenning

**Comment by july7vivian** [comment]
@nickstenning

**Comment by july7vivian** [comment]
@rossjones

**Comment by rossjones** [comment]
@july7vivian

**Comment by july7vivian** [comment]
It must be impolite to @ you so directly, I am sorry. I found that you answered another queation about the UnicodeDecodeError, so I think that you ought to know this problem. Do you know why this error happened? I read #2636 ,but it doesn't woek for me. Thanks.

**Comment by july7vivian** [comment]
It must be impolite to @ you so directly, I am sorry. I found that you answered another queation about the UnicodeDecodeError, so I think that you ought to know this problem. Do you know why this error happened? I read #2636 ,but it doesn't woek for me. Thanks.

**Comment by rossjones** [comment]
Sorry, I'm on holiday ATM, best wait for it to be triaged by the tech team

**Comment by july7vivian** [comment]
ok, Thanks!

**Comment by amercader** [comment]
@july7vivian Can you provide a full traceback? Does this happen when you enter special characters like accents in the prompts?

**Comment by rwillmer** [comment]
I hit Unicode problems when trying to setup a 2.6.0 docker image. It turned out to be a locale problem.

That might be relevant for your problem. This comment shows how I fixed mine.

[https://github.com/ckan/ckan/issues/3372#issuecomment-268490338](https://github.com/ckan/ckan/issues/3372#issuecomment-268490338)

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
