### ISSUE TITLE
Flask-DebugToolbar - Execute without dev-requirements.txt

### ISSUE THREAD

**Issue by deinok** [ckan/ckan#3388]
Seems like you need to install dev-requirements.txt in order to execute CKAN without tests.

Cause probably be this [https://github.com/ckan/ckan/commit/535f1b4e01584224399a4cf6b45c499cd03f9553](https://github.com/ckan/ckan/commit/535f1b4e01584224399a4cf6b45c499cd03f9553)

**Comment by wardi** [comment]
I think I ran into this earlier too. @deinok mind moving the polib dependency to the main requirements.in and txt?

**Comment by deinok** [comment]
I found this when making the Dockerfile. If you want i can try to take a
look

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
