### ISSUE TITLE
[REDIS] - Redis is not using the ENVVAR

### ISSUE THREAD

**Issue by deinok** [ckan/ckan#3389]
REDIS seems like its not reading the ENVVAR from this [https://github.com/ckan/ckan/blob/master/ckan/config/environment.py#L124](https://github.com/ckan/ckan/blob/master/ckan/config/environment.py#L124)

**Comment by wardi** [comment]
might be an easy fix, @deinok do you have time to investigate?

**Comment by deinok** [comment]
Yep, I also found this due to the docker PR, assign me to this ;)

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
