### ISSUE TITLE
Typing Error in Registration Invite Email

### ISSUE THREAD

**Issue by wildcatzita** [ckan/ckan#3411]
When we register user CKAN send email with text : `A user has already been created to you with the username {{ user_name }}. You can change it later.`

This issue was fixed in https://github.com/ckan/ckan/commit/66549991119191fb00a7aaf907e4027036df4561#diff-7e4740a254720d83765ada35ddd95765

In version 2.6.0 this text was fixed:
`A user has already been created for you with the username {{ user_name }}. You can change it later.`

Can you please apply these changes to an earlier version of CKAN, because many projects are still using older versions of CKAN?

**Comment by amercader** [comment]
Unfortunately I can not backport the change mentioned because it's part of a larger feature which is too large to backport. Changing the string directly would mean having to update all translations to reflect the change in the master string. I suggest that you patch your local instance. I know that's not ideal but it's probably the best option here, sorry!
