### ISSUE TITLE
Intermittent database error

### ISSUE THREAD

**Issue by brunojm** [ckan/ckan#3415]
### CKAN Version if known (or site URL)
2.6.0

### Please describe the expected behaviour
CKAN working normally.

### Please describe the actual behaviour
We are getting an intermittent (log here: https://notepad.pw/share/6lcfas3w1) SSL SYSCALL error, this seems related to a bug in SQLAlchemy (details here: https://bitbucket.org/zzzeek/sqlalchemy/issues/3021/ssl-eof-not-detected-as-disconnect-in).

We have updated SQLAlchemy to 0.9.8 but still getting the errors.

Have anybody had this problem? Solutions?

**Comment by amercader** [comment]
@brunojm This kinds of errors show that the connection to the database is lost. They are usually caused by network connectivity issues. Perhaps CKAN could handle these more gracefully but you definitely should investigate at a lower level on your network. 

Please feel free to reopen if you find more details that point to CKAN being the problem. Cheers.

**Comment by mystycs** [comment]
@TkTech  did you ever find a solution to this?
