### ISSUE TITLE
JS translation directory

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#3461]
Currently our translations for JS are built when loading the environment [1] and placed in the CKAN source tree [2]

1: https://github.com/ckan/ckan/blob/master/ckan/config/environment.py#L114
2: https://github.com/ckan/ckan/blob/master/ckan/lib/i18n.py#L71

Generating files when loading configuration isn't great because we could have multiple processes doing this at the same time, and it seems like an expensive thing to do every time there is a configuration change.

Placing generated files in the source tree is bad for a few reasons. When developing these files can conflict or show up as changes when all the user did was start the server. If running multiple sites with different configuration files all sites are sharing the same directory for JS translations, possibly creating conflicts. Writing into your own source tree conflicts with best security practices e.g. read-only docker mounts or SELinux labels that prevent code self-modification.

I think at a minimum we should add a configuration option for where these JS files (and related static files?) will be generated. It might also be worth separating the generation itself into a separate paster command (incurring a usability cost)

**Comment by torfsen** [comment]
Some context: The JS translation files were previously generated manually using the [`trans` paster command](http://docs.ckan.org/en/latest/maintaining/paster.html#trans-translation-helper-functions) (which still exists). At that time, [extensions could not provide or override JS translations](https://github.com/ckan/ideas-and-roadmap/issues/176). When I implemented support for the latter in #3272, I had to decide how translation strings from extensions' `.mo` files should end up in the generated JS translations. Auto-generating them during start-up had the benefit that it requires no further action by a site maintainers and extension developers (things basically just work).

The files had previously been generated in the source tree, and #3272 didn't change that. We stopped tracking them in #3317 which is an improvement but not really a clean solution.

Note that files are only re-generated if necessary, so during a normal server restart there's almost no time spent on this. Besides, generating the files isn't that slow anyways.

I also think that having the generated files in an instance-specific directory outside the source tree would be ideal, though. However, let's use a sensible default here (somewhere in `/tmp`?) so that we don't add another mandatory configuration option.

**Comment by wardi** [comment]
How about defaulting to a directory under `ckan.storage_path`? That's already a place that the web processes needs write access and the web server serves files from there too.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
