### ISSUE TITLE
resource_delete is not re-entrant

### ISSUE THREAD

**Issue by torfsen** [ckan/ckan#3492]
On 2.6.1, I tried using `resource_delete` in the `IResourceController.before_delete` callback to automatically delete certain resources when other resources in the same dataset are removed:

* User removes resource `A` (manually or via API)
* That triggers `before_delete`
* My `before_delete` implementation deletes resource `B` (in the same package) via `resource_delete`

I expect that both `A` and `B` are deleted, but that is not the case:

* `A` is deleted correctly
* The deletion of `B` is only done partially. In particular, `before_delete` is called for `B` (in addition to the original call for `A`), but the actual deletion does not happen.

The problem is easy to spot in the implementation of `resource_delete`: we get the package dict, then call `before_delete` (which may modify the package) and then re-use the (now potentially out-dated) package dict afterwards.

`IResourceController.after_delete` doesn't have that problem, however it cannot be used in my situation (without additional workarounds) since I need the ID of resource `A`, which `after_delete` doesn't provide.

There are probably other cases where the typical before/after-callbacks can cause similar problems. Is there a general stance whether we allow modifications during these?

**Comment by smotornyuk** [comment]
I think, that current behavior is correct. Main purpose of `after_delete` and `before_delete` is to make some arrangements or additional changes that not affect package in general. What can be changed here is implementing of some kind of workflow, like [Flux](https://facebook.github.io/flux/). Yeah, it generally used for front-end components, but its main advantage is straightforward control of asynchronous actions. Here he change package and synchronously  add updated data to search index and database. But problem in "asynchronous" change that happens at that time, when you remove second resource.
How about implementing some kind of queue. Like in Flux, atomic actions can be dispatched(queued) from another actions, but they will be really performed only when main action completed. In simplest implementation we can add global Queue object, `dispatch_action` function for queuing task and check whether there are some stuff to do after `call_action`. In the end we will obtain somethin opposite to celery - worker that performs foreground tasks

**Comment by TkTech** [comment]
What you're discussing is just generally called a `chain` and is available in both the old celery backend and the new rq backend.

**Comment by torfsen** [comment]
I'm totally OK with restricting `IResourceController` (and `IPackageController`) callbacks to not modify the reported entity directly but use background jobs for that. However in that case we need to document this limitation.

**Comment by smotornyuk** [comment]
@TkTech  No, as i understand they are not the same. I suggest synchronous workflow, where user need to wait until all tasks are ended in order to see result. In that case, when, for example, removal of one resource triggers modification of another one - user will see final result at once. If we use background worker instead - it will be asynchronous - user have to refresh page, because there are no guarantees that job was done before request completed.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
