### ISSUE TITLE
Problem installing stats in release-v2.1

### ISSUE THREAD

**Issue by jortizsisamon-dtt** [ckan/ckan#3501]
[CKAN 2.1.1]

I'm trying to install the 2.1.1 version, following the documentation of how to install as a source [http://docs.ckan.org/en/latest/maintaining/installing/install-from-source.html](url) and I'm obtaining the same error as the commented in the Issue 170. [https://github.com/poguez/ckan/commit/c835bd5072bf1775f1001c3eb102557ac20e06c5](url)

In the 2.1.1 version, the ckanext/stats/__init__.py file doesn't have the line:
`__import__('pkg_resources').declare_namespace(__name__)`
and the process fails.

This error is appearing when I try to clone the repository version with the next command: 

> pip install -e 'git+https://github.com/ckan/ckan.git@ckan-2.1.1#egg=ckan'

How can I fix this problem to install this version? I need it because is the current installed version in the application I'm developing.

Regards.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
