### ISSUE TITLE
Usage of the 'related attribute set' operation is not currently supported within the execution stage of the flush process

### ISSUE THREAD

**Issue by KrzysztofMadejski** [ckan/ckan#3507]
### CKAN Version if known (or site URL)
2.3.5, [pip environment](https://github.com/DanePubliczneGovPl/ckanext-danepubliczne/blob/release/1.2.0/requirements-danepublicznegovpl.txt)

### Please describe the expected behaviour
Fix error message.

### Please describe the actual behaviour
From time to time I'm getting the following message. That's the whole stack trace :/ so it's hard to check where it comes from.
```
[Mon Mar 27 10:40:21.827626 2017] [:error] [pid 19627] /home/ckan/.virtualenvs/ckan/lib/python2.7/site-packages/sqlalchemy/orm/unitofwork.py:79: SAWarning: Usage of the 'related attribute set' operation is not currently supported within the execution stage of the flush process. Results may not be consistent.  Consider using alternative event listeners or connection-level operations instead.
[Mon Mar 27 10:40:21.827692 2017] [:error] [pid 19627]   sess._flush_warning("related attribute set")
```

**Comment by smotornyuk** [comment]
#2017 - this problem had been raised previously but nobody wants to fix it :)

**Comment by KrzysztofMadejski** [comment]
I was searching for it, but couldn't find it. Thanks for the link. Closing as duplicate.

**Comment by tedstrauss** [comment]
the previous issue was closed without any resolution, so closing this one as a duplicate is not appropriate.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
