### ISSUE TITLE
Disable upload file and keep old files avaliable

### ISSUE THREAD

**Issue by thenets** [ckan/ckan#3516]
### CKAN Version if known (or site URL)
2.6.1

### Please describe the expected behaviour
I want to disable upload file without affect actual content.

### Please describe the actual behaviour
I need to disable upload support, but I need to keep all old content available.

### Suggestion
Will be perfect if upload controllers show just "URL" on UI when "ckan.max_resource_size" or "ckan.max_image_size" is equal to zero.

### What steps can be taken to reproduce the issue? 
- Comment "ckan.storage_path" at "{development,production}.ini"

**Comment by amercader** [comment]
That is very reasonable, and what is happening now is that when you disable uploads and try to download an existing uploaded resource you get a Server Exception which is not good.

There are no previous checks on the controller and the uploader [tries to compute](https://github.com/ckan/ckan/blob/69bf8c6a69b081ef38f075942a9dd85c713995ec/ckan/lib/uploader.py#L241:L242) the file path using `ckan.storage_path`, which of course is not available. 

My suggestion would be to introduce a new `ckan.uploads_active` config option that can be turned off while preserving the `ckan.storage_path` option. This could be True by default if we want to maintain backwards compatibility, although False seems more correct.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
