### ISSUE TITLE
Load data into datastore better, using pgloader

### ISSUE THREAD

**Issue by davidread** [ckan/ckan#3517]
Currently data goes into CKAN Datastore via the datastore_create action. This has lots of problems:
* the data is only accepted in JSON format, which requires datapusher etc to convert CSV files, which is slow
* the types of each column are guessed based on the first row. Subsequent rows with different types cause errors
* errors with any row cause the whole load to fail

I propose a new, better, logic function 'datastore_load' that:
* accepts a CSV file, either by URL or a local filepath (for FileStore) or even the content as a parameter.
* if headers row is multiple (messytables could detect this), then you could supply that info
* types of each column could be specified, or left to messytables or pgloader to identify
* pgloader loads the file into the Datastore
* it tells CKAN about it all:
  * so it can update task_status: "pending" then "complete" or "errored" (and prevent simultaneous datapusher jobs)
  * updates the resource with the hash and datastore_active=True

pgloader is quicker than conversion via JSON. It can also detect types using the whole file.

datapusher can call this new function instead of the existing one (pretty much a straight swap). In addition you could use ckanapi to call it, once you had added a new resource, with the data either a URL or uploaded.

This work is to be funded by OpenGov.

**Comment by davidread** [comment]
Comments appreciated @jqnatividad @wardi @amercader @maxious in particular

**Comment by wardi** [comment]
Sounds great. This is why I'm implementing all my datastore validation and transformations with postgres triggers #3428 they *should* work just as well with pgloader.

**Comment by amercader** [comment]
That sounds good to me. Some questions:

* If I understood correctly we need [pgloader](http://pgloader.io/) installed in the same environment as CKAN  (not the db) right?

* How are you planning on integrating with pgloader? spawning a process and calling the binary?

* > pgloader loads the file into the Datastore

   I'm assuming this is done asynchronously using the new queue? In that case maybe we can bypass DataPusher entirely because that's what DataPusher essentially does

* Related to the above, AFAICT pgloader does not support Excel, ODS, etc as input so I guess it could not completely replace it, at least on a first version.

**Comment by davidread** [comment]
Thanks for these @amercader 

> If I understood correctly we need pgloader installed in the same environment as CKAN (not the db) right?
Yes, exactly.

> How are you planning on integrating with pgloader? spawning a process and calling the binary?
Yup. The latest version is lisp, so I can't see a better way.

> pgloader loads the file into the Datastore. I'm assuming this is done asynchronously using the new queue? In that case maybe we can bypass DataPusher entirely because that's what DataPusher essentially does
It's tempting to move DataPusher off ckanserviceprovider and onto [CKAN background jobs](http://docs.ckan.org/en/latest/maintaining/background-tasks.html) however I think this is a separate job and I'll try and avoid thinking about this as well for the time being.

> Related to the above, AFAICT pgloader does not support Excel, ODS, etc as input so I guess it could not completely replace it, at least on a first version.
This is a good point. I think I'd be tempted to create a separate tool that converted Excel/ODS to CSV before using pgloader, rather than stick with the problematic bits of datapusher. But yes, that is for another iteration.

**Comment by jqnatividad** [comment]
Awesome! Datapusher has been a constant problem for us and this will help slay a lot of support issues.

As for pgloader.io, it is available on ubuntu, but the version packaged is a very old version.  It's a good thing though that its available on apt.postgresql.org (https://wiki.postgresql.org/wiki/Apt) so it should help other installations use it without having to build from source.

And I agree that we can just focus on converting other tabular formats to CSV further up the toolchain with some other packages (e.g. xl-rd, etc.) and the pgloader-powered pusher is optimized for CSV.

**Comment by TkTech** [comment]
I may be missing something here but looking at pgloader there is nothing particularly special about it, although it's a handy command line tool. We can change our loading process to be identical to pgloader (verbatim if we need to, as pgloader is under a compatible licence) without having to add a new external dependency. Smarter use of COPY and partitioning with background workers would give us the same benefits.

(I am generally highly biased against anything that adds additional dependencies, so I will play devil's advocate here)

**Comment by jqnatividad** [comment]
Point taken @TkTech , but the motivation to use pgloader.io are the following:

per the README

> Its main advantage over just using COPY or \copy, and over using a Foreign Data Wrapper, is its transaction behaviour, where pgloader will keep a separate file of rejected data, but continue trying to copy good data in your database.    

- This is our primary motivation, as the current datapusher just stops when it encounters bad data. We will leverage the report it produces, and perhaps, even give the dataset publisher actionable info as to which records failed.  Right now, the datastore tab for a dataset provides some logging messages, but no actionable info.  As is, the report it emits has a lot of useful info we can already use instead of the generic datapusher log messages - how many rows loaded, how many did not, and how fast.  And for errors, we can show the CKAN admin the reject.dat and reject.log files.

- In the future, it allows us to expose to dataset publishers/curators pgloader's robust Domain Specific Language (DSL) they can use to help onboard data.  In general, we encourage our users to practice GIGO and clean the data before publishing it.  But in reality, there are a lot of smaller jurisdictions which do not have resources to do this, and giving them the ability to open data using the XLS/CSV they already have and actually use to run a vital government function, without having to clean it through an ETL tool, reduces publishing friction.  

    Possibly, in a future iteration, the curator can even modify the DSL generated by the pgloader-powered datapusher to do simple transformations specific to that dataset (e.g. specifying optimal data type; override messytable's wrong datatype guesses; declare/drop/rebuild indices pre/post load so datastore_search_SQL API calls are more performant, etc) without having access to an ETL tool or knowing how to program - all with a declarative, data-loading, configuration DSL.

- I'm lazy and what pgloader does is non-trivial, and I'd rather leverage something that already works, in the spirit of the [Unix toolchain philosophy](https://en.wikipedia.org/wiki/Unix_philosophy) :)

**Comment by amercader** [comment]
@davidread thanks for your answers, just to clarify this one:

>> pgloader loads the file into the Datastore.

> I'm assuming this is done asynchronously using the new queue?

Is this going to target the new queue, ie CKAN >= 2.7?

**Comment by davidread** [comment]
I've no plans to move this off datapusher's existing ckanserviceprovider job queue.

**Comment by amercader** [comment]
Then I'm missing something.

Right now the one that is doing a long, heavy task that needs to be queued (parsing the CSV file, transforming to JSON and calling `datastore_create` with chunks of the file) is the DataPusher, and that's why it's a separated, queue-based service. 
If I understood correctly your plans, `datastore_load` is the one that will be performing this task (or pgloader rather), so that's what need to be queue based right? DataPusher will just call `datastore_load` with a link/path to a CSV.

**Comment by davidread** [comment]
Ah, I get you now. The datastore_load may take a few minutes, so that's no good for a simple HTTP API call. Excellent point. I'll have a ponder.

**Comment by davidread** [comment]
I did a speed benchmark loading in a large CSV ([370MB / 100k rows])(https://data.boston.gov/dataset/311-service-requests/resource/2968e2c0-d479-49ba-a884-4ef523ada3c0)

Existing 'convert and INSERT': 35 minutes
Existing 'convert and INSERT' but dropping the INDEXes: 13 minutes
pgloader without INDEX: 1m22s

**Comment by davidread** [comment]
2 options spring to mind:

1. A DataStore API call that starts the pgloader asynchronously and responds immediately saying it's started. DataPusher could either poll or wait for a callback, before doing its tidy-up and moving onto the next in its queue. Complicated.

2. pgloader is run from inside Datapusher. I'm hesitant to adding too much into DataPusher, with a view to replacing it. However maybe this new code could just be lifted into the new DataPusher2. And if anyone wants to use ckanapi to [upload a CSV file and put it straight into DataStore](https://github.com/ckan/ideas-and-roadmap/issues/150#issuecomment-108144832), then they can't.

I'm thinking 2. Thoughts?

**Comment by jqnatividad** [comment]
My vote goes to option 2 for the **_initial_** implementation.  Though there is a new queueing system in 2.7+, it will be a while before existing users migrate.

A lot of our users are using CKAN for more than just a catalog, and make extensive use of the datastore and the datapusher is the single biggest source of support headaches.

In the same breath however, the advanced stuff like datatype overrides, using pgloader's config language as an integrated ETL DSL, etc. should be best implemented in "Datapusher v2" using the new queue.

The more than an order of magnitude performance improvement (25x) in @davidread's benchmarking along with other features discussed in this thread and other issues [going back to 2015](https://github.com/ckan/ideas-and-roadmap/issues/150#issuecomment-108144832) (e.g. data-dictionary mapping; data type overrides; data enrichment, etc.) will IMHO move CKAN into more Data-as-Infrastructure type workloads, and should be done using the latest codebase.

**Comment by davidread** [comment]
Agreed @jqnatividad I'll do this.

Although datapusher seems relatively simple to move onto the new queue, there are just so many issues reported with the whole thing, that I want to be careful.
Issues: 
* https://github.com/ckan/ckan/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20datapusher 
* https://github.com/ckan/datapusher/issues

**Comment by jqnatividad** [comment]
Shouldn't we close this, now that we have Express Loader? cc @davidread

**Comment by davidread** [comment]
Yep, this was completed here: https://github.com/davidread/ckanext-xloader
