### ISSUE TITLE
API v2 hard coded for feed items

### ISSUE THREAD

**Issue by martinburchell** [ckan/ckan#3542]
### CKAN Version if known (or site URL)
eg http://demo.ckan.org/feeds/dataset.atom

### Please describe the expected behaviour
It would be good to have the option for the feed to contain v3 API URLs

### Please describe the actual behaviour
only v2 API URLs are available
https://github.com/ckan/ckan/blob/eee6decdbab330e0926942a0299754f33fceaa79/ckan/controllers/feed.py#L418

### What steps can be taken to reproduce the issue? 
Go to http://demo.ckan.org/feeds/dataset.atom
Note the `link` tag after each `summary` tag eg:

`<link length="1633" href="http://demo.ckan.org/api/2/rest/package/test-haushalt" type="application/json" rel="enclosure"></link>`

What would be the best way to implement this?

**Comment by amercader** [comment]
@martinburchell If I understood correctly this is just a matter of updating the `url_for` call that you link to to use the version 3 of the API. (and while you are at it, remove the `self.base_url + ` and use a `qualified=True` param on the `url_for` call.

Are you up for sending a PR?

**Comment by martinburchell** [comment]
Happy to send a PR but it's a low priority for our client and might not happen until mid-May, if at all

**Comment by wildcatzita** [comment]
@amercader made [PR](https://github.com/ckan/ckan/pull/3677)

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
