### ISSUE TITLE
The name of packages are not sorted alphabetically

### ISSUE THREAD

**Issue by jonathan-s** [ckan/ckan#3546]
### CKAN Version if known (or site URL)
http://demo.ckan.org/

### Please describe the expected behaviour
Sorting on name ascending. The expected behaviour in my humble opinion.  
* Abc
* abc
* Bc
* bc
* cba
* Cbc

### Please describe the actual behaviour
It sorts on name ascending, but in the following way. So lowercase and uppercase are separated from each other. If you were looking for a package with the following way of sorting you might miss out the package that where the first letter is lowercase because it's separated from the package that begins with an uppercase letter. 
* Abc
* Bc
* Cbc
* abc
* bc
* cba

### What steps can be taken to reproduce the issue? 
You can see the behaviour at the following url: http://demo.ckan.org/dataset?q=&sort=title_string+asc&ext_bbox=&ext_prev_extent=-154.68749999999997%2C-80.17871349622823%2C154.68749999999997%2C80.17871349622823&page=70

**Comment by torfsen** [comment]
+1. While we're at it, we might as well start using [natural sorting](https://blog.codinghorror.com/sorting-for-humans-natural-sort-order/).

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
