### ISSUE TITLE
Upload progress bar

### ISSUE THREAD

**Issue by grahame** [ckan/ckan#3555]
### CKAN Version if known (or site URL)
2.6.1

### Please describe the expected behaviour
This isn't a bug, it's request for comments on a potential new feature.

When uploading a file, the user should be shown upload progress -- a simple percentage progress bar would be sufficient.

### Please describe the actual behaviour
No progress is shown, unless by the user agent. At the moment only Chrome seems to show upload progress to the user.

### What steps can be taken to reproduce the issue? 
Upload a large file.

The use case is the upload of extremely large assets. The scale of "large" in our use case routinely in the order of 100GB. Those files are usually uploaded from user-agents connected to fast networks (at least 100Mb/s, often 1Gb/s), but an upload might take hours to complete.

There seem to be HTML5 based approaches to this problem space. What level of comfort is there with introducing new JS libraries into core CKAN?

**Comment by TkTech** [comment]
CKAN supports only very limited uploading. You don't *want* CKAN to be the one handling large uploads as it is right now because it'll be using up a worker for a very long time.

The solution to this with local storage (without adding a new, light-thread file server to CKAN) depends on where you're storing it and what you're running, such as nginx using nginx-upload-module. Anything you come up with will need to be an extension and luckily the Uploader interface is completely pluggable.

For remote storage if you're using something like ckanext-cloudstorage and AWS S3 you get secure client-side uploading of effectively infinite file sizes including pause/resume.

**Comment by grahame** [comment]
OK, thanks for the feedback.
