### ISSUE TITLE
Debug footer doesn't show template variables 

### ISSUE THREAD

**Issue by hvwaldow** [ckan/ckan#3584]
### CKAN Version if known (or site URL)
2.6.2

### Please describe the expected behaviour
Debug footer shows template variables. 

### Please describe the actual behaviour
Debug footer doesn't show template variables.

### What steps can be taken to reproduce the issue? 
Set `debug = true` in `development.ini`
Click on "Debug" link in footer.

**Comment by wardi** [comment]
@hvwaldow we removed the template variables from the debug footer because it was causing massive slowdowns (many seconds) when rendering pages that use lots of templates and snippets #3000.

If you need access to the variables used one approach I use is causing the page to fail and inspecting the variables with the werkzeug debugger. If you really want the old behaviour you can add it back from an extension or revert the changes in #3000 in your local ckan.
