### ISSUE TITLE
config-tool doesn't merge settings that span multiple lines

### ISSUE THREAD

**Issue by neilmayhew** [ckan/ckan#3602]
### CKAN Version if known (or site URL)

All, including `master`.

### Please describe the expected behaviour

Merging

```
setting = line1
          line2
          line3
```

into a config file should produce the same value, ie

```
setting = line1
          line2
          line3
```

### Please describe the actual behaviour

It produces

```
setting = line1
```

### What steps can be taken to reproduce the issue?

```
$ >config.ini
$ cat >merge.ini <<EOF
> setting = line1
>           line2
>           line3
> EOF
$ paster config-tool config.ini -f merge.ini
$ cat config.ini
setting = line1
```

**Comment by neilmayhew** [comment]
The problem is in `parse_config()` in `ckan/lib/config_tool.py`. It uses a hand-rolled, line-by-line parsing strategy that isn't compatible with continuation lines.

However, it also doesn't raise an error if it gets a line it doesn't understand, so unfortunately this is a silent bug that took me a long time to track down when my installation wasn't behaving properly.

**Comment by amercader** [comment]
@neilmayhew sorry about the silent failing. Feel free to submit a patch for the parser that allows support for multiple lines.

I'm not sure of the context in which you are using `config-tool` but just so you know you can use env vars to configure CKAN as well. Some of them are directly supported in [core](http://docs.ckan.org/en/latest/maintaining/configuration.html#environment-variables) but you can also use [ckanext-envvars](https://github.com/okfn/ckanext-envvars) to support (almost) all settings.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
