### ISSUE TITLE
Problems in background workers with non-core database relations

### ISSUE THREAD

**Issue by torfsen** [ckan/ckan#3606]
@amercader has [reported](https://gist.github.com/amercader/7d7d3ffa89af834205974cad0d0a57d0) problems with the new background job system where a job succeeds on the first run but then fails on the following runs. This is similar to issue #3243 (fixed by PR #3247). Also of interest may be the issue #3332 (with PR #3337) as well as issue #3365 (with PR #3377).

@amercader has suggested that the problem might be due to DataStore keeping its own set of database connections (one for reading, one for writing). Those are currently not taken into account when the database connection is disposed before a worker is forked and re-established afterwards.

If that is indeed the case then the DataStore DB connections (and all other similar connections established by extensions) need to be taken care of. One way of doing that would be via an interface that provides access to worker events (e.g. `before_worker_fork` and `after_worker_fork`).

The first step, however, should be to create a reproducibly failing test case from the example above.

**Comment by torfsen** [comment]
There is an [existing test case](https://github.com/ckan/ckan/blob/5bc4921f2b7489867aa47905a34331f20f8c64e1/ckan/tests/lib/test_jobs.py#L218) which executes a job that accesses the DB several times. That test case should, in principle, cover the problem described here. However, it has been running successfully for quite some time, so it does not reproduce the problem reported by @amercader.

**Comment by amercader** [comment]
This case does not cover the scenario where another engine is being used by an extension (only the main core one is tested). The problem can be reproduced by enabling the `datastore` plugin on the `test-core.ini` file.

Annoyingly, it is not triggered when enabling the plugin via `p.load('datastore')` though. That may be caused by the way the environment is initialised differently on both cases?

In any case I agree that the new interface you propose is a good approach.

**Comment by torfsen** [comment]
@amercader I've implemented our idea in #3627. Could you please check if this solves your issue?
