### ISSUE TITLE
jQuery version

### ISSUE THREAD

**Issue by Chris-noaa** [ckan/ckan#3665]
Are there any plans to upgrade jQuery? Version 1.x is end of life and there are known vulnerabilities.

**Comment by klikstermkd** [comment]
Some jQuery plugins in CKAN and probably many third-party extensions rely on the current jQuery version included in CKAN, which is 1.10.2, so it must be thoroughly tested if there are some breaking changes introduced by a newer version of jQuery.

**Comment by torfsen** [comment]
@klikstermkd: True, but on the other hand a new minor release is a good time to make such a change. 

Perhaps we could combine this with the Bootstrap3 migration (#3547), since that will require many people to touch their templates, too. In addition, we should also check whether our other JS dependencies need to be updated.

It seems that there are [quite a lot of breaking changes in jQuery 3.0](https://jquery.com/upgrade-guide/3.0/). As far as I understand, [2.0 is API-compatible with 1.9](https://blog.jquery.com/2013/04/18/jquery-2-0-released/) (we're currently on 1.10.2).

**Comment by klikstermkd** [comment]
@torfsen Yes, I think we can safely upgrade to 2.x with a good testing.

**Comment by klikstermkd** [comment]
jQuery 2.x removes support for IE 6/7/8, which means we have to decide is that the right choice to go with.

cc @torfsen @amercader @wardi

**Comment by klikstermkd** [comment]
I just tested the latest stable 2.x version in #3547, which is 2.2.4, and everything seems to work since the API is backwards-compatible. 

All frontend tests pass as well.

Also, the minified version of 2.2.4 is 85KB in size, whereas the current 1.10.2 that is used now it's 145KB. This means that the script will download and parse faster resulting in a greater UX.

**Comment by torfsen** [comment]
The documentation [says](http://docs.ckan.org/en/ckan-2.6.2/contributing/test.html?highlight=browser#front-end-testing)

> All new CKAN features should be coded so that they work in the following browsers:
> 
>     Internet Explorer: 11, 10, 9 & 8
>     Firefox: Latest + previous version
>     Chrome: Latest + previous version
> 
> These browsers are determined by whatever has >= 1% share with the latest months data from: http://data.gov.uk/data/site-usage

According to that site, in June 2017 there were

* no visits using IE 6
* 0.24% of visits using IE 7
* 1.50% of visits using IE 8

IE 9 and 10 both have less than 0.5%, while IE 11 has over 20%.

Even though IE 8 still has slightly more than 1% I think it would be OK to drop support for it at this point.

**Comment by willc** [comment]
Just to chime in, jQuery 1.x and 2.x are both end of life, with known security vulnerabilities that they do not plan on back-porting fixes for. Any new security issues that may be found will likely not get fixed either.

https://github.com/jquery/jquery.com/issues/162
