### ISSUE TITLE
translate urls

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#3706]
We'd like to make it possible to translate all parts of CKAN urls: the route urls, the root_path, and even the site_url when switching languages.

e.g. when clicking the "Français" option on a page like `http://open.canada.ca/data/dataset` it should lead to `http://ouvert.canada.ca/donnees/donnees`. For the moment we've implemented a half-solution with redirects for the host name.

Kind of a hack, but we could intercept the request early in the middleware to rewrite the URL from the translated `http://ouvert.canada.ca/donnees/donnees` to the expected `http://open.canada.ca/data/fr/dataset` so that it can be parsed as normal (pages might be confused about their real urls, sadly). Then in url_for apply the reverse to send users to the translated URLs. We'll need a new interface to define these translations in an extension. I don't think url translations fit nicely with gettext, especially for route urls.

How does this sound? Any suggestions for another approach?

**Comment by TkTech** [comment]
<opinion> As much of this as possible should be left to extensions. I know the client wants it but I absolutely hate even having a french title in there. URIs should be unique and only one URI should ever point to the same data. </opinion>

**Comment by wardi** [comment]
Yes, only for theme extensions that require it... Even more fun if this leads to things like trying to translate our facet query parameters in our search URLs (we'll have to say no at that point)

**Comment by wardi** [comment]
@TkTech if we do it right (add redirects for improper urls) then we'll still have one only URL per resource since {{LANG}} is already part of the current URLs.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
