### ISSUE TITLE
Harvesting to no organization (on purpose)

### ISSUE THREAD

**Issue by Rjones8901** [ckan/ckan#3708]
### CKAN Version if known (or site URL)
2.6.2

### Please describe the expected behaviour
When selecting "No Organization" for the harvester source, then the source should still be harvested if the setting ckan.auth.create_dataset_if_not_in_organization = true

### Please describe the actual behaviour
Get an error message that an Organization must be selected

### What steps can be taken to reproduce the issue? 
Creating a harvesting source with No Organization selected.

**Comment by smotornyuk** [comment]
Thanks for report, i'll take a look at it

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
