### ISSUE TITLE
Editors cannot see the organisation they are assigned into in the dashboard

### ISSUE THREAD

**Issue by camfindlay** [ckan/ckan#3727]
A reported User Experience issue from a user of our portal.

### CKAN Version if known (or site URL)
2.6.x

### Please describe the expected behaviour
When a user with "editor" permissions who has been added to an organisation logs in they should see that they are a member of that organisation (even though they cannot manage the organisation).

### Please describe the actual behaviour
When the editor user logs in and are reditected to the dashboard the "My organsiation" tab is empty causing the user to question whether they are indeed a member of that organsiation.

### What steps can be taken to reproduce the issue? 
1. Setup a user
2. Add the user to an organisation and set their permission to "editor"
3. Login as the user in step 1
4. See the My Organsiations tab in the dash.

**Comment by wildcatzita** [comment]
I will take a look

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
