### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by ggcatu** [ckan/ckan#3729]
### CKAN Version if known (or site URL)
http://docs.ckan.org/en/latest/contributing/frontend/templating.html#form-select
http://docs.ckan.org/en/ckan-2.6.2/contributing/frontend/templating.html#form-select

### Please describe the expected behaviour
```
{% import 'macros/form.html' as form %}
    {{ form.select('year', label=_('Year'), options=[{'name':2010, 'value': 2010},{'name': 2011, 'value': 2011}], selected=2011, error=errors.year) }}
```

### Please describe the actual behaviour
```
{% import 'macros/form.html' as form %}
{{ form.select('year', label=_('Year'), options={'value': 2010, 'value': 2011}, selected=2011, error=errors.year) }}
```

### What steps can be taken to reproduce the issue? 
The example in the documentation is wrong, and actually doens't work.

**Comment by ggcatu** [comment]
Only fixed on latest documentation, don't know how to push to ckan-2.6.2

**Comment by smotornyuk** [comment]
Thanks, i backported it to v2.6.3

**Comment by ggcatu** [comment]
Shouldn't it be backported to 2.6.2 which is the stable version?

**Comment by smotornyuk** [comment]
No, we are making patch releases for such branches. In most workflows(including ours) after making version available to public, there is no any possibility to somehow change this version. It leads to having instances with same versions but different functionality, thus it harder to fix bugs.
All existing minor versions will stay the same and any observed problem will be fixed in patch release - it's the law :)

**Comment by ggcatu** [comment]
Cool, that makes perfectly sense
