### ISSUE TITLE
Format isn't recognized out of the mimetype

### ISSUE THREAD

**Issue by Vanuan** [ckan/ckan#3774]
### CKAN Version if known (or site URL)

2.6.3

### Please describe the expected behaviour

Setting mimetype to 'text/csv' using API should result in format being automatically set to 'CSV'.

### Please describe the actual behaviour

Setting mimetype result in format being equal to mimetype.

### What steps can be taken to reproduce the issue? 

Use 'resource_create' to create a resource with mimetype: 'text/csv' and format undefined.

**Comment by Vanuan** [comment]
Why even have the field mimetype if it doesn't influence format in any way?

**Comment by wardi** [comment]
We auto-fill the mimetype from the format, but since there isn't a 1:1 mapping between mimetypes and file extensions doing the same in reverse could lead to strange behaviour. @Vanuan if you would like the reverse to happen in your site it's certainly possible with a custom validator on the format field, e.g. when no value is passed, look it up in the mime types table and store that instead.

**Comment by Vanuan** [comment]
Oh, I see. So mimetype is useless to fill in for my use case.
