### ISSUE TITLE
[Badges] - Add a badge to the pip dependencies

### ISSUE THREAD

**Issue by deinok** [ckan/ckan#3778]
[![Requirements Status](https://requires.io/github/ckan/ckan/requirements.svg?branch=master)](https://requires.io/github/ckan/ckan/requirements/?branch=master)

https://requires.io/github/ckan/ckan/requirements/?branch=master

This can help to see the actual state of dependencies.

**Comment by wardi** [comment]
@smotornyuk @tino097  if you thought I was going crazy in the dev call, this is what I was referencing https://en.wikipedia.org/wiki/Stinking_badges

**Comment by amercader** [comment]
@deinok It will take a long time until we can have all requirements up to date, essentially because until we don't get rid of Pylons for good there will always be some outdated requirements. So I don't think it's a good idea to have a badge that permanently says outdated on the README as this will give the impression that we don't try to have all requirements up to date as much as possible (which we do).

To that point, now it would be a great time to update requirements as we've just released a new version if you have time for that.
