### ISSUE TITLE
New plugin hooks before commit

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#3790]
I'd like to explore the inclusion of two new hooks on `IPackageController` and `IResourceController` that would be called just before the actual commit is being made. Something like this:

```diff
diff --git a/ckan/logic/action/create.py b/ckan/logic/action/create.py
index 98b8b2e..8f90f3c 100644
--- a/ckan/logic/action/create.py
+++ b/ckan/logic/action/create.py
@@ -222,6 +222,10 @@ def package_create(context, data_dict):
             {'package': data})
 
     if not context.get('defer_commit'):
+
+        for plugin in plugins.PluginImplementations(plugins.IPackageController):
+            plugin.before_package_commit(context, data)
+
         model.repo.commit()
 
     # need to let rest api create
@@ -326,6 +330,9 @@ def resource_create(context, data_dict):
     upload.upload(context['package'].resources[-1].id,
                   uploader.get_max_resource_size())
 
+    for plugin in plugins.PluginImplementations(plugins.IResourceController):
+        plugin.before_resource_commit(context, data_dict)
+
     model.repo.commit()
 
     #  Run package show again to get out actual last_resource
diff --git a/ckan/logic/action/update.py b/ckan/logic/action/update.py
index d3e3497..c3aafbc 100644
--- a/ckan/logic/action/update.py
+++ b/ckan/logic/action/update.py
@@ -121,6 +121,10 @@ def resource_update(context, data_dict):
             raise ValidationError(e.error_dict)
 
     upload.upload(id, uploader.get_max_resource_size())
+
+    for plugin in plugins.PluginImplementations(plugins.IResourceController):
+        plugin.before_resource_commit(context, data_dict)
+
     model.repo.commit()
 
     resource = _get_action('resource_show')(context, {'id': id})
@@ -333,6 +337,10 @@ def package_update(context, data_dict):
         item.after_update(context, data)
 
     if not context.get('defer_commit'):
+
+        for plugin in plugins.PluginImplementations(plugins.IPackageController):
+            plugin.before_package_commit(context, data)
+
         model.repo.commit()
 
     log.debug('Updated object %s' % pkg.name)


```

There are two main reasons for this:

* My current use case, I want to run a check that depends on the uploaded file contents, and raise a `ValidationError` if I'm not happy about them (could be structural checks, validation against a schema, a virus was found etc). `IResourceController`'s `before_create` does not work because at that point the upload hasn't happened yet, and when `after_create` is called everything is already commited.
* Clarity on what the plugin hooks really mean, eg `IPackageController` `after_create` is called *before* commiting, but `IResourceController`'s *after* commiting.

Does this sound like a worthwhile addition?

If so,

* Is it worth having separate hooks for create / update (ie `before_package_create_commit` and `before_package_update_commit`). I say yes, the more granular the better.
* Do we need `after_commit` hooks? Not sure about that.

**Comment by wardi** [comment]
As discussed in the meeting I've got concerns about creating interfaces that will potentially hold a transaction (logical or otherwise) open for arbitrary lengths of time.

Instead we can move the uploading to the top of resource_update and create an extension point just before reading and updating the metadata. The uploading is done inside a DB transaction right now which creates a really large window for data loss, even worse if we're doing extra data validation before the commit.

The tricky part is faking out the current IUploader interface that right now which expects you to call `update_data_dict()` before calling `upload()`. Maybe calling `upload_data_dict()` (discard the result) then `upload()`, give your plugin a chance to run/validate the data then `update_data_dict()` on a fresh copy of the resource would work.

**Comment by amercader** [comment]
@wardi that makes sense. I'll investigate with your pointers.

**Comment by torfsen** [comment]
If you end up modifying `IPackageController` and `IResourceController` then I'd love to take that chance to also deprecate the currently conflicting names (`after_delete`, etc.) in favour of new, separate names (e.g. `after_resource_delete`, `after_package_delete`). See #2949.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
