### ISSUE TITLE
Fanstatic urls are broken when none root is set

### ISSUE THREAD

**Issue by Engerrs** [ckan/ckan#3793]
### CKAN Version
Latest 2.6

### Expected behaviour
When the root_path is set up, fanstatic generates urls with root_path prefix

### Actual behaviour
When the root_path is set up, fanstatic generates urls without the prefix

This is been fixed in #3628, but backported only to 2.7

**Comment by Engerrs** [comment]
PR https://github.com/ckan/ckan/pull/3794

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
