### ISSUE TITLE
Notify users when they are added/removed from a group or organization

### ISSUE THREAD

**Issue by WNjihia** [ckan/ckan#3818]
### CKAN Version if known (or site URL)
2.7.0a

### Please describe the expected behaviour
A user should be notified on the news feed when they have been added or removed as a member from an organization or group

### Please describe the actual behaviour
The user is added/removed from the organization/group but they are not notified that they have been added as a member

**Comment by wardi** [comment]
https://github.com/open-data/ckanext-extendedactivity might help with this if you're interested in adding it, but I'd support this change in core too

**Comment by amercader** [comment]
That sounds like a good improvement. @WNjihia if you or someone else wants to try to implement it we can provide some guidance.

**Comment by TkTech** [comment]
@wardi Wouldn't recommend extendedactivity (it's a quick hack), instead use the "Removes Revisions" PR #3485 as a base which does the same thing much, much better. Just add a hook to emit the activity and add a template for the activity, you're done.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
