### ISSUE TITLE
Data Dictionary Error - <type 'exceptions.KeyError'>: u'name' when using multilang site

### ISSUE THREAD

**Issue by lolziac** [ckan/ckan#3832]
### CKAN Version if known (or site URL)

**2.7.0**

implemented these fixes
Reorder Resource View button is missing
https://github.com/ckan/ckan/commit/54d6c9b751f83d19084c2ebe49c498849b4c0741

add field_name to image_upload macro when uploading resources #3770
https://github.com/ckan/ckan/commit/a9e9e8652b1472b4c4abb41dbadbe878c4cc9d3f

URL path doubled when adding new dataset form
https://github.com/ckan/ckan/commit/f13aef28e752fd19661ee28f32eb763665f2d305

ckan.plugins = googleanalytics scheming_datasets fluent officedocs_view pdf_view datastore datapusher resource_proxy multilingual_group opendataz_theme recline_grid_view recline_graph_view stats text_view image_view recline_view

Site on 3 languages

### Please describe the expected behaviour

Data Dictionary Tab at Dataset Resources should work on this version 2.7.0 for all languages ?!?!

### Please describe the actual behaviour

example url:
http://opendata.example.com/en/dataset/budget/resource_edit/fa173579-a4ed-4d17-935c-b68e64946d0c

When editing a dataset resource new tab is shown named Data Dictionary which supposed to open form also on other languages. For the moment it opens the form in english only.

Error Log on Apache WSGI
[https://paste.ee/p/PpFqZ](url)

Any Ideas how to fix this ?!

**Comment by wardi** [comment]
scheming and fluent have been developed separately from the recent data dictionary work, so it's likely their templates are just conflicting. If you like you could open an issue or pull request on the ckanext-scheming repository.

For the same reason fluent and scheming haven't been extended to cover the data dictionary form. It is possible to provide your own template to add fields you need to the data dictionary form and override the preview templates so that they display the correct language version for column labels, but AFAIK there is no extension that does this automatically yet.
