### ISSUE TITLE
Can't push csv to DataStore - Relation "_table_metadata" does not exist

### ISSUE THREAD

**Issue by HilariousGil** [ckan/ckan#3868]
### Version 
CKAN 2.7.2 (fresh install)
Datapusher 0.0.12

### Expected behaviour
The CSV would be pushed to the Datastore and be visible in the data explorer.

### Actual behaviour
The file goes to the FileStore, but never reaches the DataStore.

It outputs the following error on the UI:
> Error: cannot connect to datapusher

You can check the [error log output](https://pastebin.com/S64zpZ4F)

### Notes

I have another instance that was running the CKAN 2.6.2 and then I manually upgraded the source to 2.7.1 keeping the DB, and it all continues to work well. But when I do a clean install from 2.7.1 or 2.7.2 I get this error.
Any suggestion?

**Comment by Zharktas** [comment]
You need to set the datastore permission again since they have changed in 2.7 https://github.com/ckan/ckan/blob/ckan-2.7.0/ckanext/datastore/set_permissions.sql#L52

http://docs.ckan.org/en/ckan-2.7.2/maintaining/datastore.html#set-permissions

**Comment by HilariousGil** [comment]
@Zharktas Thanks!! that did it!
I had seen that, but apparently I didn't ran the command properly last time.

**Comment by jspinella** [comment]
I was getting this same error with a fresh install of CKAN 2.8.1. I had run and re-ran the permissions script outlined at https://docs.ckan.org/en/2.8/maintaining/datastore.html. At least I thought I was.

I think it's helpful to tell the world I was running `sudo -u postgres psql` before running the script
`sudo ckan datastore set-permissions | sudo -u postgres psql --set ON_ERROR_STOP=1`, which apparently does not actually execute the SQL (I wasn't seeing any output also so that makes sense...).
