### ISSUE TITLE
Datastore DB gives invalid query error when accessing page

### ISSUE THREAD

**Issue by Invis1988** [ckan/ckan#3872]
### CKAN Version if known (or site URL)

2.7.0
### Please describe the expected behaviour
Datastore should allow me to preview csv/xls files etc on the website.

### Please describe the actual behaviour
I get a ValidationError reporting an invalid query, specifying the table does not exist (for some reason it seems that data is not being uploaded to the tables?)

### What steps can be taken to reproduce the issue? 
Install CKAN 2.7.0 on CENTOS with Solr 6.5 and Apache with wsgi script. Install datastore and datapusher then migrate a database over from an older CKAN. After that try to access the resource.

**Comment by amercader** [comment]
We'll need some more details. Can you paste the full stack trace for the ValidationError?

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
