### ISSUE TITLE
2.7.0 Dataproxy returned an error

### ISSUE THREAD

**Issue by Invis1988** [ckan/ckan#3874]
### CKAN Version if known (or site URL)
2.7.0

### Please describe the expected behaviour
Dataproxy should display data

### Please describe the actual behaviour
Dataproxy is giving an error 
Could not load view: DataProxy returned an error (Data transformation failed. error: An error occured while connecting to the server: Unable to connect to server at URL: http://10.142.3.102/dataset/14a24193-c9e0-41bc-8a02-c5adf37443b7/resource/d9b828f8-ddba-4bf9-b977-13d204d5c4e0/download/ckanrequirements.xlsx)
When using debug mode it is stating that there is an "invalid query" which leads me to believe it is a datastore error.
### What steps can be taken to reproduce the issue? 
I'm using CentOS 7 with Solr 6.5, CKAN 2.7.0, Apache 2.4.X and mod_wsgi. Solr reports deprecated code but it's just warnings and is working. I am able to download the files but dataproxy can not preview them.

**Comment by mattfullerton** [comment]
This question belongs on the mailing list (https://lists.okfn.org/mailman/listinfo/ckan-dev) or on Stack Overflow (https://stackoverflow.com/questions/tagged/ckan), as I'm fairly sure it isn't a bug.

To quickly try and address it: Dataproxy is an external service that is used as a fallback when the data is not in CKAN's datastore. Dataproxy needs to be able to see that link, external to your site. I cannot access the link you sent, so Dataproxy won't be able to see it either.

You mention a "datastore" error. Did you set up the datastore? If the problem is actually that the data isn't going into the datastore successfully, then you need to address that and not worry about the dataproxy. Again though, if its not a world-accessible link, it could happen that datapusher has problems accessing it. You, on your browser, can access the link, but that doesn't tell us for sure whether the CKAN/datapusher internally can access it. This you could check on the command line with wget or curl. But I may be barking up the wrong tree here if for example datastore isn't even active.

**Comment by amercader** [comment]
As @mattfullerton mentioned please send your support requests to the mailing list or stack overflow.  http://10.142.3.102 is an internal URL, try and set up the DataStore and avoid DataProxy entirely. Cheers.
