### ISSUE TITLE
In 2.7.1 Portal Stats return zero and featured groups return with no datasets even if user belongs to organization

### ISSUE THREAD

**Issue by qlands** [ckan/ckan#3892]
CKAN version: 2.7.2

### Please describe the expected behavior
Scenario:
a. Organization A has only two datasets both private
b. User B is a member of organization A
c. 1 dataset of A is attached to Group C
c. User B logins and goes to home
d. If user B is a member of organization A then Portal stats should return 2 datasets and featured group C should have 1 dataset.

### Please describe the actual behavior
Portal stats return zero datasets and featured group C return no datasets. However featured organization has two datasets

### What steps can be taken to reproduce the issue? 
Reproduced in all cases

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
