### ISSUE TITLE
Atom feeds on groups do not function

### ISSUE THREAD

**Issue by camfindlay** [ckan/ckan#3895]
### CKAN Version if known (or site URL)
Seen in both 2.6.0 and 2.6.4 - https://demo.ckan.org/group/data-explorer

### Please describe the expected behaviour
I expect the atom feeds for groups to display xml of the recent additions and changes to datasets in that group.

This refers the URLs in the 'alternative' metadata tags on each group page.

![screen shot 2017-11-01 at 10 46 34 am](https://user-images.githubusercontent.com/367847/32250575-f9a1c064-bef1-11e7-98b1-b6a71bc370ca.png)

### Please describe the actual behaviour
Visiting these URLs returns no entries or irrelevant results. The revision list is also missing an id.

### What steps can be taken to reproduce the issue? 
Go to any CKAN group, `inspect` the head source and follow the 2 alternative atom links:

For example:
- https://demo.ckan.org/feeds/group/data-explorer.atom
- https://demo.ckan.org/revision/list?days=1&format=atom

We know the revision list is being deprecated however think having feeds like this is useful to post rss/atom based email notifications etc.

**Comment by wardi** [comment]
@camfindlay do you have time to take a look at this? We should be linking to the activities instead of the revisions IIUC.

**Comment by kmbn** [comment]
We decided to close old issues that are not actively worked on so that we can focus our effort and attention on issues affecting the current versions of CKAN.

If this issue is still affecting the version of CKAN you're working with now, please feel free to comment or reopen the issue.

If you do reopen this issue, please update it with new details. One reason it might not have been resolved in the past is that it wasn't clear how a contributor could address the issue.
