### ISSUE TITLE
datepicker

### ISSUE THREAD

**Issue by Helios06** [ckan/ckan#4134]
### CKAN Version if known (or site URL)
in CKAN 2.7 i cannot use jquery-ui datepicker in my javascript files anymore, it says that datepicker is not a function. i could in CKAN 2.6

### Please describe the expected behaviour
i expect a datepicker to work

### Please describe the actual behaviour
ckan says "datepicker is not a function"

**Comment by gocemitevski** [comment]
@Helios06 this usually means that `jquery-ui-datepicker` is loaded before `jquery`.

**Comment by tino097** [comment]
@Helios06 as i can see, this issue is related to the extension where the component is used. 

To minimize the number of issues on this repo we encourage you to submit support requests like this one to the ckan-dev mailing list or the #ckan tag on SlackOverflow.

You can also try on the #ckan IRC channel on freenode, where other developers may be able to help you.

Thanks!
