### ISSUE TITLE
Create concurrent resources for a dataset

### ISSUE THREAD

**Issue by klikstermkd** [ckan/ckan#4217]
### CKAN Version if known (or site URL)
Tested on CKAN 2.6, 2.7 and 2.8.

### Please describe the expected behaviour
If for example 10 resources are created concurrently for 1 dataset through the REST API using the action `resource_create`, all resources should be created and have the field `state` set to `active`.

### Please describe the actual behaviour
If for example 10 resources are created concurrently for 1 dataset through the REST API using the action `resource_create`, all resources are created in the db, but only half of those have the field `state` set to `active`, the rest have the field `state` set to `deleted`.

### What steps can be taken to reproduce the issue? 
I created a test script to reproduce the issue https://repl.it/@klikster/ImpassionedOptimisticSigns

10 resources are created concurrently using Python's multithreaded feature. The `ckanapi` Python package is used to create the resource in CKAN. In the script I am using CKAN's demo portal. Just add your API key and create an empty dataset and put it's name in the script.

After the script has finished, check the dataset's page. Only 5 resources will be created. The rest are also created but hidden in the UI because its `state` field is set to `deleted`. I used a local CKAN instance to test this.

In the CKAN's codebase, I found this code which may be the culprit for the problem https://github.com/ckan/ckan/blob/master/ckan/lib/dictization/model_save.py#L89

**Comment by wardi** [comment]
in general it's not safe to update multiple resources on a dataset concurrently because `resource_create` is calling `package_update` which validates all dataset metadata fields and re-writes all fields, and there's no locking or enforced ordering on dataset updates implemented.

The client approach I've taken with ckanapi is to use `package_update` for all metadata including resource fields, then `resource_patch` (one at a time) if I need to upload files for any of the resources.

@klikstermkd if you have some time to improve the `resource_create` implementation so that it can support concurrent resource creation, that's very welcome!

The small change you're suggesting won't solve all the issues, but we could look at implementing `resource_create` and `resource_update` without re-writing all dataset metadata fields. We can discuss loosening the validation requirements so that resource fields are validated separately and could be updated without calling package_update. We'll have to be careful about breaking extensions with custom validation. Or maybe there's another approach?

**Comment by rp-21** [comment]
Even in your case since all are getting added in dataset but some are in deleted state.
Run a seperate db query to update the state to active and then using paster rebuild-index rebuild the index vola all your datasets will be active.
A few extra steps is a small price to pay for depending on ckan.

Actually ckan should change this logic of indexing package and resources combinely for every resource update to package and resources updating and indexing individually.

This flow design must be adapted to avail concurrency.

**Comment by klikstermkd** [comment]
The script I posted is part of a real project I am working on, which does not have access to the CKAN server, so it only communicates with it through the CKAN API.

As a temporary solution, I am using Python's `Lock` feature to only allow one thread at a time to create a resource, and once it's done release the lock and allow other threads to continue. This of course is not that fast since it is synchronous, but it does work until a solution is found for CKAN's core implementation.

**Comment by rp-21** [comment]
cool, although even if you run as multi-threaded.

mark the datasets/resources active from postgresql tools pgadmin or so.
UPDATE <resource/package> SET state='active' WHERE <Your Condition to pick recently added ones>

Then run the rebuild index command from ckan's virtual-env folder.
paster --plugin=ckan search-index rebuild --config=/etc/ckan/default/production.ini

This works.

**Comment by klikstermkd** [comment]
@rp-21 As I said above, I don't have access to the database of the CKAN server.

**Comment by wardi** [comment]
#4618 covers this case and would allow concurrent resource_create (and creating all resources as part of the same package_update call)
