### ISSUE TITLE
Add Logo as a Link path issue

### ISSUE THREAD

**Issue by Engerrs** [ckan/ckan#4337]
### CKAN Version
2.7

### Expected behaviour
When admin set logo using Link button and paste there path for local image (/images/logo.png), logo will appear.

### Actual behaviour
When setting path that not consist 'http' at the start of url is not shown.

As I can see from code the handles this stuff, there is a [statement](https://github.com/ckan/ckan/blob/ckan-2.7.4/ckan/logic/action/update.py#L1276) that modify URLs without 'http', because it thinks that we uploaded them.
In this case, I guess it would be great to have some information for this field that describes which Links can be provided and make some validation, so users cannot set such URLs in future.

**Comment by tino097** [comment]
#3656 should get fix for this

**Comment by smotornyuk** [comment]
Yep, for >=2.8 there is client-side validation for URLs, so you won't be able to specify relative URLs. As for older versions, the placeholder of this field implies that you should use full address and attempts to use local URLs is kind of hack :) So, you don't need additional information about supported types of links, because only full links are officially supported
