### ISSUE TITLE
Greedy Default Routes Blocking OPTIONS

### ISSUE THREAD

**Issue by TkTech** [ckan/ckan#4393]
A greedy route prevents mapping your own OPTIONS handlers when required, such as for tus.io support or 3rd party middleware integrations.

https://github.com/ckan/ckan/blob/master/ckan/config/routing.py#L102

Likewise, the forced redirection of URLs ending in `/` should probably be removed unless there's a good reason to keep it around, it's definitely incorrect default behaviour. Correct behaviour would be the default of 404ing.

https://github.com/ckan/ckan/blob/master/ckan/config/routing.py#L184

@amercader do you happen to recall why these two rules were added?

Affects all versions.

**Comment by amercader** [comment]
The first route was added because Pylons was returning the body of the `GET` response when requesting `OPTIONS`, so a catch-all route was added, pointing to a view function that just returns [an empty response](https://github.com/ckan/ckan/blob/master/ckan/controllers/home.py#L97:L99). Flask handles this automatically (supporting the `OPTIONS` request and returning an empty response), and all significant routes have been now migrated to Flask on master, so I think it's safe to remove it.

The second one is a bit more tricky as it might impact existing URLs and resources. The default on [Flask](http://werkzeug.pocoo.org/docs/0.14/routing/#rule-format) and Django is the opposite of what we are enforcing now (non-slash URLs get redirected to slash-URLs unless you have `strict_slashes=False`). Even if in theory it would make sense to align with that, given that we have been enforcing the opposite for so long I'm reluctant to change this behavior for now. We'll have to decide for sure when we remove all Pylons routing for good, but my vote goes to leave as it is now.

The route immediately below allows to render arbitrary templates and should also be removed. See #4397

**Comment by TkTech** [comment]
This has been resolved!
