### ISSUE TITLE
Old permissions if package_show redirects to a different package

### ISSUE THREAD

**Issue by frafra** [ckan/ckan#4653]
What happens if `package_show` returns a different package? That what happens with ex`ckanext-datasetversions`: the original version uses a private/hidden dataset tracking the versioned public datasets using relations. This could create issues to CKAN, because in order to determine if a user should access to a resource, it checks if the user has access to the original package.

My workaround is to change the context in `package_show` adding this line:
```python
context['package'] = model.Package.get(package['name'])
````

I am not sure if CKAN should override the `context['package']` or just specifying that `package_show` should not be used to access to a different package and suggest a different solution (a redirect could work, but users would see a different URL).

Related pull request: https://github.com/aptivate/ckanext-datasetversions/pull/13

**Comment by amercader** [comment]
@frafra I'm not sure I understand. I don't think there is a general use case for "What happens if `package_show` returns a different package". It should always return the dataset specified by the id provided. If ckanext-datasetversions or another extension overrides this default behaviour to implement versioning it would seem a better approach to take this into account extending `package_show` or having a separate dedicated action to handle requests as needed.

I'm going to close this but please feel free to reopen if you think that it is an actual issue with ckan core or I missed something

**Comment by frafra** [comment]
Thank you, so I suppose I should fill a bug against `ckanext-datasetversions` that is not following the convention.
