### ISSUE TITLE
Described "actions" template block does not exist

### ISSUE THREAD

**Issue by tobinus** [ckan/ckan#4743]
The [docs] describe blocks that are available to template designers who extend "page.html", which I'm doing as a part of developing an extension. Among those is a block that I tried to use, called "actions". However, nothing changed when I used it. When I tried to search for it here on GitHub, nothing relevant seemed to show up, and I could not find it in `page.html` either.

The way I see it, there are two possible explanations:
* The documentation is right, so the `actions` block should be implemented
* The implementation is right, so the description of the `actions` block should be removed from the documentation

I have no idea what the block was supposed to make possible in the first place, so I'm fine either way. I'll just add a button inside of my `primary_content` block. I just thought I would try it out, since it seemed relevant. Reporting this so future template designers won't need to stumble across this oddity :)

[docs]: https://docs.ckan.org/en/2.8/contributing/frontend/template-blocks.html#actions

### CKAN Version if known (or site URL)
2.8.2

### Please describe the expected behaviour
I expect that if a feature (the `actions` template block, in this case) is described in the documentation, it works as described. So the `actions` block should either work, or not be advertised in the documentation.

### Please describe the actual behaviour
Overriding the `actions` block does not change anything in the generated HTML, despite it being advertised in the documentation.

### What steps can be taken to reproduce the issue? 
1. Create a new route or something similar that renders a custom template
2. Create a new template that `{% extends "page.html" %}`
3. Try to use the `actions` block:

   ```jinja2
   {% block actions %}
       <a class="btn" href="http://example.com">Go to example.com</a>
   {% endblock %}
   ```
4. After restarting CKAN, observe that the link does not appear anywhere (alternatively, search the generated HTML for the link).

**Comment by tobinus** [comment]
I have not checked whether this is the case for any other blocks described on the same page (though I'm using `title` and `primary_content` successfully) so it might be a good idea to check out the other blocks as well.

**Comment by boykoc** [comment]
@tobinus possibly a good candidate to make a PR to update the docs you referenced.

I did a quick search and found that the [documentation is from 7 years ago](https://github.com/ckan/ckan/blame/b9e45e2723d4abd70fa72b16ec4a0bebc795c56b/doc/contributing/frontend/template-blocks.rst#L67) for that line.  It also seems this block is only on some pages, I could only find it on [this template](https://github.com/ckan/ckan/blob/b9e45e2723d4abd70fa72b16ec4a0bebc795c56b/ckan/templates/user/logout_first.html#L6).

Looks like this block was removed from this [template awhile ago](https://github.com/ckan/ckan/commit/25cdea387018486791b66fad9bce282b2dd2a65f#diff-3a3c92fefd91654892ad323c0935035c).

So, you're not able to override the block because it doesn't exist in the template anymore.

**Comment by amercader** [comment]
@tobinus it would be great if you could submit a PR updating the docs, thanks!

**Comment by boykoc** [comment]
@tobinus I'm happy to submit if don't have time.

**Comment by tobinus** [comment]
I don't have time, so it would be nice if you or someone else could help with that :)
