### ISSUE TITLE
Could I assign a custom id via api `resource_create`

### ISSUE THREAD

**Issue by KinoLien** [ckan/ckan#4753]
### CKAN Version if known (or site URL)
2.8.2

### Please describe the expected behaviour
Assign a custom id via api `resource_create` just like `package_create` can be assigned `name` field, and the url would like `/dataset/foo/resource/bar`.

### Please describe the actual behaviour
Only get the auto-generated id.

--
Or other alternative ways to do that? thanks.

**Comment by smotornyuk** [comment]
In case of dataset, the most general way of obtaining name for URL is converting title to lower case and removal of all 'unsafe' characters. It works for datasets, because each dataset represent quite unique metadata. In rare cases user is able to manually set final name(URL) for dataset using edit form. 
I don't think it will work for resources - it's just faceless data. Quite often you'll have resource with the same name(like `Report`, `Data`, `Quality Statement`) almost for every dataset. Thus, resource's name cannot be used as unique identifyed. Adding an ability of create user-friendly url chunk for url will add additional mandatory field, that won't anyhow improve quality of data, neither will increase value of data(remember, dataset is the first-class citizen, resource in the same time is just some secondary data).  If this field will be optional, we'll increase amount of conditions in code, that usually ends up in a lot of problems. using some default value won't work either, because, for example, setting resource_id as default url may create problem, when data custodian removes an old resource, creates a new one(with different id) and then assings id of removed resource as a url of the new one, for persistent urls. In a no time you won't understand what is going here.

for your portal, i suggest adding new URL rule via `before_map` hook, that will replace original URL for resource page and will try to locate resource by name with logic you are considering sane for this case or fallback to native behavior.

**Comment by KinoLien** [comment]
Alright, I would try the method, thanks.
