### ISSUE TITLE
 Apache process is terminated by high memory usage of ckan

### ISSUE THREAD

**Issue by iamarnavgarg** [ckan/ckan#4939]
### CKAN Version if known (or site URL)
2.7.2

### Please describe the actual behavior
I have an apache web server(v2.4) + ckan (v2.7.2) running in a docker container. 
In our scenario, Ckan is being hit with large number of requests at certain intervals (like 10 requests/sec). Then after a certain period of time, the memory consumption tends to increase towards it's threshold value. 

At a certain time, if we access the home page of ckan at https://url-address/ckan with large number of request, the memory usage of the Apache process keeps on increasing and ultimately the process crashes and does not work properly.

(NOTE: ckan is mounted on /ckan root path )

As a quick remedy for this, restarting the docker container reduces the memory usage.

My concern is that is there any set of conditions/parameters in CKAN or Apache that needs to be taken care of, to prevent this behavior? What is the threshold values to process these requests? Do I have to limit the no. of requests to Ckan below its threshold value so that it does not crashes?

**Comment by smotornyuk** [comment]
As far as I know, there is no 'suggested' configuration. Memory usage highly depends on module usage, so it's almost impossible to tell some concrete numbers that may be used as bounds for Apache. So, for each particular portal and hardware, you need to manually check peak load and configure web-server according to this. 

In addition, it worth mentioning, that currently, CKAN has pretty weak cache implementation, so you can drastically improve your portal capabilities using some cache engine, like Varnish, so that in most cases(like a hit on the homepage), python will still untouched and response will be completely static. Unfortunately, I never tried such setup and have no examples of configuration.

**Comment by iamarnavgarg** [comment]
Hi @smotornyuk 

I searched for this behavior(Apache memory usage) and found this could be improved by following ways:

1.  Lower the limit of number of simultaneous connections/requests, as Apache creates a new process for every new request always.
For example, it can be done by tweaking apache parameters in "apache2.conf" file(location: /etc/apache2/apache2.conf) such as KeepAlive, KeepAliveTimeout, TimeOut etc. 

2. Reduce the Apache's  log level so that Apache would use less memory for generating logs.
For more reference: https://bobcares.com/blog/apache-high-memory-usage/

3. One important parameter in Apache: MaxConnectionsPerChild
https://httpd.apache.org/docs/current/mod/mpm_common.html#page-header 
(The MaxConnectionsPerChild directive sets the limit on the number of connections that an individual child server process will handle.)
This is set as 0 in my ./mods-enabled/mpm_event.conf file 

Could you please suggest something on this?

**Comment by wardi** [comment]
setting MaxConnectionsPerChild to 0 might mean unlimited, right? If you have a memory leak in an extension or if you're running with SQL logging turned on you will run out of memory.

Either way this is more of a support/configuration issue, please try asking on our gitter chat or on stackoverflow, we use the ticket system here for issues with the ckan repository itself.
