### ISSUE TITLE
i18n: Multiline translation strings not translated

### ISSUE THREAD

**Issue by bellisk** [ckan/ckan#4968]
### CKAN Version if known (or site URL)
2.8.3

### Please describe the expected behaviour
All translated strings in the CKAN templates should be translatable into all available languages.

### Please describe the actual behaviour
Multi-line translated strings in the CKAN templates that are specified with `{% trans %}` tags are not translated.

e.g., this works: `{{ _('Update Member') }}`
This works: `{% trans %}Update Member{% endtrans %}`

This doesn't work, and the text remains in English when a different language is selected:
```
{% trans %}
    Some really long string that is so long
    we put it on multiple lines in the template.
{% endtrans %}
```

### What steps can be taken to reproduce the issue? 
Bring up a new CKAN instance. Go to the Organizations page and see that the help text in the left column (under "What are Organizations?") does not change when a different language is selected.

**Comment by amercader** [comment]
@bellisk thanks a lot for the report.
I can reproduce this in master: https://master.ckan.org/ca/organization/
Are you sure this happens on 2.8.3? Seems to work fine in here: https://beta.ckan.org/ca/organization

**Comment by wardi** [comment]
I've definitely had trouble with multiline translations in my extensions being picky about not having the exact right surrounding white-space (I need to use the exact right combinations of spaces and newline characters in my .po files) I thought the fuzzy setting was supposed to make that unnecessary.

**Comment by bellisk** [comment]
@amercader Sorry, I checked again and we seem to be using master; the last commit in our ckan/ckan repository is https://github.com/ckan/ckan/commit/b6298333453650cd9dbb3f5d3566da719804ecca

**Comment by amercader** [comment]
@wardi @bellisk I investigated a bit and this seems related to the upgrade to Jinja2 2.10, particularly:
https://jinja.palletsprojects.com/en/2.10.x/extensions/#whitespace-trimming

I haven't tried yet to pass this as I'm not sure where and how to do so (I imagine wherever we are initializing our Jinja2 environment)

**Comment by wardi** [comment]
interesting, so we need to either turn this off or remove all the whitespace from the start/end of the po strings?

Sounds like kind of a nice default TBH

**Comment by iamarnavgarg** [comment]
Hi @amercader @wardi do we need to re-compile or rebuild ckan again after removing the white spaces from ckan.po  file?

**Comment by iamarnavgarg** [comment]
Hi @amercader @wardi do we need to re-compile or rebuild ckan again after removing the white spaces from ckan.po file? Because simply changing and re-executing CKAN doesn't reflects the changes?

I had followed this [po-files](https://docs.ckan.org/en/ckan-2.7.3/contributing/i18n.html#create-a-po-file-for-your-language) document.

**Comment by clauded** [comment]
I have the same problem here with 2.8.3. 

For example, the string "Your profile lets other CKAN users know about who you are and what you do." is not translated in French. I tried to add/remove white spaces to the english string in the po file (and recompile with `python setup.py compile_catalog -f --locale fr`) without success.

Is there a workaround while waiting for an official fix?

**Comment by iamarnavgarg** [comment]
Hi @amercader , I had analyzed and investigated the issue and found that we need to change the ckan.po files present in /i18n location. For eg: in /ca/LC_messages/ckan.po file, we need to remove the unnecessary white-line spaces to make this work. I am looking further into this.

Ref docs: [ckan.po-setup](https://docs.ckan.org/en/ckan-2.7.3/contributing/i18n.html#manual-setup)

**Comment by clauded** [comment]
Any progress on this? Is there a workaround to make this work?

**Comment by smotornyuk** [comment]
@amercader , sorry for bothering you, but in our community you are translation-guru, so it's unavoidable.
It seems, that setting `ckan` message extractor to the `babel_extractor` from jinja2 do the thing.
```diff
diff --git a/setup.py b/setup.py
index adec5e76b..4eb6ecda5 100644
--- a/setup.py
+++ b/setup.py
@@ -186,7 +186,7 @@ entry_points = {
         'legacy_mock_search_plugin = ckan.tests.legacy.logic.test_action:MockPackageSearchPlugin',
     ],
     'babel.extractors': [
-        'ckan = ckan.lib.extract:extract_ckan',
+        'ckan = jinja2.ext:babel_extract',
     ],
 }
 ```
And here few questions:
* do we need this `extract_ckan` function? It using [jinja2_cleaner](https://github.com/ckan/ckan/blob/master/ckan/lib/extract.py#L41) - i.e we already relying on jinja2.
* After updating the extractor, you need to reinstall CKAN (i.e. `pip install -e .` ) and run `extract_messages`. But this will only update main `.pot` file. As I understand, if we'll upload this file to transifex, all existing multi-line translations would be lost? Yes, they aren't working anyway, but is there any way to copy existing translations from old multiline message into new multiline messages(I mean, `msgid` in `po` file is different, so transifex cannot do it automatically)

**Comment by Chealer** [comment]
The behavior we're seeing in 2.8.3 as well as 2.8.4 is fairly mystifying. In some cases, translation is whitespace-hypersensitive, as described by @wardi . In other cases, translation is whitespace-sensibly-sensitive. The sensitivity level does not depend on the string's content - it depends on where it occurs.

In one Jinja template, a certain translation matches loosely. In another Jinja template, a translation is ignored due to strict matching. I do not know if it's the file which matters or where in the file the string occurs, but I did test that interchanging both strings, the effective translation stops translating, and the ignored translation starts translating.

I tested this using ckanext\datastore\templates\ajax_snippets\api_info.html (tricky) and ckan\templates\organization\snippets\helper.html (loose). For the tricky template's translation to be taken into account, it needs to be written as exactly
`msgid "\n          Further information in the <a\n            href=\"http://docs.ckan.org/en/latest/maintaining/datastore.html\" target=\"_blank\">main\n            CKAN Data API and DataStore documentation</a>.</p>\n          "`
As I write this, I wonder if tricky places could be those outside the core (extensions).

That being said, such a backport would be delicate, and it should be done early in a patch release's development, if at all.

**Comment by Chealer** [comment]
I suggest to consider "the issue" tracked here as 2:

1. whitespace "hypersensitivity" in some cases
2. English strings in the po template (.pot) file assuming less sensitivity, using sometimes different whitespace

As I wrote, work on the first issue for 2.8 is risky, but the second issue can be considered as a bug by developers. It may be worth it to change untranslated strings to precisely match English strings.
