### ISSUE TITLE
Overriding package controller

### ISSUE THREAD

**Issue by benbaido** [ckan/ckan#4983]
### CKAN Version if known (or site URL)
2.8.1

### Please describe the expected behaviour
Overriding the /dataset/new post endpoint would change the route the save dataset button goes to but it doesn't.
What I want to do is change which controller the save button routes to. I don't want it to go to the ckan.lib.base file. I want it to go to my controller.

### Please describe the actual behaviour
The page goes to the same endpoint and is not overridden.

### What steps can be taken to reproduce the issue? 
My Plugin.py
```
    def before_map(self, map_):
        my_controller= 'ckanext.myextension.controller:MyController'
        map_.connect(
             'save',
            '/dataset/new',
            controller=my_controller,
            action='new_dataset',
            conditions=dict(method=['POST']),
        )
        return map_

    def after_map(self, map_):
        my_controller= 'ckanext.myextension.controller:MyController'

        map_.connect(
            'save',
            '/dataset/new',
            controller=my_controller,
            action='new_dataset',
            conditions=dict(method=['POST']),
        )

        return map_
```

**Comment by usingsky** [comment]
@benbaido 
I had a similar issue. In my experience, ckan has the following routing priorities

>Order of precedence if more than one app can handle a url:
    Flask Extension > Pylons Extension > Flask Core > Pylons Core

And "/dataset/new" is routed to Flask Core(2.9.x) or Pylons Core(2.8.x)

I think there are two solutions. Hope this helps

1. overriding blueprint instead of pylons (If you plan to update ckan to 2.9.x)
refer to [get_blueprint](https://docs.ckan.org/en/latest/extensions/plugin-interfaces.html?highlight=get_blueprint#ckan.plugins.interfaces.IBlueprint)


2. set ckan_core as False (If you want to continue using pylons)
map_.connect(
            'save',
            '/dataset/new',
            controller=my_controller,
            action='new_dataset',
            conditions=dict(method=['POST', 'GET']),
            **ckan_core=False**
        )

**Comment by usingsky** [comment]
@smotornyuk 
I have a question about the above.
`ckan_core = '' or ckan_core_ = False or ckan_core = True` behave the same.
This is because ckan only checks for the existence of the ckan_core attribute. 


https://github.com/ckan/ckan/blob/1e70c730e131a0b53a5f42e815d5f710957c9fa1/ckan/config/routing.py#L47-L51

https://github.com/ckan/ckan/blob/1e70c730e131a0b53a5f42e815d5f710957c9fa1/ckan/config/routing.py#L140-L143
