### ISSUE TITLE
Adding group during creating dataset

### ISSUE THREAD

**Issue by MandanaMoshref** [ckan/ckan#4985]
### CKAN Version if known (or site URL)
2.8

### Please describe the expected behaviour
I would like to add additional field OR stage where the user can add the group as a compulsory metadata item to the dataset. 

### Please describe the actual behaviour
At the moment a user can decide to whether add a group to the dataset or not (assuming with the given right to do so). But in my application adding at least 2 groups should be compulsory. 
My expectation is that It is not possible to add an additional field to the dataset metadata while creating the dataset, as the group should be added after creating the dataset. So, I decided to add it as the stage 3.

### What are my issues? 
1. First of all, is it possible to add the a field for adding group (e.g. using ckanext schema) to the dataset metadata while creating a dataset? or as I already wrote it should happen after creating the dataset?

2. Does it make sense to do this as the stage 3? I am badly struggling to figure out how this works but no success so far. Does it need a controller? or helper would be enough?

I appreciate your advice in advance
Mani

**Comment by boykoc** [comment]
Somewhat related to #4901

**Comment by smotornyuk** [comment]
And for a basic solution, you can check [this extension](https://github.com/datagovau/ckanext-agls/blob/master/ckanext/agls/templates/package/snippets/package_basic_fields.html#L185)

Generally, dataset already has `groups` key, but it a little bit tricky because of validation logic. While the addition of 3rd step may turn into hell, updating only the dataset form may become quite straightforward, thou.
What you need to do for assigning groups `xxx` and `yyy` to the package initially, is editing package form(like in link above) by adding these two fields:
```
<input name="groups__0__id" value="xxx" type="checkbox" checked/>
<input name="groups__1__id" value="yyy" type="checkbox" checked/>
```

The main trick here - names of the new fields. They MUST follow the format `groups__INDEX__id`, where INDEX is starting with 0 and increasing by 1 with every group. Note that the index is surrouned by double underscore from each side.

**Comment by MandanaMoshref** [comment]
@smotornyuk  Thank you very much. You saved my life. 
Actually, I want to use the group from the dropdown list. The extension you shared helped me finally to manage it.

I have one more question...
I have a hierarchy in my group (this works the same as the ckanext_hirarchy but for groups). Is there any possibility that I have e.g. 2 fields and each call the sub-groups of the corresponding parent group. I mean imagine "XXX" is one parent with 4 sub-groups and "YYY" another parent with 5 subgroups.

The aim is that in my metadata two categories of groups should be chosen as obligatory attributes for the dataset but they are not tags or something similar but rather fixed values with similar function to ckan groups.

Anyway again many thanks for your great help.

Best regards
Mani

**Comment by MandanaMoshref** [comment]
Ok I have an update:

Thanks to the help and advice from @smotornyuk I could understand how adding a new field directly in the dataset metadata works.

The steps I have done to add three new fields for the user to add the groups are as following:
1. I already adapted the ckanext-hirarchy which is for organisation for groups. It means I have groups managed under three main categories.
The prepose is that each dataset has to have at least two groups as mandatory inputs. It is in order to improve the searchability of datasets.
2. The current functionality in ckan is that after creating a dataset, a user can add as many groups as possible to a dataset. This is optional, however I want to make it obligatory, hence I decided to have this step as fields in my metadata.
3. I added a helper function to my ckanext-group-hirarchy which calls the children of a parent (main group):
`def get_allowable_children_groups_g(group_id):
    if group_id:
        group = model.Group.get(group_id)
        allowable_parent_groups = group.get_children_group_hierarchy(type='group')
	a = group.groups_allowed_to_be_its_parent(type='group')
    else:
        allowable_parent_groups = model.Group.all(
            group_type='group')
    return allowable_parent_groups`

4. in the ckan, in the html template "[package_basic_fields.html](https://github.com/ckan/ckan/blob/master/ckan/templates/package/snippets/package_basic_fields.html)", I added these lines:
`
    <div class="control-group control-full">

        <label class="control-label" for="field-group"><span title="This field is required"
                                                             class="control-required">*</span>Add group</label>

        <label class="control-label" for="field-group"><span title="This field is required"
                                                             class="control-required">* </span>Field 1</label>
        <div class="controls">
            <select id="field-group" name="groups__0__id" data-module="autocomplete">
                <option value="">Please Select</option>

                {% for group in h.get_allowable_children_groups_g('group1')  %}
                    <option value="{{ group.id }}">{{ group.title }}</option>
                {% endfor %}
            </select>
        </div>
<br/>
        <label class="control-label" for="field-group"><span title="This field is required"
                                                             class="control-required">* </span>Field 2</label>
        <div class="controls">
            <select id="field-group" name="groups__1__id" data-module="autocomplete">
                <option value="">Please Select</option>

                {% for group in h.get_allowable_children_groups_g('group2')  %}
                    <option value="{{ group.id }}">{{ group.title }}</option>
                {% endfor %}
            </select>
        </div>
<br/>
        <label class="control-label" for="field-group"><span title="This field is required"
                                                             class="control-required"></span>Group3</label>
        <div class="controls">
            <select id="field-group" name="groups__2__id" data-module="autocomplete">
                <option value="">Please Select</option>

                {% for group in h.get_allowable_children_groups_g('group3')  %}
                    <option value="{{ group.id }}">{{ group.title }}</option>
                {% endfor %}
            </select>
        </div>
</div>`

Please note***: This condition is only to assume the user has full right permission for all groups.

I know this is a dirty solution, but still I thinkt it could help if anyone has similar difficulty as mine.
I close this issue as it is solved for me, but I still see it as an improvement for CKAN because I would rather like to have the possibility to add it as extra stage. And I believe this should be an option for the user.

Thanks
Mani

**Comment by smotornyuk** [comment]
I'm not sure, whether I've got the idea, but [here's](https://github.com/smotornyuk/ckanext-example_multi_group) some example of solving the mentioned problem from my point of view.

1. Let's imagine, that you have [two separate fields](https://github.com/smotornyuk/ckanext-example_multi_group/blob/master/ckanext/example_multi_group/plugin.py#L29-L71) and each of them only can be set to specified set of groups.
2. You have to make sure, that value if those fields always have the same structure. In my example, both of them can have multiple values, so I'm [converting single option](https://github.com/smotornyuk/ckanext-example_multi_group/blob/master/ckanext/example_multi_group/plugin.py#L33) into a list that contains the only value. Otherwise, I will get a string for single value and list for multiple values.
3. In addition, you want to [exclude possibility ](https://github.com/smotornyuk/ckanext-example_multi_group/blob/master/ckanext/example_multi_group/plugin.py#L34)of setting unacceptable group as value for each of field. For this reason you have [helper](https://github.com/smotornyuk/ckanext-example_multi_group/blob/master/ckanext/example_multi_group/plugin.py#L88), that returns set of groups that may be used for each of fields(in my case - `first` is a set of groups with name starting with letter `g` - they can be assigned to the first field and `second` is a set of groups with name starting with letter `e` - they can be assigned to the second field).
4. When user provides incorrect set of groups, you'll return [validation error](https://github.com/smotornyuk/ckanext-example_multi_group/blob/master/ckanext/example_multi_group/plugin.py#L106-L108). Otherwise, you'll [copy group ids](https://github.com/smotornyuk/ckanext-example_multi_group/blob/master/ckanext/example_multi_group/plugin.py#L109-L110) into `groups` field. In addition, you can completely strip custom field from `data` on this step, because it's already copied into `groups` and there is no sense in data duplication.
5. The only thing that is not handled here - excluding datasets from group. if you'll update dataset, providing different values for `first_level_groups` and `second_level_groups` fields, additional groups will be assigned to dataset, but old ones won't be excluded. If you want to fix this problem, try to create list of groups from the scratch, instead of [reusing existing list](https://github.com/smotornyuk/ckanext-example_multi_group/blob/master/ckanext/example_multi_group/plugin.py#L109)

I've used [multiple-select](https://github.com/smotornyuk/ckanext-example_multi_group/blob/master/ckanext/example_multi_group/templates/package/snippets/package_basic_fields.html#L18) with [custom macro](https://github.com/smotornyuk/ckanext-example_multi_group/blob/master/ckanext/example_multi_group/templates/package/snippets/package_basic_fields.html#L3) just as example, solution from ckanext-agls(one, that i mentioned in previous comment) can be used as well. 

Maybe, you can just install `example_multi_group` extesion on fresh CKAN installation, enable it by adding `example_multi_group` to plugins list, create few groups whose name starts with `g`(`group-1`, `group-2`) and few with `e`(`extra-group-1`, `extra-group-2`) and see, how it corresponds to your requirements?

**Comment by MandanaMoshref** [comment]
> I'm not sure, whether I've got the idea, but [here's](https://github.com/smotornyuk/ckanext-example_multi_group) some example of solving the mentioned problem from my point of view.
> 
> 1. Let's imagine, that you have [two separate fields](https://github.com/smotornyuk/ckanext-example_multi_group/blob/master/ckanext/example_multi_group/plugin.py#L29-L71) and each of them only can be set to specified set of groups.
> 2. You have to make sure, that value if those fields always have the same structure. In my example, both of them can have multiple values, so I'm [converting single option](https://github.com/smotornyuk/ckanext-example_multi_group/blob/master/ckanext/example_multi_group/plugin.py#L33) into a list that contains the only value. Otherwise, I will get a string for single value and list for multiple values.
> 3. In addition, you want to [exclude possibility ](https://github.com/smotornyuk/ckanext-example_multi_group/blob/master/ckanext/example_multi_group/plugin.py#L34)of setting unacceptable group as value for each of field. For this reason you have [helper](https://github.com/smotornyuk/ckanext-example_multi_group/blob/master/ckanext/example_multi_group/plugin.py#L88), that returns set of groups that may be used for each of fields(in my case - `first` is a set of groups with name starting with letter `g` - they can be assigned to the first field and `second` is a set of groups with name starting with letter `e` - they can be assigned to the second field).
> 4. When user provides incorrect set of groups, you'll return [validation error](https://github.com/smotornyuk/ckanext-example_multi_group/blob/master/ckanext/example_multi_group/plugin.py#L106-L108). Otherwise, you'll [copy group ids](https://github.com/smotornyuk/ckanext-example_multi_group/blob/master/ckanext/example_multi_group/plugin.py#L109-L110) into `groups` field. In addition, you can completely strip custom field from `data` on this step, because it's already copied into `groups` and there is no sense in data duplication.
> 5. The only thing that is not handled here - excluding datasets from group. if you'll update dataset, providing different values for `first_level_groups` and `second_level_groups` fields, additional groups will be assigned to dataset, but old ones won't be excluded. If you want to fix this problem, try to create list of groups from the scratch, instead of [reusing existing list](https://github.com/smotornyuk/ckanext-example_multi_group/blob/master/ckanext/example_multi_group/plugin.py#L109)
> 
> I've used [multiple-select](https://github.com/smotornyuk/ckanext-example_multi_group/blob/master/ckanext/example_multi_group/templates/package/snippets/package_basic_fields.html#L18) with [custom macro](https://github.com/smotornyuk/ckanext-example_multi_group/blob/master/ckanext/example_multi_group/templates/package/snippets/package_basic_fields.html#L3) just as example, solution from ckanext-agls(one, that i mentioned in previous comment) can be used as well.
> 
> Maybe, you can just install `example_multi_group` extesion on fresh CKAN installation, enable it by adding `example_multi_group` to plugins list, create few groups whose name starts with `g`(`group-1`, `group-2`) and few with `e`(`extra-group-1`, `extra-group-2`) and see, how it corresponds to your requirements?
> 
> PS i noticed your last comment after submitting this response, but as i see, both of us solved this problem in a quite similar manner)

Many thanks for this. I have learnt also from your approach.
