### ISSUE TITLE
metadata_modified content is misleading

### ISSUE THREAD

**Issue by Chealer** [ckan/ckan#5011]
In CKAN 2.4.1, the ckan.logic.action.get.package_show API function's result contains a "metadata_modified" field. When the dataset's metadata is modified, that timestamp is updated to the current time, unsurprisingly.

What is more surprising is that this timestamp is also updated when any of the dataset's resources is modified. This happens even if only the resource's content (the file) is modified.

There are 2 possible solutions here, depending on what CKAN was meant to do:
1. Either the metadata_modified field gets a non-misleading name matching the described behavior, such as "modified". Such a rename has not been done (in the master branch) so far.
2. Or this field's behavior is modified to a behavior which makes sense given its name. In that case, at least mere modifications to a resource's contents should not cause a modification of that field. I have not verified that such a change has not been done between CKAN 2.4.1 and 2.8.3.

Looking at this better, if the proper solution is #1, the result also contains a "metadata_created" field, which surely contains the dataset's creation time. Shouldn't both fields lose the "metadata"?

**Comment by wardi** [comment]
In ckan the package metadata (including dataset and resource resource metadata) is what is being referred to by "metadata_modified". It is the date that any fields within the dataset or its resources were last changed. Resources are considered part of the package because they are validated, stored and indexed together for searching.

If a file that was linked in a resource is modified there's no way for ckan to know, but if a new file is uploaded the reference to that new file (and its resource hash when using datapusher) are part of the metadata so the metadata_modified would be updated.

**Comment by Chealer** [comment]
Thank you wardi,
We do use DataPusher, but the only fields modified that I see are:
1. the dataset's metadata_modified
2. the resource's last_modified
3. the resource's revision_id (the id of the latest revision)

I'm not sure I consider adding a revision id as a metadata modification, but for sure, if both metadata_modified and last_modified are about metadata, it would be more consistent to name them the same.

**Comment by wardi** [comment]
datapusher updates the hash value on the resource when a new file is uploaded. last_modified is meant to refer to the last change of the resource itself. HTH

**Comment by Chealer** [comment]
It doesn't look like the "hash" field of resources is responsible, because in our CKAN 2.4.1, that field is the empty string. Unless it would be set to something, then cleared immediately after...
