### ISSUE TITLE
Search form validation

### ISSUE THREAD

**Issue by bohdanbobrowski** [ckan/ckan#5025]
### CKAN Version if known (or site URL)
CKAN 2.8.3

### Please describe the expected behaviour
When user enter incorrect search query (in dataset search form on organization page), search form should inform her/him that something is wrong with that.

### Please describe the actual behaviour
Currently CKAN web UI returns "An internal server error occurs" message... which many users found to be misleading.

### What steps can be taken to reproduce the issue? 
Go into random organization page and enter "and" into search field and press enter, url should be similar to that:
http://<instance address>/organization/<organization name>?q=AND&sort=score+desc%2C+metadata_modified+desc

**Comment by mutantsan** [comment]
Since Pysolr returns us a pretty clear description of the exception that occurred, we can use it to explain to the user why exactly this happened.

`u"Solr responded with an error (HTTP 400): [Reason: Can't determine a Sort Order (asc or desc) in sort spec 'score dessc, metadata_modified descs', pos=5]".
`
For now, the message "There was an error while searching. Please try again." is hard-coded in the template, what is definitely could be unclear for someone. However, the text of the exception itself needs refinement before being presented to the user. I would like to work on this issues.
