### ISSUE TITLE
Metadata modified date change behaviour

### ISSUE THREAD

**Issue by dottyz** [ckan/ckan#5058]
CKAN 2.8.2 (https://ckan0.cf.opendata.inter.prod-toronto.ca/)

On resources modifications (eg. create, delete, metadata updates) the metadata_modified date also updates on the package level. 

Is this the expected behaviour? If so, what would be the easiest way to separate the metadata modified date tracking between resources and packages? 

We would like to separate the two so that we can track when modifications to the packages are metadata only vs. data content only. Thanks in advance for the help.

**Comment by amercader** [comment]
Yes, that is the expected behaviour. Changes in resources are reflected in the dataset metadata_modified field.
I guess that one potential way of implementing what you want would be to override `resource_create`, `resource_update` and `resource_patch` to add a resource specific timestamp any time they are called.

Closing this as there isn't an actual issue with CKAN. If you want to discuss this further you can try the [ckan-dev mailing list](https://lists.okfn.org/mailman/listinfo/ckan-dev) or the [Gitter channel](https://gitter.im/ckan/chat).
Thanks!
