### ISSUE TITLE
Helper Methods Defined in Extension Not Available in Extension Test

### ISSUE THREAD

**Issue by thejuliekramer** [ckan/ckan#5087]
**Note:** Are you submitting a security related issue that could be a potential vulnerability? Please send it to security@ckan.org instead.

### CKAN Version if known (or site URL)

2.8

### Please describe the expected behaviour

When running a test for an extension the helpers registered via the plugin should be available when running tests.

`nosetests --ckan --with-pylons=test.ini ckanext/example_extension/tests`

### Please describe the actual behaviour

When running a test for an extension the helpers registered via the plugin are not available when running tests.
### What steps can be taken to reproduce the issue? 

Run a test from within extension that is reliant on a helper method defined in the extension.

Test example: https://github.com/thejuliekramer/ckanext-datagovtheme/blob/master/ckanext/datagovtheme/tests/test_datagovetheme.py#L23

Unavailable helper method: https://github.com/thejuliekramer/ckanext-datagovtheme/blob/master/ckanext/datagovtheme/helpers.py#L76

**Comment by amercader** [comment]
Hi @thejuliekramer, regarding the `HelperNotFound` exception the reason is because you have added it to the helpers.py module but not registered for CKAN to know about it. To do so you need to add a reference to it on the `ITemplateHelpers` [`get_helpers`](https://github.com/thejuliekramer/ckanext-datagovtheme/blob/master/ckanext/datagovtheme/plugin.py#L85) method, similarly to how the other ones are registered.

Some more pointers on loading plugins from the test. In general you need to make sure to unload it after the tests you've run are done, so it won't affect other tests down the line. Unless it will be used in a single test, you can add them on the `setup_class` method, and remove them on the `teardown_class` method:

```python
  class TestDatagovthemeServed():
      '''Tests for the ckanext.datagovtheme.plugin module.'''
  
      @classmethod
      def setup_class(cls):
          super(TestDatagovthemeServed, cls).setup_class()
          ckan.plugins.load('datagovtheme')

      @classmethod
      def teardown_class(cls):
          super(TestDatagovthemeServed, cls).teardown_class()
          ckan.plugins.unload('datagovtheme')

     def test_xx(self):

```

If you are extending `helpers.FunctionalTestBase` then you can use the `_load_plugins` property directly that will handle this for you:

```python
  class TestDatagovthemeServed(helpers.FunctionalTestBase):
      '''Tests for the ckanext.datagovtheme.plugin module.'''

     _load_plugins = ['datagovtheme']

     def test_xx(self):

```

But in your case, as you are writing tests for that particular plugin you will probably need to always have it loaded. So just add it to your [`test.ini`](https://github.com/thejuliekramer/ckanext-datagovtheme/blob/master/test.ini) file, alongside any other plugins that your extension will always require (like `geodatagov`):

```
[app:main]
use = config:../ckan/test-core.ini
ckan.plugins = datagovtheme geodatagov
ckanext.geodatagov.dynamic_menu.url_default = http://www.data.gov/app/plugins/datagov-custom/wp_download_links.php
```

Hope this helps
