### ISSUE TITLE
Migrate Datapusher and DataStore CLI commands to Click

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#5126]
Now that #5112 is merged, we can refactor the CLI commands for the datastore and datapusher extensions (`ckanext/datastore/cli.py` and `ckanext/datapusher/cli.py`) to use the new `IClick` interface rather than the old paster based one.

https://github.com/ckan/ckan/pull/5121 has some detail on how to implement this interface

**Comment by mutantsan** [comment]
Hi, I would like to work on it.

**Comment by amercader** [comment]
go for it @mutantsan !

**Comment by smotornyuk** [comment]
Note, that we already have those commands migrated as global groups in https://github.com/ckan/ckan/blob/master/ckan/cli/datastore.py and https://github.com/ckan/ckan/blob/master/ckan/cli/datapusher.py . So instead of full migration from paster commands, you need to put mentioned code into `IClick` of relevant extensions.

**Comment by amercader** [comment]
Thanks @smotornyuk, I had missed this. So it's probably better to move the cli modules to their own extensions and expose them via IClick right?

**Comment by smotornyuk** [comment]
Yep, absolutely agree.

**Comment by smotornyuk** [comment]
Solved by #5329
