### ISSUE TITLE
Wrong redirecting from custom dataset_type to dataset

### ISSUE THREAD

**Issue by MandanaMoshref** [ckan/ckan#5239]
I am using Ckan with many extensions. E.g. I use scheming and I only use a custom dataset type using ckanext_scheming. 
dataset_type: "datahub_resource"
### CKAN Version if known (or site URL)
2.8.0

### Please describe the expected behavior
I expect that when I am viewing or editing or creating my own dataset, in url I always see my dataset_type name.
e.g: https://myckan.com/en/datahub_resource/geodaten-v2

### Please describe the actual behavior
Although for viewing an already created dataset, when i click on the dataset, i see the name of my dataset_type in url. On the dataset view page, if I click on the tab: "Dataset", it surprisingly changes the url to the default "dataset"
e.g.:
instead of: https://myckan.com/en/datahub_resource/geodaten-v2
with click on dataset tab of a dataset i get:
-> https://myckan.com/en/dataset/geodaten-v2

### What steps can be taken to reproduce the issue? 
using ckan 2.8.0
and adding ckanext_schemming
create a schema in with another dataset_type similar to mine: datahub_resource

#### What I have found so far:
I assume this problem is from CKAN and not ckanext.
I have found this link as well:
https://techmemo.xyz/ckan/ckan/pull/5189
However, applying the same changes I receive errors (https://techmemo.xyz/ckan/ckan/pull/5189#issuecomment-590917809).
Is there any idea why I have this problem?

**Comment by smotornyuk** [comment]
I've added a comment to the #5189 and here the short summary:

1. If you are expecting, that you'll always be using/redirected to `PACKAGE_TYPE/url` after creating custom dataset type with ckanext-scheming - you are wrong. This `PACKAGE_TYPE` has sense only on the package creation stage so that CKAN can build a correct form for UI.
2. If you want to create a special package type, with custom redirects, logic,URLs, etc. - you have to create a custom controller and everything else that is required for your package type. Check [ckanext-showcase](https://github.com/ckan/ckanext-showcase) as reference.
3. If you want to use custom templates, actions, etc. - you should create a new dataset type using IDatasetForm.
4. ckanext-scheming - is just a convenient wrapper for base(and most frequent) case, when you only need a few different dataset types every of which has a custom set of fields/validators/display snippets. Currently, it doesn't provide anything else(custom URLs, ability to configure a completely different sets of templates depending on dataset type, etc).

So, it just works as expected. You are using incorrect tools. Instead, create custom package type from scratch(like in mentioned ckanext-showcase, or in ckanext-harvest)

**Comment by MandanaMoshref** [comment]
Thanks for the reply.
I close this issue as it seems was my misunderstanding and not an issue
