### ISSUE TITLE
beaker_cache table keeps growing

### ISSUE THREAD

**Issue by FuhuXia** [ckan/ckan#5294]
### CKAN Version if known (or site URL)
2.5.2 

### Please describe the expected behaviour
We use database to store beaker sessions. 
`beaker.session.type=ext:database`

The `beaker_cache` table in CKAN database keeps growing. There should be way to set the max age based on last accessed time and delete stale records in this table.

### Please describe the actual behaviour
`beaker_cache` is filled with years of records and grows to millions of rows. Eventually it starts to give 500 Internal Server Error.

### What steps can be taken to reproduce the issue? 
`SELECT * FROM beaker_cache ORDER BY accessed limit 1;`

**Comment by Zharktas** [comment]
This is a documented feature of beaker that it does not clear its sessions from backend https://beaker.readthedocs.io/en/latest/sessions.html#removing-expired-old-sessions and it is up to a developer to clear them.

One example from our instances can be seen here https://github.com/vrk-kpa/opendata/blob/b951a09c3ae5f0914f8cf265e79b4074caf40dd8/ansible/roles/ckan/templates/beaker_session_cleanup.sh.j2. This script is run on cron every day so that the cache table never grows too big.

**Comment by adborden** [comment]
If this is a required maintenance task, shouldn't it be documented in the CKAN docs? I didn't see it mentioned anywhere.

**Comment by Zharktas** [comment]
CKAN docs don't have anything about configuring beaker. The defaults are fine for the most cases, but when someone needs something more advanced features like database backend for multi instance setups, one should really read the beaker docs. It makes no sense to replicate them in CKAN docs.

And running session cleanup tasks are almost never required on default settings.

**Comment by adborden** [comment]
By default, doesn't beaker use file-based storage? And doesn't that still require maintenance of removing those files?

This might be a separate issue, but I feel like what CKAN considers "default" is really development and "advanced features" are really essential features for running a production CKAN instance. Would you suggest I open a new issue to capture documentation for running a multi-instance production CKAN and that would include things like how to configure beaker?

**Comment by Zharktas** [comment]
Session files are stored in /tmp by default which are typically cleared during reboots. So if the machine is maintained at all, it sorts itself out automatically.  

There is wiki page on running HA clusters https://github.com/ckan/ckan/wiki/CKAN-High-Availability, but it hasn't been maintained. You can always write an issue about documenting HA setups, but I doubt the core team has time to write those, especially since there are countless options to do it now days. For example do you want to run docker containers or not, where is your load balancer installed: in some virtual maching running nginx or cloud provided solution, one solution would not work for everybody.

Single machine setups can do quite a lot, for multimachine setups you need some devops person to implement it as there's a  quite a lot of security aspects to consider as well which in unmaintened documentation would cause issues.

**Comment by adborden** [comment]
Thanks for the information. We (Data.gov) have some experience running HA services and production CKAN and would be happy to contribute to those docs if there was a place the core team could maintain them.

Since this issue is closed, does that mean you are not interested in a CKAN feature that would manage expired sessions, even if the core team wasn't the ones to implement it?

**Comment by Zharktas** [comment]
By all means, all contributions are welcome. Docs could always be improved, although github wiki pages probably would be the place to start with HA setups, as docs.ckan.org is only updated when there is a new release.

I've closed the issue as the problem is not in ckan itself rather it is in misconfigured beaker. Especially as beaker configuration is not covered by ckan docs. If someone was to implement, test and document a feature which would remove old sessions from database periodically, it probably would merged to the core.

**Comment by ThrawnCA** [comment]
We have never had trouble with the Beaker session cache filling up before, despite running production instances that are rarely restarted, for years. However, since recently upgrading to CKAN 2.9 (less than a fortnight ago), we have started encountering incidents from our disks running out of inodes and needing to be manually cleaned out.

We will probably establish a cron job to start cleaning up old files. However, it is concerning to us that:

a) CKAN's documentation never hints at this being a necessary step. In fact, searching for "beaker" on docs.ckan.org produces only two hits, both in the changelog (and applying to older version). How are site owners meant to know that "one should really read the beaker docs", when CKAN's docs are almost entirely silent about Beaker's presence?

b) This appears to have substantially escalated with the upgrade to CKAN 2.9.

**Comment by mhazan01** [comment]
> We have never had trouble with the Beaker session cache filling up before, despite running production instances that are rarely restarted, for years. However, since recently upgrading to CKAN 2.9 (less than a fortnight ago), we have started encountering incidents from our disks running out of inodes and needing to be manually cleaned out.
> 
> We will probably establish a cron job to start cleaning up old files. However, it is concerning to us that:
> 
> a) CKAN's documentation never hints at this being a necessary step. In fact, searching for "beaker" on docs.ckan.org produces only two hits, both in the changelog (and applying to older versions). How are site owners meant to know that "one should really read the beaker docs", when CKAN's docs are almost entirely silent about Beaker's presence?
> 
> b) This appears to have substantially escalated with the upgrade to CKAN 2.9. We are seeing inode usage rise at nearly a percentage point every two hours. Furthermore, it seems like it would be entirely possible for someone to turn this into a denial-of-service attack, by simply spamming a server with requests until its cache fills the disk.

same here it's killing the vm where CKAN is hosted and locking any disk write. was any more issue created about this ?

**Comment by ThrawnCA** [comment]
> same here it's killing the vm where CKAN is hosted and locking any disk write. was any more issue created about this ?

I don't think there is an automatic cleanup, but the explosion of sessions was addressed in #6954 (release 2.9.6).
