### ISSUE TITLE
docs.ckan.org for 2.6, 2.7 and 2.8 haven't been updated since 2018

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#5380]
### Please describe the expected behaviour
https://docs.ckan.org/en/2.8/, https://docs.ckan.org/en/2.7/ and https://docs.ckan.org/en/2.6/ should have latest docs for each version.

### Please describe the actual behaviour
The docs are generated for 2.8.2, 2.7.5 and 2.6.7

**Comment by amercader** [comment]
Yes, unfortunately our old Jinja2 versions conflict with the ones used by RTD: https://github.com/readthedocs/readthedocs.org/issues/6894

The problem is that because of the way we generate the docstrings we need a full install of CKAN. At the end of the linked issue there is a suggested library that would avoid that.

Related: https://github.com/ckan/ckan/issues/4892

**Comment by smotornyuk** [comment]
Seems to be fixed: 
![image](https://user-images.githubusercontent.com/11091199/154957470-eb314070-0fd7-4d64-88c8-f0de180f850f.png)
