### ISSUE TITLE
Password validator does not include validation for at least 1 upper case, 1 lower case, 1 number and 1 special character.

### ISSUE THREAD

**Issue by Gauravp-NEC** [ckan/ckan#5512]
The built in "user_password_validator" function does not validate 1 uppercase, 1 lowercase, 1 digit and 1 special character. If customized password validator is applied then the "user_invite" function crashes with "Internal Sever Error".  

The "user_invite" function does not generate the password with at least 1 special character.

**CKAN version**
   2.8.4

**Actual behavior**
Existing password validator validates the password to be string and must be 8 character or long.

**Comment by wardi** [comment]
For generating new passwords we should make passwords optional (invited users have no password) instead of hoping that a particular random password will pass whatever validation rules are configured on a particular ckan site.

If you're interested in adding this feature please comment and I will reopen this ticket.
