### ISSUE TITLE
CkanUrlException Error Issues with version 2.8

### ISSUE THREAD

**Issue by tchnlgst** [ckan/ckan#5711]
**CKAN version**
2.8

I have the ckanext-openafrica theme working well under CKAN 2.7 (no issues there). 

I decided to move up one level to CKAN 2.8, and installed the theme as I had done before. 

When logging into the user dashboard, I get the following:

```
File "/usr/lib/ckan/default/src/ckanext-openafrica/ckanext/openafrica/templates/header.html", line 49, in block "header_wrapper"
   <a href="{{ h.url_for(controller='user', action='dashboard') }}">Control Panel</a>
 File "/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py", line 332, in url_for
   return _local_url(my_url, locale=locale, **kw)
 File "/usr/lib/ckan/default/src/ckan/ckan/lib/helpers.py", line 537, in _local_url
   raise ckan.exceptions.CkanUrlException(error)
CkanUrlException: There is a broken url being created {'action': 'dashboard', 'controller': 'user'}
```

Looking at the code the error seems to be triggered triggered by this bit in helpers.py (section lines 530-539):

```
if no_root and url_to_amend.startswith(root):
        url = url_to_amend[len(root):]
        if not default_locale:
            url = '/%s%s' % (locale, url)

    if url == '/packages':
        error = 'There is a broken url being created %s' % kw
        raise ckan.exceptions.CkanUrlException(error)

    return url
```

Any thoughts on how to get around it?

**Comment by amercader** [comment]
The syntax for `url_for` changed as the different controllers were moved to Flask blueprints, instead of `url_for(controller=controller, action=action)` you need `url_for(blueprint.view_function)`. Most cases are backwards compatible but this particular one is different because there is a new blueprint for dashboards. You need to update your code to:

```
<a href="{{ h.url_for('dashboard.index') }}">Control Panel</a>
```
Hope this helps, for other support requests please use the [ckan-dev mailing list](https://groups.google.com/a/ckan.org/forum/#!forum/ckan-dev) or the [#ckan tag](http://stackoverflow.com/questions/tagged/ckan) on SlackOverflow. 

You can also try on the [Gitter channel](https://gitter.im/ckan/chat), where other developers may be able to help you.

Thanks!
