### ISSUE TITLE
User following an Orgazation can't load any page

### ISSUE THREAD

**Issue by Engerrs** [ckan/ckan#5765]
**CKAN version**
CKAN 2.9

**Describe the bug**
When A User follows an Organization/Group with a lot of Datasets related to it, he/she unable to load the page. The issue start appearing at least when Org have 100 and more Datasets.

**Expected behavior**
As on CKAN 2.8 it worked well without any loading issues.

**Additional details**
I know that the activity model has been modified in CKAN 2.9, to be more exact here is the line that makes to most time consume https://github.com/ckan/ckan/blob/master/ckan/model/activity.py#L229

Couldn't prepare a PR to this one as I'm not sure how it should work properly so I suggest the author to look into to it.

**Comment by alexandru-m-g** [comment]
At the link mentioned above there is a left outer join with an OR condition: 

1. `model.Package.id == model.Member.table_id` OR
1. `model.Package.owner_org == group_id`

Is (2) really needed ? What is the case where the owner_org in the package table is not reflected in the member table ? 

Also, isn't it a bit weird to have a join condition that doesn't connect to any other table ? We are looking for data from Activity table but how can (2) help with that if it's not connected to it ? And doesn't this just multiply the rows of the subquery ?

I'm asking because on our database this query never finishes. Removing (2) seems to solves the issue.
