### ISSUE TITLE
Overly aggressive indexing strategy greatly increases datastore storage requirements

### ISSUE THREAD

**Issue by jqnatividad** [ckan/ckan#5847]
**CKAN version**
2.9.1

**Describe the bug**
The postgres datastore creates several indices when a resource is uploaded.

A unique index for the `_id` internal field, an FTS index using the `_full_text` internal field (which stores all the column values in one field for FTS searches, effectively doubling the width of the table), and **_one index per text column._**

Though this is great for ad-hoc queries using `datastore_search` and `datastore_search_sql`, and for interactive filtering on the UI, it greatly increases the datastore's storage requirements.

For example, a table with 1.37 million rows and 9 columns is:

- **60 mb** as a csv file
- **302 mb** for the database table
- **569 mb** for the 8 indices (unique index for `_id`, 1 fts index, and 6 indices for the 6 text columns. It did not create indices for the one timestamp and two numeric columns) 

I got this info while testing the [expanded `datastore_info` PR.](https://github.com/ckan/ckan/pull/5846)

**Expected behavior**
The team should consider giving finer granular control to the CKAN administrator beyond [specifying the index method](https://docs.ckan.org/en/latest/maintaining/configuration.html#ckan-datastore-default-fts-index-method).

Some indexing "knobs" to consider:
* turn on/off FTS index
* leverage the data dictionary to explicitly declare columns that should be indexed. As an added benefit, this should also allow indices for non-text columns
* or alternatively, instead of creating a mini DBA interface on CKAN (a non-trivial task), just read the postgres system catalog and  selectively show some indexing info on the data dictionary (leveraging the expanded `datastore_info`), and let the DB/CKAN administrator use robust tools like PgAdmin to manage datastore indices manually.  This is consistent with the keeping the Datastore API _["as thin as possible to allow you to use the features you would expect from a powerful database management system."](https://docs.ckan.org/en/2.9/maintaining/datastore.html#the-datastore-api)_

**Comment by wardi** [comment]
:+1: to using the data dictionary interface to enable indexes and having the per-column indexes disabled by default

**Comment by wardi** [comment]
1. Update `datastore_create` to default to not add any indexes when the `index` list of fields is empty or not provided.
2. Show which fields are indexed in the data dictionary and make it possible to add or remove indexes for field types that support indexing. Future: we might want to be able to select which columns are included in the full text search index here too.
3. For large datasets creating indexes will take a long time, we should use a background job to run the datastore_create call so that the web UI doesn't time out returning a response to the user.

**Comment by amercader** [comment]
https://github.com/ckan/ckan/pull/8530 looks good and will at least allow to deactivate the index creation site wide, addressing the first point.

But this would be much better handled on a per-resource basis, allowing the publishers to index columns on data files where it makes sense. @wardi is this a matter or storing a list of column names to index in the data dictionary and pulling this information
to call `datastore_create` with the `indexes` param to trigger the index creation (just by looking at the API docs, haven't checked that's what that param does)?

**Comment by wardi** [comment]
The `indexes` parameter is for normal indexes, indexes that help `filter` and `sort` parameters of `datastore_search`.

When the `q` parameter is a dict it always does a FTS search but when there is no index on the specific columns it *also* queries on the general FTS index, so for many datasets will be about as fast with per-column FTS indexes as without.

For the 3.5GB csv test data I'm using loaded into the datastore:
- 10GB is used for the data itself
- 2GB is used for the general FTS index
- 14GB is used for per-column FTS indexes

So more than half of the datastore storage and a significant amount of time when updating is spent on what only *might* be a performance improvement for a specific way of calling `datastore_search`.

Even when we do create a UI for enabling FTS indexes on specific columns it's going to be a challenge explaining to users what the feature does and when they will actually benefit. That UI should also offer configurable normal indexes and indexes across multiple columns because those affect other `datastore_search` use cases. As @jqnatividad says this is like creating a "mini DBA interface on CKAN" which might be overkill.

**Comment by wardi** [comment]
Performance impacts will vary, but as an example a FTS query on a field that returns 200k rows from a test 11M row table is 20% slower after removing the additional index. Other queries are unaffected.
