### ISSUE TITLE
Sysadmin cannot edit normal user's profile

### ISSUE THREAD

**Issue by asas1asas200** [ckan/ckan#6142]
**CKAN version**
2.9.2

**Describe the bug**
When a sysadmin edit normal user's profile, ckan always reports `Old Password: incorrect password` error message.

**Steps to reproduce**
1. Login as sysadmin.
2. Select a normal user and into Manage page.
3. Typing something in the form exclude change password field.
4. Get the error message.

**Expected behavior**
Sysadmin can correctly update normal user's profile.

**Additional details**
I think that is about this:
https://github.com/ckan/ckan/blob/5e7ea57f97d03219fd2098c8d6848905ba056170/ckan/views/user.py#L287-L290
That will check if the email was changed, but it compare with `g.userobj.email`, i.e. current login user's email.
So when a sysadmin want update normal user's profile, it will always get an error about `Old Password incorrect`.
I am trying to fix it now.

**Comment by tino097** [comment]
@asas1asas200 looks like you are not entering your sysadmin password when doing the changes. The current flow could be little bit confusing or misleading because the sysadmin pass field is part of the password changing block 

In case that i missinterpreted your inputs, please reopen the issue and if possible add some additional details

**Comment by etj** [comment]
I guess this issue is still open.
If the admin is editing another user's profile, some internal assignment are plainly wrong, e.g.:

Here we are taking the admin username, not the edited profile:
https://github.com/ckan/ckan/blob/2121cda9865a26ebf2058c41e65b827c4e66f136/ckan/views/user.py#L270

Here the code is comparing admin mail address against the edited user one:
https://github.com/ckan/ckan/blob/2121cda9865a26ebf2058c41e65b827c4e66f136/ckan/views/user.py#L287
