### ISSUE TITLE
DataPusher not documented in CKAN source installing document.

### ISSUE THREAD

**Issue by Gauravp-NEC** [ckan/ckan#6269]
**CKAN version**
Master

**Describe the bug**
There is no information about DataPusher in CKAN source installing doc: https://docs.ckan.org/en/2.9/maintaining/installing/install-from-source.html

**Expected behavior**
DataPusher must be documented after Datastore in the CKAN source installing document.

**Comment by jqnatividad** [comment]
This might be because the datastore is an optional extension, as noted in step 8 of the source install.

https://docs.ckan.org/en/2.9/maintaining/installing/install-from-source.html#set-up-the-datastore

If you choose to set it up, it does [link to the procedure](https://docs.ckan.org/en/2.9/maintaining/datastore.html#datapusher-automatically-add-data-to-the-datastore) to install the DataPusher.

**Comment by Gauravp-NEC** [comment]
My suggestion is that a precise information about DataPusher must be documented after DataStore. This will help beginner's to know more about CKAN and DataStore extension.

**Comment by Gauravp-NEC** [comment]
@amercader , Please assign this issue to me. Thankyou

**Comment by kowh-ai** [comment]
@jqnatividad is correct - the datastore is an optional extension. @Gauravp-NEC - We chatted about this today at the Dev meeting. The documentation for installing CKAN from source should be as minimal as possible (which I believe it currently is). However what might be helpful is mentioning: "**DataPusher** _or_ **XLoader** could be installed after DataStore in the **8. Set up the DataStore** section as both these plugins are common and rely on the DataStore"

**Comment by Gauravp-NEC** [comment]
@kowh-ai , Thanks. I will fix this issue.

**Comment by Gauravp-NEC** [comment]
@kowh-ai , I have raise the PR https://github.com/ckan/ckan/pull/6281 to fix this issue.
