### ISSUE TITLE
i18n js files are built in source directory

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#6278]
**CKAN version**
all

**Describe the bug**
On startup the ckan process tries to rebuild all JS translations by overwriting a file in the ckan source directory. This means the web process needs to have permission to write to its own source directory just to be able to start. This encourages a bad security practice so we should generate this file in a location that the web process would normally have write access, such as the upload directory.

We should also stop regenerating these files on startup when `debug=false` (require use of the cli or deployment for updating translations) for production sites to cut down on startup time.

**Steps to reproduce**
Make a change to a .po file covering text that appears in js on a site supporting multiple languages, then start ckan with a user that doesn't have permission to modify files in its own source directory

**Expected behavior**
ckan should start even when it doesn't have permission to modify its own source directory

**Additional details**
```
...
  File "/project/ckan/ckan/config/middleware/__init__.py", line 55, in make_app
    load_environment(conf, app_conf)
  File "/project/ckan/ckan/config/environment.py", line 131, in load_environment
    build_js_translations()
  File "/project/ckan/ckan/lib/i18n.py", line 408, in build_js_translations
    _build_js_translation(lang, po_files, js_entries, dest_file)
  File "/project/ckan/ckan/lib/i18n.py", line 348, in _build_js_translation
    with open(dest_filename, u'w') as f:
IOError: [Errno 30] Read-only file system: u'/project/ckan/ckan/public/base/i18n/fr.js'
```

**Comment by robson-koji** [comment]
Wardi, I am new to CKAN, I am looking this issue and I would like to work on it. 

**I was not sure how to reproduce the problem**

First I tried on my development environment (git clone here), running the command below in virtualenv. 
- ckan -c /etc/ckan/default/ckan.ini run

Translations did not compile on dev, but I think this is the expected behavior. 


I built a "production environment" following the docs. On this environment supervisord is the responsible to start CKAN and boot uwsgi as the command below:

- command=/usr/lib/ckan/default/bin/ckan -c /etc/ckan/default/ckan.ini jobs worker 

I changed ckan/i18n/pt_BR/LC_MESSAGES/ckan.po, and the file ckan/public/base/i18n/pt_BR.js compiled just fine. 

supervisord sets user to www-data, the same owner of the created filesystem structure on installation, so this environment compiles just fine. 


**I faked the environment to reproduce the problem**
I changed ownership of the compiled file to get the expected result:

```
  File "/usr/lib/ckan/default/src/ckan/ckan/config/middleware/__init__.py", line 56, in make_app
    load_environment(conf)
  File "/usr/lib/ckan/default/src/ckan/ckan/config/environment.py", line 138, in load_environment
    build_js_translations()
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/i18n.py", line 413, in build_js_translations
    _build_js_translation(lang, po_files, js_entries, dest_file)
  File "/usr/lib/ckan/default/src/ckan/ckan/lib/i18n.py", line 355, in _build_js_translation
    with open(dest_filename, u'w', encoding='utf-8') as f:
PermissionError: [Errno 13] Permission denied: '/usr/lib/ckan/default/src/ckan/ckan/public/base/i18n/pt_BR.js'
```

I can start from here, I just want to be sure what the main goals are.  Can you please confirm them:

1. Translation to happen only with debug=false
When the sysadmin first run the application or whenever a new translation occurs, he/she needs to set debug=true, boot the system in order to compile translation, shutdown the system and boot again. 

2. Create compiled files in a "public" folder
