### ISSUE TITLE
Limit API endpoint

### ISSUE THREAD

**Issue by tmneche** [ckan/ckan#6295]
**CKAN version 2.8**

**Describe the bug**
API endpoint only returns 10 datasets despite otherwise indicated in the API documentation

**Steps to reproduce**
I used this endpoint ckanu.rl/api/3/action/package_search?include_private=True&include_drafts=True to migrate datasets. 

**Expected behavior**
I expected this endpoint to return all datasets. It only returned 10. As workaround, I checked the count and add &rows={count} to get all datasets

**Comment by Zharktas** [comment]
The API documentations says for `rows` parameter in `package_search`:

> rows (int) 
>
> – the maximum number of matching rows (datasets) to return. (optional, default: 10, upper limit: 1000 unless set in site’s 
> configuration ckan.search.rows_max)

Which means that if you do not give `rows` parameter, `package_search` will return 10 datasets. The maximum by default is 1000 due to performance reasons or whatever you have given in `ckan.search.rows_max` parameter in your configuration and you will need to fetch them in multiple calls by using `start` parameter.

**Comment by robin-NEC** [comment]
Hi @Zharktas , I'm interested to work on this issue. Please let me know, if anything else is needed to be done on this issue.

**Comment by Zharktas** [comment]
There really isn't anything to do here, everything is documented already.
