### ISSUE TITLE
Flask-Babel 2.0.0 breaks ITranslation

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#6708]
Upgrading Flask-Babel from 1.0.0 to [2.0.0](https://github.com/python-babel/flask-babel/releases/tag/v2.0.0) makes the `ITranslation` tests fail:

https://app.circleci.com/pipelines/github/ckan/ckan/1902/workflows/8ef66c69-6def-4d1b-8bbf-1678e93f56aa/jobs/9630

Basically our custom override to support multiple translation domains is never called:

https://github.com/ckan/ckan/blob/d47eb0972a6f99460926e2869bd858caee1f74bf/ckan/config/middleware/flask_app.py#L97-L106

@TkTech I *think* that the way this works in Flask-babel changed as part of this change: https://github.com/python-babel/flask-babel/pull/163 but I couldn't find any docs on how the new approach works.

Do you have any pointers on how to refactor this on our end?

**Comment by TkTech** [comment]
@amercader I'll look into this, however it'll have to wait until Saturday.

**Comment by TkTech** [comment]
I'm not entirely sure how this works as-is. It seems to depend on the order it's called (?) which is prone to breaking. Under v2.0.0, the approach I think will work here is to create a:
 ```domain = flask_babel.Domain(translation_directories=plugin.i18n_directory(), domain=plugin.i18n_domain())```
 for each plugin that defines `ITranslation`, then pass in `domain.gettext` to the templates instead of `flask_babel.gettext`.

**Comment by amercader** [comment]
@TkTech I wasn't able to figure out your approach, so I proposed this on the Flask-Babel side:
