### ISSUE TITLE
Order of primary and secondary block in mobile view is wrong

### ISSUE THREAD

**Issue by knudmoeller** [ckan/ckan#6773]
**CKAN version**

2.9.5 (bug introduced in 2.8.0 in https://github.com/ckan/ckan/commit/00e8dc5caa1029f978dc0525b3996f2bc8330c61)

**Describe the bug**

Block `secondary` from the `page.html` template is rendered before block `primary` in mobile view (width < 768px). This is counter-intuitive and confusing.

**Steps to reproduce**

* Open any page with a primary and secondary block (e.g. a dataset view).
* Decrease window width to below 768px.

**Expected behavior**

* The primary block with navigational elements and the main information should be on top.
* Secondary block should come, well, second. 

**Additional details**

* Simply switching the order of the blocks in `page.html` seems to work at first, but now the whole content of the primary block cannot be interacted with (probably a z-index-problem?).

![Screenshot 2022-03-25 at 17 38 29](https://user-images.githubusercontent.com/1128115/160163498-7f7db85c-04ee-41c1-b9b2-a37267053685.png)

**Comment by Zharktas** [comment]
It would make sense that primary and secondary would be in order they originally were, screen readers and such kind rely on that. However swapping them back would require for fixing the original issue https://github.com/ckan/ckan/issues/3754 properly with CSS.

**Comment by robin-NEC** [comment]
Hi @Zharktas , I would like to work on this issue.

**Comment by robin-NEC** [comment]
>**The fix does not affect the layout of the `page.html` in desktop mode.**

On investigation, I found that this issue is not only affecting the dataset page but also the other components like organizations, groups, and user profile pages in CKAN versions 2.8 and above.

Below are the changes before and after applying the fix:

![datasetbefore#6773](https://user-images.githubusercontent.com/100402885/173563165-98cc12e3-c586-41d8-8911-5bd64b68336b.PNG)

![dataset#6773](https://user-images.githubusercontent.com/100402885/173562861-895a9267-b712-42de-8a2f-adf90804effb.PNG)

All the components of both the blocks are responsive after the fix is applied.

**Comment by robin-NEC** [comment]
Before:

![before_patch#6773](https://user-images.githubusercontent.com/100402885/173578061-e736bebe-8ae6-4e57-b6ca-6ad887b7f245.PNG)

After :

![after_patch#6773](https://user-images.githubusercontent.com/100402885/173578049-46e37a5f-f12b-49c9-b5d7-ffe7b4419483.PNG)
