### ISSUE TITLE
Extra resource metadata fields are being lost when it is updated via UI.

### ISSUE THREAD

**Issue by sagargg** [ckan/ckan#6998]
**CKAN version v2.8, v2.9 , v2.10  and Main**

**Describe the bug**
Extra resource metadata fields are being lost when it is edited via UI.
https://github.com/ckan/ckan/blob/master/ckan/views/resource.py#L236

**Steps to reproduce**
1. Add extra fields/metadata to the resource using `resource_update` or `resource_patch` API and confirm it has been added via resource_show API.
2. Update any resource metadata via resource edit UI and save it. 
3. You won't be seeing recently added extra metadata anymore.

**Expected behavior**
It shouldn't delete extra metadata.

**Suggested Fix**
Replace this with `resource_patch` instead of `resource_update`
https://github.com/ckan/ckan/blob/master/ckan/views/resource.py#L236

**Comment by TomeCirun** [comment]
Yes, I investigated a bit around this, this [line](https://github.com/ckan/ckan/blob/568e28fe43d452709b1fdd6667e6d09f2b09a490/ckan/logic/action/update.py#L107) is causing the problem, data_dict contains all values from the resource form and since it doesn't have custom fields, it would delete the extra metadata fields on every update. 
One way to avoid this is by your suggestion, instead of resource_update we could use resource_patch, another way is to integrate custom fields on the resource form the same as we did on the dataset.

I can work on this.
Which one would you prefer? 

Thanks

@wardi @sagargg

**Comment by wardi** [comment]
changing to resource_patch for resource editing would be an API change that users may be relying on (e.g. with dynamic fields not submitted when they shouldn't be saved) It would be better to add these as fields to your schema and hidden inputs in the form.

**Comment by TomeCirun** [comment]
@wardi we already have extras in our resource schema, i just checked out, they are saved in resource.extras
![image](https://user-images.githubusercontent.com/72216462/182956103-b67a0324-59bb-443e-85df-281bc57cc935.png)
i will need to add only the hidden inputs in the form right?

**Comment by sagargg** [comment]
Hi @wardi,   are you suggesting this shouldn’t be fixed in core code but add hidden extra input fields in the extension template per project requirement?

**Comment by wardi** [comment]
@sagargg yes that's the backwards-compatible way to add resource fields that aren't changed by the form.
