### ISSUE TITLE
Docker: Login fails with Firefox browser

### ISSUE THREAD

**Issue by ondics** [ckan/ckan#7062]
**CKAN version**

2.9.5, master branch, cloned on apr,7, 2022
Commit: dfa58c885795bcafe531bfe2e0289c53b6f203ea

**Describe the bug**

I cannot login with a freshly installed CKAN docker instance.

**Steps to reproduce**

After starting up the docker-compose, I create a sysadmin user with the command line. This works perfectly.
When I try to login with Firefox browser (version 104.0.2) I get the error message "wrong user or password".
When I try to login with Google Chrome browser (version 105.0.5195.102) login works.

**Expected behavior**

Login should work across the major browsers.

**Additional details**

![grafik](https://user-images.githubusercontent.com/1729357/188912998-0c5ba5e5-2055-45f3-a0fd-89476c9f9370.png)

**Comment by kowh-ai** [comment]
Iv'e just tested a new CKAN **2.9.5** (Docker) install. Created a new (admin) user and logged in using both Chrome and Firefox (**104.0.1**) browsers. Both work fine. Screenshot of the Firefox browser after logging in:

![ff ckan](https://user-images.githubusercontent.com/54408245/189341169-b0949f62-63d5-448c-8d75-dfe39f899600.png)

**Comment by ondics** [comment]
Hmmm. Maybe a 301 redirection problem in some of our browsers? Anyway. 
Thank you for your investigation.
I close this issue.

**Comment by TimoB2005** [comment]
Same problem here.

Firefox login fails repeatedly. Please reopen Issue.

**Comment by s2074135** [comment]
Hi

I have the same problem using CKAN 2.9.7, login with Firefox fails on valid credentials.

When going into the browsers Developer Mode, I get several messages of: 

`"Cookie “ckan” has been rejected because it is already expired."`. 

![firefox](https://user-images.githubusercontent.com/39614473/215049855-22b71916-1677-4c42-854c-dd516446a1fe.png)

When clearing the FF cache or using Private Browsing Mode, this error messages disappear and login works again.

As a test, I have disabled the config option "beaker.session.cookie_expire =" in ckan.ini and this seems to increase the time before a valid login attempt is rejected by CKAN.

I do not see any other messages in my log files. Is there anything I could do to increase beakers log output?

Thomas

**Comment by MartinHowitt** [comment]
I get this same problem now on 2.9.9, but when using Chrome. I can log in either using an incognito window in Chrome, or using Firefox.
