### ISSUE TITLE
Ckan Docs page is down - do we have an alternative?

### ISSUE THREAD

**Issue by JackBurns1984** [ckan/ckan#7240]
![image](https://user-images.githubusercontent.com/115991393/203750167-620b2cf7-a6f2-4541-9271-7b41e4212898.png)
hello,  the ckan document page is down,  I was looking for some pages about updating the dataset question groupings.  

do we have any documents i can download until the site is backup?

**Comment by JackBurns1984** [comment]
never mind - the page is back. thanks :)

**Comment by amercader** [comment]
Sorry, there's some really confusing configuration problem between Readthedocs and Cloudflare but *I think* we should be fine now. Thanks for reporting it

**Comment by wardi** [comment]
I've been working around this issue by clicking the "Save" button on the custom domain page of readthedocs every 30 days but I think the root cause is that our DNS is configured to use an alias instead of a CNAME (which readthedocs doesn't like)

```
$ host docs.ckan.org
docs.ckan.org is an alias for readthedocs.io.
```

![Screenshot from 2022-11-24 07-52-54](https://user-images.githubusercontent.com/153258/203789310-536f817e-9337-4cef-8d3e-1cd7114454a8.png)
