### ISSUE TITLE
Revisit the config.get / config.get_value approach

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#7282]
Config declaration introduced in #6467 is undoubtedly useful and one of the highlights of CKAN 2.10, in terms of cataloguing the configuration options available from core and extensions, and in terms of being able to rely on config options being the expected format.

But the current implementation with two config modes (`default` / `strict`) and different access methods (`config.get()` / `config.get_value()` ) is confusing and error-prone (see eg #7141,#7223, #7254, #7257) so before formalizing it in major CKAN release maybe we can re-think the approach and simplify it.

## Current behaviour (pre-CKAN 2.10)
Let's assume we have these configuration options in our ini file:

```ini
ckan.myconf1 = 12
ckan.myconf2 = one two three
ckan.myconf3 = yes
# This config option is undeclared
ckan.myconf4 = some_text 
```
And we have the following config declaration:
```yaml
- key: ckan.myconf1
  type: int
- key: ckan.myconf2
  type: list
- key: ckan.myconf3
  type: bool
```

| conf option | CKAN 2.9 config.get(x) | CKAN 2.10 config.get(x) - config.mode = default | CKAN 2.10 config.get_value(x) - config.mode = default | CKAN 2.10 config.get(x) - config.mode = strict | CKAN 2.10 config.get_value(x) - config.mode = strict |
| --- | --- | --- | --- | --- | --- |
| ckan.myconf1 | `"12"` | `"12"` | `12` | `12` | `12` |
| ckan.myconf2 | `"one two three"` | `"one two three"` | `["one", "two", "three"]` | `["one", "two", "three"]` | `["one", "two", "three"]` |
| ckan.myconf3 | `"yes"` | `"yes"` | `True` | `True` | `True` |
| ckan.myconf4 | `"some_text"` | `"some_text"` | `"some_text"` + Warning: "Option ckan.myconf4 is not declared" | `"some_text"` | `"some_text"`
| ckan.not_defined | `None` | `None` | `None` + Warning: "Option ckan.not_defined is not declared" | `KeyError` raised | `None` |

I think that `KeyError` is a bug, we shouldn't override default `.get()` behaviour like this. Aside from this the differences are clear, we chose to be conservative when using the `default` config mode and the standard `.get()` method and return the unparsed value. If you want the parsed value you need to call `.get_value()` or use `config.mode = strict`.

But `config.mode = strict` has other implications, mainly that failing to parse a declared config option will raise an exception and prevent CKAN from start:

```ini
ckan.myconf1 = not_an_int
```
| conf option | CKAN 2.9 config.get(x) | CKAN 2.10 config.get(x) - config.mode = default | CKAN 2.10 config.get_value(x) - config.mode = default | CKAN 2.10 config.get(x) - config.mode = strict | CKAN 2.10 config.get_value(x) - config.mode = strict |
| --- | --- | --- | --- | --- | --- |
| ckan.myconf1 | `"not_an_int"` | `"not_an_int"` | `"not_an_int"` | CKAN won't start with `AssertionError` | CKAN won't start with `AssertionError` |

```
AssertionError: Invalid value for ckan.myconf1: not_an_int
```
## Proposal

1. I'd remove `.get_value()`, make `.get()` return the parsed configuration value. I know this has potential to break things but assuming we clearly communicate this in the CHANGELOG it would be limited in scope:

  * This will only potentially affect configuration options that 1) are declared (ie only core ones) and 2) have a custom validation/formatting/default values applied 
  * If some extension was already parsing the configuration option with `int()` or `toolkit.aslist()` that will keep working as expected
  * There's still potential to break things if users were doing stuff like `print("Count: " + conf.get("ckan.some_int_value")`, this will work on CKAN 2.9 and fail on 2.10, but we need to assess if this risk outweighs the complexity and confusion that having both `.get()` and `.get_value()` will mean for users.

2. I'd keep `config.mode = strict` but just enforcing the config declaration, ie raising an exception if the configuration is not properly defined. I can definitely see how this is useful for site maintainers, specially as more extensions adopt config declarations
3. I'd remove the `Warning: "Option ckan.not_defined is not declared"` messages in `default` mode and only show them in `strict` mode. But I'd also add warnings if a declared option was not properly parsed in `default mode.

@smotornyuk you are the one who wrote this and the one with more experience in how the config is managed. What do you think? I probably missed something, but is what I'm proposing easy to implement (apart from changing a lot of `get_value()` calls :upside_down_face: )?

@ckan/core it would be good to get your take on this, I know we discussed this in the past but I feel we can avoid future confusion before releasing CKAN 2.10

**Comment by pdelboca** [comment]
### My thoughts on this:

 - I support the idea of removing `get_value()` and stay with only `get()`
 - I would also remove the `Warning: ...` when in default since it's confusing and currently a little bit buggy and causes some confusion: like [here](https://gitter.im/ckan/chat?at=639ddc0883b5463b6e09324e).
 
### My long personal thoughts on this:

I'm personally not a fan of this type of features since the complexity outruns the benefits. This changes are really low level (extending the Flask config object and overriding `__get__`), and when you need to start getting so low I always think twice if it is really necessary.

I expect the config object to be as raw as possible and deal with it's value when calling it instead of having a layer on top of it. I like to be able to explicitly call `as.int(config['key'])` instead of relying of whatever logic `config.get_value("key")` returns. The config File is a file, so I expect nothing but strings to be returned and that's okay for me.

If `as.int(config['key'])` fails, I inspect `config['key']` and fix it which basically is: either fixing the config value (error while adding it) or rethinking my application code. If I have an error on `config.get_value("key")` I need to go to the internal implementations of the config object and declarations and yml to find what's going on and why what I'm getting is not what I expect.

Configs are not forms so heavily validation on it's values shouldn't be expected since they are not dynamically changed. I see some value on it, but as I said, I think the complexity is bigger than the benefits.

I do see the benefit of having some logic to stop the execution in case of missing configurations (specially for maintainers). But in case of extensions I prefer an explicit `Raise("X is not declared")` in the `update_config(...)` or in the loading code instead of an internal lib raising the error.

Config objects are handled by developers/administrators so I wouldn't invest too much time on pre-parsing it to make sure it contains "valid" values (where valid is a debatable question). When I do `config.get(...)` I expect an honest interface to get whatever the responsible for the site put in that place,

Enforcing `strict` declarations will be beneficial if we make it mandatory for the ecosystem of extensions and if the plan is to move to a `strict` mandatory config file. Otherwise, having such a complex implementation but keep a `default` mode makes no sense in terms of effort to maintain. Config declarations hasn't been adopted widely in the core extensions while migrating to 2.10 and this tells something about it's implementation/communication.

**Comment by wardi** [comment]
A couple thoughts (caveat: I haven't used the new config extensively)
- `KeyError` on `get()` with `config.mode = strict` is surprising since the dict `.get(key, default=None)` interface is so common. Should strict checking of the existence be only for the new method of getting values instead?
- something like `parsed(key)` could be a better name than `get_value(key)` because it communicates the intent and is clearly different than `get(key)`

**Comment by smotornyuk** [comment]
Raising a `KeyError` from `get()` in the strict mode is not an intended behavior. It definitely shouldn't work like this:)

As for proposals:

***

> I'd remove .get_value(), make .get() return the parsed configuration value

It was my original suggestion, but we discussed the benefits and chose to introduce a separate method for the parsed config values:) Arguments were basically the same as yours but we decided to make this change as backward-compatible as possible in past. I don't have any preference for this question because I'm not maintaining any worldwide extension. Either updating `get()` or renaming `get_value()` to `parsed()` looks good for me.

*** 

> I'd keep config.mode = strict but just enforcing the config declaration,

I like strict modes, but I'm sure that not everyone will really love declarations, like @pdelboca for example. Whether or not they are useful, really depends on the way you write code and manage the portal. If you just set up CKAN once and never update it, you don't need declarations. Just as @pdelboca said, you won't update your config file often. If you are not updating dependencies, there will be no new config options, so you don't need declarations to check what you are missing in your config file. If you ok with providing the default value as `.get(xxx, 'DEFAULT')` everywhere in your code, you don't need defaults from the declaration, etc.
I'm sure that popular extensions, like dcat or scheming have huge benefits from declarations because it helps them to introduce new or change existing options, guarantee the sanity of values, and reduce the required level of knowledge for people who just starts to use the extension.
But some people are not bothered with the code quality, and they want to quickly write something, get the money, and leave. For extensions that are not evolved and are not used by others, declarations don't have much value. So here enforcing will just cause a strong resentment.

Basically, CKAN never enforced something, only recommended good ways to do a thing. So enforcing declarations may feel unnatural, I believe.

*** 

> I'd remove the Warning: "Option ckan.not_defined is not declared" messages in default mode and only show them in strict mode. But I'd also add warnings if a declared option was not properly parsed in `default mode.

Big +1 here

*** 



@pdelboca , you are completely right to say that the benefits from validation are not really valuable because of the high complexity of the feature. But declarations are not a "validation of config options". It's a set of features. And validations were added in the very end accidentally, just because it was a cheap feature when the whole declaration system began to work. The main "users" of declarations are community extensions. With declarations they can:

* Have a central repository of all config options. You don't need to go through the extension code and check if you added a new config option to the README.md(it's really a pain, especially when working on external PRs). Now everything starts from the declaration file. You see, it's just like our `IAuthFunctions` interface. I never heard that `tk.check_access` is too complex and low-level internally and it kills all the benefits from it.
* Have a standard default value. No more `get(xxx, default)` everywhere in your code. The default value will be the same and you don't have to remember it or update a lot of lines if the default changes. I remember that in CKAN we have a strange bug, when we used a different default `items_per_page`, because somebody forgot to update the code in one place, but updated it in another. Now we are closer to atomic changes - you have to change one place in code(declaration) in order to change the single aspect of behavior(default value).
* Standardise the way to document code. At least, configuration. Somebody documents config options in README.md, somebody creates helpers that return parsed value and adds documentation to them, and somebody ignores documentation. Declarations have a special property for docs, so everyone can add them in the same way. You, actually, don't have to add a description of the config option to README.md anymore, because you can check the documentation for config via CLI (but I still recommend doing it, for usability. It can be a good idea to create a CLI command that will insert docs for declared config options into README.md of your extension). 
* Extend configuration-related capabilities. Have you seen nice and shiny config-related sections in CMS, like Drupal/Wordpres, that list all the config options from all the plugins and allow you to change the configuration in real-time, right from the admin interface? Such a thing is not possible in CKAN(don't even try to mention the poor lil' config page from the sysadmin's section), because nobody knows which config options exist in CKAN. Or should I say **was not possible**? Because now you can create an extension that provides such sort of functionality because you have declarations. I'm thinking about working on a such extension, but I really have no time(((
* Get an example of a configuration for the extension. You don't need to open GitHub, search for an extension, read through its manual, and copy configuration options. Now you can use CLI and get the complete list of options for extension and just copy it to your config file.
* Search for options. Have you ever felt frustrated attempting to find a config option for something? For example, you know it contains a `page` fragment, but don't remember if it is `items_per_page` or `page_capacity`? Now you can do in CLI `ckan config search '*page*'` and see all the options that contain `page`. Or, if you want to check all the options that start with `solr`, do `ckan config search 'solr*'`. Neat, right?
* ... a number of possibilities that I'm too lazy to mention:)


PS
> Config declarations haven't been adopted widely in the core extensions while migrating to 2.10 and this tells something about its implementation/communication.

Does it mean that anything that hasn't been adopted widely in the core extensions while migrating to 2.10 has not much value? In that case, can you show an example of features that "were adopted widely"? Or everything we worked on is senseless?:)  
Declarations are not adopted, because they are functional only in CKAN 2.10. So you have to write a code, that relies on declarations and a separate code for the non-declaration environment in CKAN v2.9. We cannot expect that people will really use it until v2.11 or v2.12 when all the officially supported CKAN versions will support declarations. And it will be the same for absolutely every brand-new feature.

**Comment by amercader** [comment]
To summarize the discussion we had in the last dev meeting:

* We believe that the benefits of having a single way of accessing property values outweigh the potential risk in breaking extensions during a 2.9 -> 2.10 upgrade.
* We will revert the usage of `config.get_value()`. Config options will be parsed at startup time by default, so when calling `config.get()` you will get the parsed value.
* There will be clear documentation in the changelog about changes
* When using `config.mode = strict` an exception will be raised if the options don't pass validations
* We'll limit the warning to:
   * If `config.mode= default` : config options that don't pass validation
   * If `config.mode = string` : config options that are not declared (ie the current  `Option ckan.not_defined is not declared`).

@ckan/core have I captured this correctly? Did I miss anything?
