### ISSUE TITLE
Download_proxy documentation appears to be lost

### ISSUE THREAD

**Issue by Zharktas** [ckan/ckan#7422]
## CKAN version
2.10, master

## Describe the bug
Documentation from https://github.com/ckan/ckan/pull/6517 seems to be missing.

https://docs.ckan.org/en/2.10/maintaining/configuration.html#resource-proxy-settings

**Comment by Gauravp-NEC** [comment]
@wardi , I am interested to work on this issue. Please assign this issue to me.

**Comment by Gauravp-NEC** [comment]
@Zharktas @wardi , I have investigate this issue to update the `Resource Proxy settings` document and I found that `_config_options.inc` file which is a auto-generated file contains the `Configuration Options` document. I didn't find the source from where `_config_options.inc` file is build so that I can edit it.
