### ISSUE TITLE
Invalid session timeout value on CKAN 2.10 (logged out users unexpectedly)

### ISSUE THREAD

**Issue by amercader** [ckan/ckan#7490]
## CKAN version
2.10

## Describe the bug

According to our config declaration for [`beaker.session.timeout`](https://github.com/ckan/ckan/blob/656a39de2e7ed0ce47e15080f0f5d42b66b4929b/ckan/config/config_declaration.yaml#L306):

> Defaults to never expiring.

But the defined default value is 600 :upside_down_face: 
Apart from the inconsistency, this is problematic because now that the logged-in user id is stored in the session by Flask-login, this means that users are logged out every 10 minutes.

The fix is to default it to never expire as described on the docs (which is also the [Beaker default](https://beaker.readthedocs.io/en/latest/configuration.html#session-options)), but the problem is that I can set it to `None` because then Beaker complains that the value is not an int:

```
  File "/home/adria/dev/pyenvs/gates/lib/python3.8/site-packages/beaker/util.py", line 290, in verify_rules
    params[key] = verify_options(params[key], types, message)
  File "/home/adria/dev/pyenvs/gates/lib/python3.8/site-packages/beaker/util.py", line 281, in verify_options
    raise Exception(error)
Exception: Session timeout must be an integer.
```
This is because our config parsing does not support "int or None", and leaves the string "None" as the value. I guess the alternative is to put a really big number but would be good to handle it better.

**Comment by spwoodcock** [comment]
Without `beaker.session.timeout = None` being possible, the `beaker.session.save_accessed_time` variable is also not configurable.

```python
  File "/usr/lib/ckan/.local/lib/python3.10/site-packages/beaker/middleware.py", line 126, in __init__
    coerce_session_params(self.options)
  File "/usr/lib/ckan/.local/lib/python3.10/site-packages/beaker/util.py", line 325, in coerce_session_params
    raise Exception("save_accessed_time must be true to use timeout")
```

**Comment by amercader** [comment]
@smotornyuk this looks related to config declaration so you might have a good shot at this

**Comment by smotornyuk** [comment]
That's why I hate when the value allows multiple types:)

We have two main directions here:

### Introduce more validators

This option leaves config options under our control but it may be too complex for such a trivial issue. 
We need something even more versatile than `int_or_none`, to cover similar cases in the future. How about `accept(*values)` and `accept_type(*types)` validator? It will stop the validation chain when meets a given value or type and keep the current value. In this way `accept(None) int_validator` will use `None` or pass any other value to the following `int_validator`.
But it won't work just now. We have `default: 600`. `default` is used whenever the option is missing from the config file. We can change it to `default: null`(YAML uses `null` instead of `None`) in order to use `None` when the option is missing.

What if we leave the option in the config file, but remove its value: `beaker.session.timeout =`. In this way, the option is present in the config file, so `default: 600` attribute of the declaration is ignored. But Python's config parser module reads such an option's value as an empty string, so it's still not `None`.
In order to overcome this without modifying `default: 600`, we can add CKAN's `default` validator to the list of validators: `validators: default(None) accept(None) int_validator`. CKAN's `default` validator replaces `None`, `tk.missing` and **empty string** with the specified value. So, when an option without the value is added to the config file, CKAN reads it as an empty string, the `default` validator turns it into `None`, `accept` validator interrupts the validation chain.


### Allow anything(almost) as the value for session timeout

We can remove `type: int` and `default: None` from the `beaker.session.timeout`. It means that we have `None` when the option is missing(because the declared option without explicit `default` uses `None`) and an empty/non-empty string when the option is there. 
Now we add the following validators: `validators: default(None) convert_to_json_if_string`. The first validator will convert an empty string into `None`. The second will fire if we still have string after the first validator. It will handle parsing numbers from the string. 

And now it's up to the beaker to validate the option. Things I don't like in this scenario:
* the wrong configuration was handled/reported in a different way than for other config options
* usage of `convert_to_json_if_string` is rather a peculiar way
* we cannot use literals with separators like `1_000_000` now because they are not accepted by the JSON parser(`int_validator` uses Python's `int` class, so they work just fine with it)


But, even though the second option has certain problems, it requires changing only 2 lines inside `config_declaration.yaml`. So, at least for now, we probably should choose it
