### ISSUE TITLE
Hypothesis: embracing an hypermedia approach could lead to an easier transition to a richer UX.

### ISSUE THREAD

**Issue by thegostev** [ckan/ckan#7524]
### Problem statement

Current front-end, while functional and extensible by plugins, have become tedious to maintain and work with.

### Hypothesis

Given that:
 - Lots of CKAN sites are maintained by small teams or even individuals, and
 - is fair to say that there is a significant movement of influential people raising concerns about client based apps and SPAs shortcomings and about them being overuse (see https://hypermedia.systems/ and https://hotwired.dev/), and
 - that a decoupled CKAN could handle this approach as one of the options for frontend technologies, then

It should be possible for CKAN to adopt an hypermedia approach to build a rich UX as a part of CKAN 3.0.

### Discovery work

It would be possible to code a little demo about integrating HTMX in CKAN to evaluate the feasibility of the approach. (There is already some tests ongoing: https://github.com/pdelboca/ckan/tree/demo-htmx) 

### Validation

Why the solution is trustworthy? It is build on already proven technologies and our requirements are not as complex to require a SPA. (Example: We do not need to build an alternative to Google Drive.)

What makes it strong? 
 - It would provide an easier transition (it is build on already existing stack of technology)
 - There are concise metrics on migrations to this technologies: https://htmx.org/essays/a-real-world-react-to-htmx-port/
 - Experiences suggest that this kind of technologies are good for small teams (https://www.youtube.com/watch?v=3GObi93tjZI)

Questions to consider:

- Is this change going to break current installations? **TBD**

- Can we provide a backwards compatibility? Yes

- How easy is gonna be for current implementations to migrate to this new release? **TBD**

- Do current versions of CKAN have the adequate resources/support to migrate to this new version? **Yes**

- Are we going to change the database schema? **No**

- Are we going to change the API? **No**

- Are we going to deprecate Interfaces? **No**

**Comment by pdelboca** [comment]
Some materials of the exploring work I have been doing:

 - Presentation of a small extension to test the integration of HTMX with CKAN: https://www.youtube.com/watch?v=07cE486wc4k
 - Slides: https://docs.google.com/presentation/d/1iWQMpJjW02O0B4UeK0AmBms9gSxRJa2O6dZ46ICr_98/edit?usp=sharing
 - Code to the extension: https://github.com/pdelboca/ckanext-htmx-demo

**Comment by thegostev** [comment]
Hey, @pdelboca thanks for the presentation, demo part was especially good as you've tested and shown feasibility of the approach. After getting through the presentation and looking at additional materials that you've posted I have a several follow up question to undrstand implications of this solution:

1. What parts of the software should be re-written? Based on your demo how many man/hours you'd think it'll take?
2. Can we get the value out of it implementing it partially, deploying and finding evidence that it helps developers? Would it be possible or make sense to implement the approach at some specific are first?
3. Let's connect this solution to the target outcomes that we want to happen after it's implemented. I presume that it'll lead to (1) less frontend experience needed to work with HTMX comparing to the current frontend tech, (2) it's a simplification of the software design = better maintainability and readability, (3) it'll be easier for developers to start with CKAN [if it's so, what's the time saving?], (4) HTMX is a step towards decoupled frontend, is it correct?, (5) would it be more fun for developers working with this tech comparing to the current tech? (6) as it's encourages reusability of snippets, it should increase decrease the cost of making changes. What do you think about these points of potential value, which of them make sense, which of them we know for sure? Can you imagine other potential benefits?

Thanks again for the links and transparency during the process 👍

**Comment by pdelboca** [comment]
Hey @thegostev !

### 1. Estimates
At this point, any estimate would be completely wrong. Said that, evidence suggest that with our current setup any major release takes about a year. So I wouldn't expect any less than that if we do not have a dedicated team. And if we have more team members then whatever estimate would be completely wrong since all the variables change so it is impossible to estimate.

I can say that for me, an experienced CKAN developer, it took around 10hs of work to implement the demo. This is considering that I wasn't paying attention to details, tests, etc. If I need to super ballpark estimate I would suggest that at least a couple of weeks for every screen of the system if a person can have a full-time job working on this. So yeah, it will all come to 6 months, plus testing, plus redoing all the documentation, etc, etc.

So in a summary, the current cadence of releases for CKAN being a year has its reasons and there is nothing to suggest it would be otherwise for a new major CKAN 3.0 release.

### 2. Partial implementations

This could be an option. HTMX is a non intrusive library that we can integrate easily and start partially implementing it. We can, for example, implement the faceted search first. 
Given that the guideline expected for CKAN 3.0 is to revamp the UX, we could move forward with some design decisions and partially implement the faceted search and validate the approach. Following with the dataset creation UI, for example.

### 3. Target Outcomes

(1) I would say that the experience required will be equal. Maybe a little bit higher given that we need to learn the essentials of HTMX. The frontend tech will not drastically change, so the experience either. It will be however be easier to work with since the current template system has a lot of code written 12 years ago that would not be necessary to maintain anymore when redoing it.

(2) The simplification will be because we are going to clean 12+ years old code in our templates system. Code that it is no longer necessary since newer versions of CSS/HTML automatically solve those issues for us.

(3) What's the current time to start with CKAN? Do we have that metric? What's the desired "start up" time? How are we going to measure it?

(4) HTMX **is not an obstacle** for a decoupled front-end initiative. We have a consistent and stable API that we are not planning to drastically change or change at all. This allows anyone in the community who wants to build a decoupled solution to be able to do it. HTMX is just another front-end. The CKAN community should not have any impediment to build decoupled solutions.

(5) Define fun. It would be easier since we are planning on deprecating 12+ years old code. But "fun" is not measurable.

(6) Yes, using HTMX encourages thinking about reusable components/snippets and that is a huge factor. The major benefit could come from the easy integration with current extensions and implementations since there is not going to be any breaking change in the tech stach.

**Comment by thegostev** [comment]
Thanks for details @pdelboca  now it's clear that integrating HTMX falls into refactoring bucket. As any refactoring effort it takes time to re-think current software design with a good amount of testing and bugfix so 6 months sound reasonable to me (as an Order of Magnitude Estimate: -25 percent to +75 percent). From what I read - maintainability will be better with less code after the refactoring.

Answering your questions:
- Easiness for new devs to get in CKAN. Estimating amount of time to start with CKAN is problematic as the sample size of newcomers is small (although I can imagine academic study with a group of new devs). It's safe to assume that increasing [readability](https://www.sciencedirect.com/topics/engineering/readability#:~:text=Readability%20in%20software%20programming%20can,a%20variety%20of%20software%20code.) and maintainability of the software will contribute to ease of starting and continuing working with it.
- The definition of _fun_ in this context would be - willingness of a developer to work with technology and happiness that's produced as the result of working with the tool. Non-fun tech is usually dated, I'd think about [Java native GUI](https://www.guru99.com/java-swing-gui.html). By referring to _fun_ I tried to make a case for HTMX to be a tech that has a chance for newcomers to be happy working with, comparing to the tech we have now. If it's not the case, than as you said "HTMX is just another front-end".

@amercader thanks for the big picture. So it's about (1) out-of-the-box UI and (2) Information Architecture. I would elaborate on problems that you see with it, especially with particular examples to understand them better.

Enjoying the conversation 👍

**Comment by pdelboca** [comment]
@thegostev in that case, then I would 100% say that HTMX is super fun to work with and developers will have tons of fun with it :)

To follow up on @amercader comments. I agree with the approach he's proposing.

If I can be bold and wild I would propose some concrete guidelines. This guidelines are based on how much HTML/CSS has advanced since the beginning of CKAN and how, in that context, some of our code gets obsolete.

### Guidelines:
1. Base our entire styling on vanilla Bootstrap (meaning almost no CSS in our codebase):
   - It's gonna be easy to maintain.
   - First work item of 95% of CKAN implementations is to customize the theme so I don't see any point of putting effort on something that most of our users will change anyway.
   - Bootstrap is not ugly as a default style, we have been using it, and it is as good as whatever other framework on the internet.
2. Remove our macros. 
   - They provide almost no value at all
   - They are painful to work with
   - Inputs are already well standardized
   - Users can control their look and feel using [sass variables](https://getbootstrap.com/docs/5.3/forms/form-control/#css) if desired.
3. Minimize our blocking specificity.
   - CKAN has abused of blocks to provide customization, it provides little value to [have a block to override a CSS class in a 5 lines snippet](https://github.com/ckan/ckan/blob/7d99276e2e09cb6af47df066b5bf5eacd9818765/ckan/templates/snippets/follow_button.html#L7). Or a block to [change the title and subtitle in a 35 lines template](https://github.com/ckan/ckan/blob/master/ckan/templates/snippets/license.html).
4. Clean up all the dynamic custom styling in the admin setting
    - Remove style, theme, custom css and layouts. CKAN is extensible enough to maintain several out-of-the-box layouts.
  
I would like to discuss this in the Tech Team meeting since it should be a common decision. I also lack of context of some design decisions made that now might not make sense to me.

Also, some points like 3 and 4 could provide short term benefits and I would be supper happy to tackle them now :P

**Comment by wardi** [comment]
re point 3 blocking specificity: I can understand the argument to keep the ability to override some small parts of templates because the alternative is copying the whole template into an extension, and that makes it harder for us to make large changes across our templates and to tell what was changed in the copied version when upgrading.

However blocks for changing CSS classes might be unnecessary as long as themes can use CSS to override the styling of specific parts of specific pages. Could we add a classes to one of the parent elements to identify what part of the page is being rendered to make that possible with CSS selectors?

**Comment by wardi** [comment]
Refreshing the UI would be great. I'd love to start with some ideas from outside UI experts where possible and really imagine what could be possible if we rethink the designs we have now.

However template changes can be pushed from both directions. If we choose one focus of CKAN 3.0 to be a UI overhaul then over this development cycle we can be more liberal with breaking template changes in general. We can merge changes that are required by either technical performance reasons like adopting HTMX or big vision Information Architecture changes. I don't think HTMX needs to be the last step in this process.

**Comment by pdelboca** [comment]
HTMX has been selected as one of the 20 Projects of Github Accelerator: https://github.blog/2023-04-12-github-accelerator-our-first-cohort-and-whats-next/

Looks like HTMX has more visibility than I thought it has while doing the presentation :)

**Comment by pdelboca** [comment]
Some new pieces of debate around architectures decisions:
 - https://www.primevideotech.com/video-streaming/scaling-up-the-prime-video-audio-video-monitoring-service-and-reducing-costs-by-90
 - https://world.hey.com/dhh/even-amazon-can-t-make-sense-of-serverless-or-microservices-59625580

**Comment by anuveyatsu** [comment]
@pdelboca I was reading this thread and I think this could be a great improvement for CKAN, esp, in terms of developer experience 👍🏼  we could also improve the ui/ux along the way ⭐  

cc @thegostev

**Comment by pdelboca** [comment]
This is going to be implemented in #7685
