### ISSUE TITLE
CKAN Data API extensions

### ISSUE THREAD

**Issue by wardi** [ckan/ckan#7573]
This is a placeholder ticket for work on improving the CKAN Data API template and making it extendable for new client languages and for cases when the example data can be generated to match the specific table (e.g. w/table designer)

**Comment by drw** [comment]
I'm glad to see that this is in the works. By far, the question we get most often about the CKAN API from our users is "Why is my SQL query not working?". It's always because they don't know that the rules around putting single quotes around certain query elements and double quotes around others. An example query that demonstrates these rules (including how to quote the field names that the user wants to select) would be a great improvement to the Data API template.
