### ISSUE TITLE
Tagging without creating GitHub releases limits visibility

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#7600]
CKAN releases are tagged, but there have not been any corresponding GitHub releases created.

This means that users cannot subscribe to watch the repository for releases and receive notice of security patches such as https://github.com/ckan/ckan/security/advisories/GHSA-446m-hmmm-hm8m

This is particularly concerning since the advice given to customers by Radiant Security, in the lead-up to publishing GHSA-446m-hmmm-hm8m, included instructions to subscribe and watch for releases on this repository. Any customers who followed that advice, expecting to receive a notice of 2.9.9/2.10.1 being released, would still be waiting.

There is no option in GitHub to watch a repository for new tags, so releases are needed.

**Comment by amercader** [comment]
GitHub releases were not part of our release process but of course if it can help to give them visibility we'll start using them from now on.

https://github.com/ckan/ckan/releases/tag/ckan-2.10.1
https://github.com/ckan/ckan/releases/tag/ckan-2.9.9

As per Radiant's advice it didn't run through the maintainers first, otherwise we would have flagged that GH releases were not (yet) used

**Comment by ThrawnCA** [comment]
Thanks. Release notes are a bit sparse, but the notification is good to have.
