### ISSUE TITLE
Support of "ckanext-oauth2" and "ckanext_right-time context" extension with latest CKAN v2.10.1

### ISSUE THREAD

**Issue by nisha-nec** [ckan/ckan#7744]
## CKAN version
2.10.1
## Describe the bug
I am trying to integrate the following two extensions into CKAN v2.10.1. However, I am encountering "**IRoute and xmlrpclib**" error while integrating extensions.

1. [ckanext-right_time_context](https://github.com/conwetlab/ckanext-right_time_context
2. [ckanext-oauth2]https://github.com/conwetlab/ckanext-oauth2

In my analysis, I found that these errors are occurring due to flask and python3 changes in CKAN latest code whereas  these extensions are supporting python2 only. 
I have also gone through the issue '#4793.' On this ticket @amercader has suggested to changes in the extension to support Python 3 and Flask in order to make it compatible with CKAN's latest code.

Please confirm that do I need to  update extension(ckanext-right_time_context, ckanext-oauth2) to support the latest CKAN? or Is there any other way to support the current state extension in the latest CKAN?

Please let me know Is there any other information/ticket related to this issue?

**Comment by pdelboca** [comment]
@nisha-nec both extensions need to be updated in order to be run in CKAN v2.10.1.

You can check the CKAN Wiki for material on how to do that:
 - https://github.com/ckan/ckan/wiki/Python-3-migration-guide-for-extensions
 - https://github.com/ckan/ckan/wiki/CKAN-2.9-to-2.10-migration-tips
 
 There's no other way to integrate those extensions with CKAN v2.10.1.
 
 Bests,
