### ISSUE TITLE
HTML5 validation fails on resource uploads

### ISSUE THREAD

**Issue by ThrawnCA** [ckan/ckan#7915]
## CKAN version

2.10

## Describe the bug

Uploaded resources can get into a state where HTML5 validation fails, complaining that the value of `field-resource-url` is not a proper URL.

### Steps to reproduce

- Create a dataset.
- Create a resource by uploading a file.
- Edit the resource and save it without making changes.
- Edit and save the resource again. The "Update Resource" button will silently fail.

### Expected behavior

Upload URLs should not be subject to HTML5 validation, and if they are, it should be visible rather than silent.

### Additional details

The failure can be made more visible by inspecting the page and disabling the CSS rule that hides `.resource-upload-field > div.select-type`. Clicking on Update Resource will then give a proper error message attached to the URL field, albeit the error should not occur.

The error will temporarily go away if the dataset, rather than the resource, is edited and saved. However, it will return if resources continue to be edited and saved.

**Comment by Chealer** [comment]
Thank you very much @TomeCirun and @amercader

This was backported to 2.10 via 2d60c7f and fixed in CKAN 2.10.3.

Could someone please:

1. rename this ticket to something more functional, like "Resource modification quietly fails for some with locally stored files"
2. make the fix more prominent in the changelog by:
   1. moving this entry up, perhaps just after the security fix
   2. renaming this entry ("Fix HTML5 validation failing on resource uploads") to something more functional, like "Fix quiet failures to modify some resources with locally stored files (URL validation)"
   3. possibly moving _Bugfixes_ before _Minor changes_

**Comment by ThrawnCA** [comment]
@Chealer I've adjusted the title a bit. Feel free to change it further if you want.

**Comment by Chealer** [comment]
The resource created at reproduction step #2 has a value of "https://beta.donneesquebec.ca/recherche/dataset/2095ec43-6e18-441d-a79a-fd400393093f/resource/0b9d8e64-9443-4f3e-8576-073966bb3c33/download/sondage.csv" in its `url` field. If I understand correctly, in some circumstances, step #3 will have the effect of mangling that URL, converting it into a basename/filename. For example, following step #3, the resource above would have a value of just "sondage.csv".
This is not normal.

> @Chealer I've adjusted the title a bit. Feel free to change it further if you want.

Thank you, but I do not have the privileges required to change this ticket's title.

**Comment by ThrawnCA** [comment]
> This is not normal.

If there is a more fundamental underlying issue, I'm not sure how to go about finding and fixing it.
