### ISSUE TITLE
Wrong file names for Chinese locales in the DataTables View

### ISSUE THREAD

**Issue by u10313335** [ckan/ckan#8424]
## CKAN version

2.10, 2.11, and master

## Describe the bug

In the `ckanext/datatablesview/assets/vendor/DataTables/i18n/` (2.11 and master) or `ckanext/datatablesview/public/vendor/DataTables/i18n/` (2.10), the file names of Chinese locales should be `zh_Hant_TW.json` and `zh_Hans_CN.json` (rather than `zh_Hant.json` and `zh_CN.json`), or they will not be loaded successfully under the corresponding locales.

### Steps to reproduce

N/A

### Expected behavior

The Chinese locales should be loaded without problems.

### Additional details

N/A

**Comment by amercader** [comment]
Shouldn't this be fixed in the upstream datatables repo? I think we just copy the distribution files as they are. I guess we could rename our vendored copy but then we'd have to remember to do the same on each updated.

Or we can also have a check in the [initialization script that we control](https://github.com/ckan/ckan/blob/ffd2531495946e997c95c43a6659a3c59304ff44/ckanext/datatablesview/assets/datatablesview.js#L384C11-L384C25) to translate `zh_Hant_TW.json` / `zh_Hans_CN.json` to `zh_Hant.json` / `zh_CN.json`.

**Comment by u10313335** [comment]
Thanks @amercader. I like the idea of altering the initialization script. Maybe something like this?

```diff
--- a/ckanext/datatablesview/public/datatablesview.js
+++ b/ckanext/datatablesview/public/datatablesview.js
@@ -385,6 +385,11 @@ this.ckan.module('datatables_view', function (jQuery) {
       // en is the default language, no need to load i18n file
       if (languagefile === '/vendor/DataTables/i18n/en.json') {
         activelanguage = ''
+      // load i18n files for zh_Hant_TW and zh_Hans_CN language
+      } else if (languagefile === '/vendor/DataTables/i18n/zh_Hant_TW.json') {
+        activelanguage = '/vendor/DataTables/i18n/zh_Hant.json'
+      } else if (languagefile === '/vendor/DataTables/i18n/zh_Hans_CN.json') {
+        activelanguage = '/vendor/DataTables/i18n/zh_CN.json'
       }

       // settings if gcurrentView === table
```

**Comment by amercader** [comment]
Looks good @u10313335 , want to submit a PR?

**Comment by u10313335** [comment]
Thanks @amercader. I have submitted two PRs for master and dev-v2.10.
