### ISSUE TITLE
The additional fields in the Additional Information section of the Resource screen are displayed duplicated

### ISSUE THREAD

**Issue by YukiNakamuraAbel** [ckan/ckan#8476]
## CKAN version
2.10.3
## Describe the bug
I am building an extension plugin and adding fields to the additional information on the resource screen.
When translating the field name added by i18n, the field before and after translation are duplicated.

### Steps to reproduce
1. Install and enable the following extension:
https://github.com/c-3lab/ckanext-feedback

2. Register the resource and switch the language setting from English to Japanese
3. Check that the items are duplicated on the resource details screen

<img width="411" alt="V0SNjzot" src="https://github.com/user-attachments/assets/1c5324b4-6f39-416a-b4a2-22abea7328f5">g)

### Expected behavior
The items are displayed without duplication

### Additional details
For debugging purposes, I inserted a debug log in the following location, and expected it to be called only once, but it was actually called twice.
I don't know if this is a feature or a bug.
https://github.com/c-3lab/ckanext-feedback/blob/main/ckanext/feedback/plugin.py#L383

**Comment by amercader** [comment]
I can't install ckanext-feedback without errors, but it looks like the issue is how you define the resource field names here:

https://github.com/c-3lab/ckanext-feedback/blob/6d452852d927b017614c135526c62955275b3cc4/ckanext/feedback/plugin.py#L385

If you use `_("Downloads")` as the key, whenever you change the language a new key will be added to the dict because `_("Downloads")` will have a different value (the Japanese translation). Just use `resource_dict["Downloads"]` to ensure you always use the same key, and when it's rendered in templates it will be translated (that's where it makes sense to wrap the key [with `_("...")`](https://github.com/ckan/ckan/blob/12c5e9adb77ace52b7d539c91f910b3c9ad510d6/ckan/templates/package/snippets/additional_info.html#L86))

Hope this helps

**Comment by k-nakahara21** [comment]
@amercader 
I am a member of the same development team as @YukiNakamuraAbel and I have taken over this issue and will answer.

By using `resource_dict[“Downloads”]`, it appears that no new keys are added to the dict and the items are no longer duplicated.
Thank you!
If you know, please let me know, what should I do to make the items added in the developed extentions in the Additional Information of this resource localize to Japanese as well?

(I have not read all of the following official documentation, would it help?:https://docs.ckan.org/en/2.10/contributing/i18n.html)

**Comment by amercader** [comment]
Sorry @k-nakahara21 I missed this comment. To translate strings in your own extension you need to follow the steps described here:

https://docs.ckan.org/en/2.10/extensions/translating-extensions.html

Hope this helps
